import type { HelpEntrySkeleton } from "../types";

export const AGENDA_ENTRIES: HelpEntrySkeleton[] = [
  { id: "ag-1", section: "agenda", related: ["ag-2", "ag-3", "ag-11"] },
  { id: "ag-2", section: "agenda", related: ["ag-1", "ag-51", "ag-55"] },
  { id: "ag-3", section: "agenda", related: ["ag-1", "ag-4", "ag-19"] },
  { id: "ag-4", section: "agenda", related: ["ag-1", "ag-5", "ag-6", "ag-7"] },
  { id: "ag-5", section: "agenda", related: ["ag-4", "ag-6", "ag-30", "ag-38"] },
  { id: "ag-6", section: "agenda", related: ["ag-4", "ag-5", "ag-31", "ag-32"] },
  { id: "ag-7", section: "agenda", related: ["ag-4", "ag-5", "ag-6", "ag-33"] },
  { id: "ag-8", section: "agenda", related: ["ag-4", "ag-5", "ag-6", "ag-7"] },
  { id: "ag-9", section: "agenda", related: ["ag-4", "ag-10", "ag-49"] },
  { id: "ag-10", section: "agenda", related: ["ag-9", "ag-19"] },
  { id: "ag-11", section: "agenda", related: ["ag-12", "ag-13", "ag-14", "ag-55"] },
  { id: "ag-12", section: "agenda", related: ["ag-11", "ag-13", "ag-14", "ag-15"] },
  { id: "ag-13", section: "agenda", related: ["ag-14", "ag-54", "ag-55", "ag-56"] },
  { id: "ag-14", section: "agenda", related: ["ag-13", "ag-54", "ag-55"] },
  { id: "ag-15", section: "agenda", related: ["ag-12", "ag-21", "ag-30"] },
  { id: "ag-16", section: "agenda", related: ["ag-17", "ag-18", "ag-25", "ag-35"] },
  { id: "ag-17", section: "agenda", related: ["ag-16", "ag-18", "ag-22", "ag-58"] },
  { id: "ag-18", section: "agenda", related: ["ag-16", "ag-17", "ag-25", "ag-26"] },
  { id: "ag-19", section: "agenda", related: ["ag-17", "ag-20", "ag-22"] },
  { id: "ag-20", section: "agenda", related: ["ag-17", "ag-21", "ag-22", "ag-23", "ag-24"] },
  { id: "ag-21", section: "agenda", related: ["ag-20", "ag-22", "ag-23", "ag-55"] },
  { id: "ag-22", section: "agenda", related: ["ag-20", "ag-23", "ag-24"] },
  { id: "ag-23", section: "agenda", related: ["ag-20", "ag-22", "ag-25"] },
  { id: "ag-24", section: "agenda", related: ["ag-22", "ag-20", "ag-16"] },
  { id: "ag-25", section: "agenda", related: ["ag-16", "ag-23", "ag-27", "ag-55"] },
  { id: "ag-26", section: "agenda", related: ["ag-16", "ag-18", "ag-35"] },
  { id: "ag-27", section: "agenda", related: ["ag-25", "ag-28", "ag-55"] },
  { id: "ag-28", section: "agenda", related: ["ag-11", "ag-27"] },
  { id: "ag-29", section: "agenda", related: ["ag-30", "ag-57", "ag-58"] },
  { id: "ag-30", section: "agenda", related: ["ag-5", "ag-6", "ag-29"] },
  { id: "ag-31", section: "agenda", related: ["ag-6", "ag-32"] },
  { id: "ag-32", section: "agenda", related: ["ag-6", "ag-30", "ag-31", "ag-38"] },
  { id: "ag-33", section: "agenda", related: ["ag-7", "ag-9"] },
  { id: "ag-34", section: "agenda", related: ["ag-1", "ag-29", "ag-57"] },
  { id: "ag-35", section: "agenda", related: ["ag-16", "ag-29"] },
  { id: "ag-36", section: "agenda", related: ["ag-16", "ag-37", "ag-38"] },
  { id: "ag-37", section: "agenda", related: ["ag-36", "ag-38"] },
  { id: "ag-38", section: "agenda", related: ["ag-5", "ag-30", "ag-47"] },
  { id: "ag-39", section: "agenda", related: ["ag-16", "ag-18"] },
  { id: "ag-40", section: "agenda", related: ["ag-5", "ag-41", "ag-47"] },
  { id: "ag-41", section: "agenda", related: ["ag-40", "ag-42", "ag-43"] },
  { id: "ag-42", section: "agenda", related: ["ag-41", "ag-43", "ag-44"] },
  { id: "ag-43", section: "agenda", related: ["ag-42", "ag-44", "ag-46"] },
  { id: "ag-44", section: "agenda", related: ["ag-42", "ag-43", "ag-46"] },
  { id: "ag-45", section: "agenda", related: ["ag-42", "ag-55"] },
  { id: "ag-46", section: "agenda", related: ["ag-44", "ag-43"] },
  { id: "ag-47", section: "agenda", related: ["ag-28", "ag-11"] },
  { id: "ag-48", section: "agenda", related: ["ag-13", "ag-14", "ag-58"] },
  { id: "ag-49", section: "agenda", related: ["ag-50", "ag-55"] },
  { id: "ag-50", section: "agenda", related: ["ag-49", "ag-7"] },
  { id: "ag-51", section: "agenda", related: ["ag-4", "ag-5"] },
  { id: "ag-52", section: "agenda", related: ["ag-7", "ag-36", "ag-37"] },
  { id: "ag-53", section: "agenda", related: ["ag-1", "ag-47"] },
  { id: "ag-54", section: "agenda", related: ["ag-13", "ag-14", "ag-55", "ag-56"] },
  { id: "ag-55", section: "agenda", related: ["ag-13", "ag-54", "ag-56"] },
  { id: "ag-56", section: "agenda", related: ["ag-55", "ag-54"] },
  { id: "ag-57", section: "agenda", related: ["ag-58", "ag-29"] },
  { id: "ag-58", section: "agenda", related: ["ag-57", "ag-59", "ag-60"] },
  { id: "ag-59", section: "agenda", related: ["ag-58", "ag-60"] },
  { id: "ag-60", section: "agenda", related: ["ag-58", "ag-59", "ag-57"] },
];
