import type { HelpEntrySkeleton } from "../types";

export const AGENDA_HORARIO_ENTRIES: HelpEntrySkeleton[] = [
  { id: "ah-1", section: "agenda-horario", related: ["ah-2", "ah-3", "ah-9"] },
  { id: "ah-2", section: "agenda-horario", related: ["ah-1", "ah-13", "ah-14"] },
  { id: "ah-3", section: "agenda-horario", related: ["ah-1", "ah-9", "ah-31"] },
  { id: "ah-4", section: "agenda-horario", related: ["ah-5", "ah-6", "ah-39"] },
  { id: "ah-5", section: "agenda-horario", related: ["ah-4", "ah-6", "ah-7"] },
  { id: "ah-6", section: "agenda-horario", related: ["ah-5", "ah-4", "ah-13"] },
  { id: "ah-7", section: "agenda-horario", related: ["ah-5", "ah-11", "ah-16"] },
  { id: "ah-8", section: "agenda-horario", related: ["ah-9", "ah-22", "ah-26"] },
  { id: "ah-9", section: "agenda-horario", related: ["ah-1", "ah-10", "ah-22"] },
  { id: "ah-10", section: "agenda-horario", related: ["ah-9", "ah-22", "ah-34"] },
  { id: "ah-11", section: "agenda-horario", related: ["ah-7", "ah-13", "ah-32"] },
  { id: "ah-12", section: "agenda-horario", related: ["ah-5", "ah-8", "ah-24"] },
  { id: "ah-13", section: "agenda-horario", related: ["ah-14", "ah-26", "ah-32"] },
  { id: "ah-14", section: "agenda-horario", related: ["ah-15", "ah-16", "ah-27"] },
  { id: "ah-15", section: "agenda-horario", related: ["ah-14", "ah-16", "ah-27"] },
  { id: "ah-16", section: "agenda-horario", related: ["ah-14", "ah-27", "ah-29"] },
  { id: "ah-17", section: "agenda-horario", related: ["ah-25", "ah-27", "ah-30"] },
  { id: "ah-18", section: "agenda-horario", related: ["ah-39", "ah-19", "ah-29"] },
  { id: "ah-19", section: "agenda-horario", related: ["ah-1", "ah-14", "ah-31"] },
  { id: "ah-20", section: "agenda-horario", related: ["ah-13", "ah-18", "ah-33"] },
  { id: "ah-21", section: "agenda-horario", related: ["ah-22", "ah-33", "ah-34"] },
  { id: "ah-22", section: "agenda-horario", related: ["ah-18", "ah-27", "ah-39"] },
  { id: "ah-23", section: "agenda-horario", related: ["ah-12", "ah-34", "ah-24"] },
  { id: "ah-24", section: "agenda-horario", related: ["ah-17", "ah-9", "ah-10"] },
  { id: "ah-25", section: "agenda-horario", related: ["ah-9", "ah-13", "ah-34"] },
  { id: "ah-26", section: "agenda-horario", related: ["ah-9", "ah-25", "ah-32"] },
  { id: "ah-27", section: "agenda-horario", related: ["ah-17", "ah-30", "ah-37"] },
  { id: "ah-28", section: "agenda-horario", related: ["ah-19", "ah-29", "ah-31"] },
  { id: "ah-29", section: "agenda-horario", related: ["ah-28", "ah-31", "ah-35"] },
  { id: "ah-30", section: "agenda-horario", related: ["ah-8", "ah-14", "ah-37"] },
  { id: "ah-31", section: "agenda-horario", related: ["ah-10", "ah-34", "ah-36"] },
  { id: "ah-32", section: "agenda-horario", related: ["ah-11", "ah-13", "ah-35"] },
  { id: "ah-33", section: "agenda-horario", related: ["ah-20", "ah-21", "ah-39"] },
  { id: "ah-34", section: "agenda-horario", related: ["ah-10", "ah-29", "ah-35"] },
  { id: "ah-35", section: "agenda-horario", related: ["ah-1", "ah-3", "ah-19"] },
  { id: "ah-36", section: "agenda-horario", related: ["ah-10", "ah-30", "ah-31"] },
  { id: "ah-37", section: "agenda-horario", related: ["ah-8", "ah-28", "ah-29"] },
  { id: "ah-38", section: "agenda-horario", related: ["ah-32", "ah-34", "ah-35"] },
  { id: "ah-39", section: "agenda-horario", related: ["ah-4", "ah-18", "ah-22"] },
  { id: "ah-40", section: "agenda-horario", related: ["ah-1", "ah-8", "ah-31"] },
];
