import type { HelpEntrySkeleton } from "../types";

export const AGENDA_GOOGLE_ENTRIES: HelpEntrySkeleton[] = [
  { id: "ago-1", section: "agenda-google", related: ["ago-2", "ago-3", "ago-12"] },
  { id: "ago-2", section: "agenda-google", related: ["ago-1", "ago-10", "ago-11"] },
  { id: "ago-3", section: "agenda-google", related: ["ago-1", "ago-4", "ago-24"] },
  { id: "ago-4", section: "agenda-google", related: ["ago-3", "ago-17", "ago-21"] },
  { id: "ago-5", section: "agenda-google", related: ["ago-3", "ago-6", "ago-7"] },
  { id: "ago-6", section: "agenda-google", related: ["ago-5", "ago-8", "ago-38"] },
  { id: "ago-7", section: "agenda-google", related: ["ago-17", "ago-18", "ago-26"] },
  { id: "ago-8", section: "agenda-google", related: ["ago-1", "ago-9", "ago-11"] },
  { id: "ago-9", section: "agenda-google", related: ["ago-8", "ago-10", "ago-17"] },
  { id: "ago-10", section: "agenda-google", related: ["ago-8", "ago-9", "ago-17"] },
  { id: "ago-11", section: "agenda-google", related: ["ago-12", "ago-13", "ago-34"] },
  { id: "ago-12", section: "agenda-google", related: ["ago-11", "ago-35", "ago-36"] },
  { id: "ago-13", section: "agenda-google", related: ["ago-11", "ago-37", "ago-38"] },
  { id: "ago-14", section: "agenda-google", related: ["ago-15", "ago-16"] },
  { id: "ago-15", section: "agenda-google", related: ["ago-14", "ago-16", "ago-40"] },
  { id: "ago-16", section: "agenda-google", related: ["ago-14", "ago-15", "ago-29"] },
  { id: "ago-17", section: "agenda-google", related: ["ago-7", "ago-18", "ago-19"] },
  { id: "ago-18", section: "agenda-google", related: ["ago-17", "ago-19", "ago-21"] },
  { id: "ago-19", section: "agenda-google", related: ["ago-17", "ago-18", "ago-21"] },
  { id: "ago-20", section: "agenda-google", related: ["ago-19", "ago-21", "ago-22"] },
  { id: "ago-21", section: "agenda-google", related: ["ago-20", "ago-22"] },
  { id: "ago-22", section: "agenda-google", related: ["ago-5", "ago-20", "ago-21"] },
  { id: "ago-23", section: "agenda-google", related: ["ago-29", "ago-32"] },
  { id: "ago-24", section: "agenda-google", related: ["ago-25", "ago-26", "ago-27"] },
  { id: "ago-25", section: "agenda-google", related: ["ago-24", "ago-26", "ago-27"] },
  { id: "ago-26", section: "agenda-google", related: ["ago-25", "ago-27"] },
  { id: "ago-27", section: "agenda-google", related: ["ago-25", "ago-26"] },
  { id: "ago-28", section: "agenda-google", related: ["ago-29", "ago-30"] },
  { id: "ago-29", section: "agenda-google", related: ["ago-28", "ago-30"] },
  { id: "ago-30", section: "agenda-google", related: ["ago-28", "ago-29"] },
  { id: "ago-31", section: "agenda-google", related: ["ago-32", "ago-33"] },
  { id: "ago-32", section: "agenda-google", related: ["ago-31", "ago-33", "ago-39"] },
  { id: "ago-33", section: "agenda-google", related: ["ago-32", "ago-35"] },
  { id: "ago-34", section: "agenda-google", related: ["ago-10", "ago-32"] },
  { id: "ago-35", section: "agenda-google", related: ["ago-1", "ago-8", "ago-36"] },
  { id: "ago-36", section: "agenda-google", related: ["ago-20", "ago-21"] },
  { id: "ago-37", section: "agenda-google", related: ["ago-38"] },
  { id: "ago-38", section: "agenda-google", related: ["ago-37"] },
  { id: "ago-39", section: "agenda-google", related: ["ago-32", "ago-33"] },
  { id: "ago-40", section: "agenda-google", related: ["ago-15", "ago-20", "ago-22"] },
];
