import type { HelpEntrySkeleton } from "../types";

export const AJUSTES_COBROS_ENTRIES: HelpEntrySkeleton[] = [
  { id: "ajc-1", section: "ajustes-cobros", related: ["ajc-2", "ajc-3", "ajc-6"] },
  { id: "ajc-2", section: "ajustes-cobros", related: ["ajc-1", "ajc-3", "ajc-4"] },
  { id: "ajc-3", section: "ajustes-cobros", related: ["ajc-2", "ajc-14", "ajc-15"] },
  { id: "ajc-4", section: "ajustes-cobros", related: ["ajc-1", "ajc-5", "ajc-22"] },
  { id: "ajc-5", section: "ajustes-cobros", related: ["ajc-4", "ajc-6", "ajc-22"] },
  { id: "ajc-6", section: "ajustes-cobros", related: ["ajc-1", "ajc-7", "ajc-8"] },
  { id: "ajc-7", section: "ajustes-cobros", related: ["ajc-6", "ajc-10", "ajc-20"] },
  { id: "ajc-8", section: "ajustes-cobros", related: ["ajc-9", "ajc-15", "ajc-16"] },
  { id: "ajc-9", section: "ajustes-cobros", related: ["ajc-8", "ajc-16", "ajc-17"] },
  { id: "ajc-10", section: "ajustes-cobros", related: ["ajc-7", "ajc-9", "ajc-20"] },
  { id: "ajc-11", section: "ajustes-cobros", related: ["ajc-12", "ajc-13", "ajc-4"] },
  { id: "ajc-12", section: "ajustes-cobros", related: ["ajc-11", "ajc-13", "ajc-14"] },
  { id: "ajc-13", section: "ajustes-cobros", related: ["ajc-11", "ajc-12", "ajc-17"] },
  { id: "ajc-14", section: "ajustes-cobros", related: ["ajc-3", "ajc-15", "ajc-12"] },
  { id: "ajc-15", section: "ajustes-cobros", related: ["ajc-3", "ajc-14", "ajc-18"] },
  { id: "ajc-16", section: "ajustes-cobros", related: ["ajc-4", "ajc-17", "ajc-20"] },
  { id: "ajc-17", section: "ajustes-cobros", related: ["ajc-9", "ajc-16", "ajc-13"] },
  { id: "ajc-18", section: "ajustes-cobros", related: ["ajc-19", "ajc-15", "ajc-13"] },
  { id: "ajc-19", section: "ajustes-cobros", related: ["ajc-18", "ajc-9", "ajc-25"] },
  { id: "ajc-20", section: "ajustes-cobros", related: ["ajc-21", "ajc-7", "ajc-16"] },
  { id: "ajc-21", section: "ajustes-cobros", related: ["ajc-20", "ajc-4", "ajc-24"] },
  { id: "ajc-22", section: "ajustes-cobros", related: ["ajc-4", "ajc-5", "ajc-23"] },
  { id: "ajc-23", section: "ajustes-cobros", related: ["ajc-24", "ajc-7", "ajc-19"] },
  { id: "ajc-24", section: "ajustes-cobros", related: ["ajc-23", "ajc-11", "ajc-1"] },
  { id: "ajc-25", section: "ajustes-cobros", related: ["ajc-5", "ajc-4", "ajc-16"] },
];
