import type { HelpEntrySkeleton } from "../types";

export const AJUSTES_SUSCRIPCION_ENTRIES: HelpEntrySkeleton[] = [
  { id: "ajs-1", section: "ajustes-suscripcion", related: ["ajs-2", "ajs-3", "ajs-8"] },
  { id: "ajs-2", section: "ajustes-suscripcion", related: ["ajs-1", "ajs-3", "ajs-4"] },
  { id: "ajs-3", section: "ajustes-suscripcion", related: ["ajs-1", "ajs-4", "ajs-14"] },
  { id: "ajs-4", section: "ajustes-suscripcion", related: ["ajs-3", "ajs-5", "ajs-15"] },
  { id: "ajs-5", section: "ajustes-suscripcion", related: ["ajs-1", "ajs-6", "ajs-24"] },
  { id: "ajs-6", section: "ajustes-suscripcion", related: ["ajs-7", "ajs-9", "ajs-23"] },
  { id: "ajs-7", section: "ajustes-suscripcion", related: ["ajs-6", "ajs-9", "ajs-23"] },
  { id: "ajs-8", section: "ajustes-suscripcion", related: ["ajs-1", "ajs-10", "ajs-11"] },
  { id: "ajs-9", section: "ajustes-suscripcion", related: ["ajs-6", "ajs-7", "ajs-11"] },
  { id: "ajs-10", section: "ajustes-suscripcion", related: ["ajs-11", "ajs-12", "ajs-13"] },
  { id: "ajs-11", section: "ajustes-suscripcion", related: ["ajs-10", "ajs-12", "ajs-6"] },
  { id: "ajs-12", section: "ajustes-suscripcion", related: ["ajs-10", "ajs-11", "ajs-7"] },
  { id: "ajs-13", section: "ajustes-suscripcion", related: ["ajs-14", "ajs-17", "ajs-22"] },
  { id: "ajs-14", section: "ajustes-suscripcion", related: ["ajs-13", "ajs-3", "ajs-22"] },
  { id: "ajs-15", section: "ajustes-suscripcion", related: ["ajs-16", "ajs-13", "ajs-14"] },
  { id: "ajs-16", section: "ajustes-suscripcion", related: ["ajs-15", "ajs-13", "ajs-14"] },
  { id: "ajs-17", section: "ajustes-suscripcion", related: ["ajs-18", "ajs-10", "ajs-13"] },
  { id: "ajs-18", section: "ajustes-suscripcion", related: ["ajs-17", "ajs-25", "ajs-10"] },
  { id: "ajs-19", section: "ajustes-suscripcion", related: ["ajs-20", "ajs-10", "ajs-24"] },
  { id: "ajs-20", section: "ajustes-suscripcion", related: ["ajs-21", "ajs-7", "ajs-24"] },
  { id: "ajs-21", section: "ajustes-suscripcion", related: ["ajs-20", "ajs-10", "ajs-24"] },
  { id: "ajs-22", section: "ajustes-suscripcion", related: ["ajs-13", "ajs-14", "ajs-17"] },
  { id: "ajs-23", section: "ajustes-suscripcion", related: ["ajs-14", "ajs-13", "ajs-10"] },
  { id: "ajs-24", section: "ajustes-suscripcion", related: ["ajs-5", "ajs-19", "ajs-10"] },
  { id: "ajs-25", section: "ajustes-suscripcion", related: ["ajs-6", "ajs-7", "ajs-18"] },
];
