import type { HelpEntrySkeleton } from "../types";

export const AJUSTES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "aj-1", section: "ajustes", related: ["aj-2", "aj-4", "aj-18"] },
  { id: "aj-2", section: "ajustes", related: ["aj-1", "aj-3", "aj-5"] },
  { id: "aj-3", section: "ajustes", related: ["aj-2", "aj-6", "aj-10"] },
  { id: "aj-4", section: "ajustes", related: ["aj-1", "aj-14", "aj-15"] },
  { id: "aj-5", section: "ajustes", related: ["aj-3", "aj-6", "aj-22"] },
  { id: "aj-6", section: "ajustes", related: ["aj-5", "aj-7", "aj-3"] },
  { id: "aj-7", section: "ajustes", related: ["aj-3", "aj-6", "aj-10"] },
  { id: "aj-8", section: "ajustes", related: ["aj-2", "aj-3", "aj-17"] },
  { id: "aj-9", section: "ajustes", related: ["aj-5", "aj-22", "aj-28"] },
  { id: "aj-10", section: "ajustes", related: ["aj-11", "aj-1", "aj-3"] },
  { id: "aj-11", section: "ajustes", related: ["aj-10", "aj-4", "aj-12"] },
  { id: "aj-12", section: "ajustes", related: ["aj-11", "aj-10", "aj-4"] },
  { id: "aj-13", section: "ajustes", related: ["aj-10", "aj-19", "aj-3"] },
  { id: "aj-14", section: "ajustes", related: ["aj-15", "aj-19", "aj-4"] },
  { id: "aj-15", section: "ajustes", related: ["aj-14", "aj-10", "aj-24"] },
  { id: "aj-16", section: "ajustes", related: ["aj-10", "aj-20", "aj-27"] },
  { id: "aj-17", section: "ajustes", related: ["aj-10", "aj-3", "aj-19"] },
  { id: "aj-18", section: "ajustes", related: ["aj-1", "aj-21", "aj-2"] },
  { id: "aj-19", section: "ajustes", related: ["aj-27", "aj-10", "aj-25"] },
  { id: "aj-20", section: "ajustes", related: ["aj-14", "aj-3", "aj-1"] },
  { id: "aj-21", section: "ajustes", related: ["aj-22", "aj-18", "aj-28"] },
  { id: "aj-22", section: "ajustes", related: ["aj-23", "aj-1", "aj-21"] },
  { id: "aj-23", section: "ajustes", related: ["aj-22", "aj-9", "aj-6"] },
  { id: "aj-24", section: "ajustes", related: ["aj-26", "aj-15", "aj-3"] },
  { id: "aj-25", section: "ajustes", related: ["aj-24", "aj-19", "aj-26"] },
  { id: "aj-26", section: "ajustes", related: ["aj-24", "aj-14", "aj-13"] },
  { id: "aj-27", section: "ajustes", related: ["aj-13", "aj-25", "aj-24"] },
  { id: "aj-28", section: "ajustes", related: ["aj-9", "aj-22", "aj-2"] },
  { id: "aj-29", section: "ajustes", related: ["aj-18", "aj-21", "aj-2"] },
  { id: "aj-30", section: "ajustes", related: ["aj-6", "aj-23", "aj-1"] },
];
