import type { HelpEntrySkeleton } from "../types";

export const AJUSTES_INTEGRACIONES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "aji-1", section: "ajustes-integraciones", related: ["aji-2", "aji-3", "aji-20"] },
  { id: "aji-2", section: "ajustes-integraciones", related: ["aji-1", "aji-20", "aji-21"] },
  { id: "aji-3", section: "ajustes-integraciones", related: ["aji-4", "aji-5", "aji-7"] },
  { id: "aji-4", section: "ajustes-integraciones", related: ["aji-3", "aji-5", "aji-6"] },
  { id: "aji-5", section: "ajustes-integraciones", related: ["aji-6", "aji-17", "aji-23"] },
  { id: "aji-6", section: "ajustes-integraciones", related: ["aji-5", "aji-17", "aji-18"] },
  { id: "aji-7", section: "ajustes-integraciones", related: ["aji-3", "aji-14", "aji-25"] },
  { id: "aji-8", section: "ajustes-integraciones", related: ["aji-1", "aji-19", "aji-24"] },
  { id: "aji-9", section: "ajustes-integraciones", related: ["aji-10", "aji-11", "aji-12"] },
  { id: "aji-10", section: "ajustes-integraciones", related: ["aji-9", "aji-11", "aji-14"] },
  { id: "aji-11", section: "ajustes-integraciones", related: ["aji-9", "aji-10", "aji-15"] },
  { id: "aji-12", section: "ajustes-integraciones", related: ["aji-9", "aji-13", "aji-20"] },
  { id: "aji-13", section: "ajustes-integraciones", related: ["aji-12", "aji-20", "aji-21"] },
  { id: "aji-14", section: "ajustes-integraciones", related: ["aji-7", "aji-10", "aji-20"] },
  { id: "aji-15", section: "ajustes-integraciones", related: ["aji-16", "aji-17", "aji-18"] },
  { id: "aji-16", section: "ajustes-integraciones", related: ["aji-15", "aji-17", "aji-19"] },
  { id: "aji-17", section: "ajustes-integraciones", related: ["aji-15", "aji-16", "aji-18"] },
  { id: "aji-18", section: "ajustes-integraciones", related: ["aji-3", "aji-15", "aji-16"] },
  { id: "aji-19", section: "ajustes-integraciones", related: ["aji-6", "aji-17", "aji-24"] },
  { id: "aji-20", section: "ajustes-integraciones", related: ["aji-2", "aji-21"] },
  { id: "aji-21", section: "ajustes-integraciones", related: ["aji-2", "aji-20"] },
  { id: "aji-22", section: "ajustes-integraciones", related: ["aji-23", "aji-25"] },
  { id: "aji-23", section: "ajustes-integraciones", related: ["aji-7", "aji-22", "aji-25"] },
  { id: "aji-24", section: "ajustes-integraciones", related: ["aji-6", "aji-17", "aji-19"] },
  { id: "aji-25", section: "ajustes-integraciones", related: ["aji-7", "aji-22", "aji-23"] },
];
