import type { HelpEntrySkeleton } from "../types";

export const DASHBOARD_ENTRIES: HelpEntrySkeleton[] = [
  { id: "dash-1", section: "dashboard", related: ["dash-2", "dash-3", "dash-7"] },
  { id: "dash-2", section: "dashboard", related: ["dash-1", "dash-11", "dash-19"] },
  { id: "dash-3", section: "dashboard", related: ["dash-1", "dash-44", "dash-48"] },
  { id: "dash-4", section: "dashboard", related: ["dash-5", "dash-6"] },
  { id: "dash-5", section: "dashboard", related: ["dash-4", "dash-6"] },
  { id: "dash-6", section: "dashboard", related: ["dash-4", "dash-5", "dash-34"] },
  { id: "dash-7", section: "dashboard", related: ["dash-8", "dash-9", "dash-10"] },
  { id: "dash-8", section: "dashboard", related: ["dash-7", "dash-9", "dash-10"] },
  { id: "dash-9", section: "dashboard", related: ["dash-7", "dash-10", "dash-23"] },
  { id: "dash-10", section: "dashboard", related: ["dash-7", "dash-34", "dash-35"] },
  { id: "dash-11", section: "dashboard", related: ["dash-12", "dash-40", "dash-41"] },
  { id: "dash-12", section: "dashboard", related: ["dash-11", "dash-40", "dash-41"] },
  { id: "dash-13", section: "dashboard", related: ["dash-14", "dash-15", "dash-16"] },
  { id: "dash-14", section: "dashboard", related: ["dash-13", "dash-15", "dash-17"] },
  { id: "dash-15", section: "dashboard", related: ["dash-13", "dash-14", "dash-16"] },
  { id: "dash-16", section: "dashboard", related: ["dash-15", "dash-17", "dash-18"] },
  { id: "dash-17", section: "dashboard", related: ["dash-13", "dash-18", "dash-45"] },
  { id: "dash-18", section: "dashboard", related: ["dash-13", "dash-20", "dash-46"] },
  { id: "dash-19", section: "dashboard", related: ["dash-13", "dash-15", "dash-20"] },
  { id: "dash-20", section: "dashboard", related: ["dash-19", "dash-21", "dash-50"] },
  { id: "dash-21", section: "dashboard", related: ["dash-22", "dash-23", "dash-24"] },
  { id: "dash-22", section: "dashboard", related: ["dash-21", "dash-23", "dash-24"] },
  { id: "dash-23", section: "dashboard", related: ["dash-7", "dash-21", "dash-25"] },
  { id: "dash-24", section: "dashboard", related: ["dash-21", "dash-25", "dash-27"] },
  { id: "dash-25", section: "dashboard", related: ["dash-21", "dash-24", "dash-26"] },
  { id: "dash-26", section: "dashboard", related: ["dash-21", "dash-22", "dash-25"] },
  { id: "dash-27", section: "dashboard", related: ["dash-21", "dash-26", "dash-47"] },
  { id: "dash-28", section: "dashboard", related: ["dash-3", "dash-29", "dash-48"] },
  { id: "dash-29", section: "dashboard", related: ["dash-21", "dash-28", "dash-30"] },
  { id: "dash-30", section: "dashboard", related: ["dash-11", "dash-40", "dash-41"] },
  { id: "dash-31", section: "dashboard", related: ["dash-28", "dash-29", "dash-30"] },
  { id: "dash-32", section: "dashboard", related: ["dash-1", "dash-33", "dash-46"] },
  { id: "dash-33", section: "dashboard", related: ["dash-32", "dash-44"] },
  { id: "dash-34", section: "dashboard", related: ["dash-10", "dash-35", "dash-37"] },
  { id: "dash-35", section: "dashboard", related: ["dash-10", "dash-34", "dash-36"] },
  { id: "dash-36", section: "dashboard", related: ["dash-34", "dash-35", "dash-37"] },
  { id: "dash-37", section: "dashboard", related: ["dash-34", "dash-36", "dash-50"] },
  { id: "dash-38", section: "dashboard", related: ["dash-39", "dash-46", "dash-48"] },
  { id: "dash-39", section: "dashboard", related: ["dash-18", "dash-38", "dash-46"] },
  { id: "dash-40", section: "dashboard", related: ["dash-11", "dash-30", "dash-41"] },
  { id: "dash-41", section: "dashboard", related: ["dash-11", "dash-30", "dash-40"] },
  { id: "dash-42", section: "dashboard", related: ["dash-3", "dash-37", "dash-44"] },
  { id: "dash-43", section: "dashboard", related: ["dash-7", "dash-8", "dash-9"] },
  { id: "dash-44", section: "dashboard", related: ["dash-3", "dash-28", "dash-48"] },
  { id: "dash-45", section: "dashboard", related: ["dash-13", "dash-17", "dash-46"] },
  { id: "dash-46", section: "dashboard", related: ["dash-18", "dash-39", "dash-45"] },
  { id: "dash-47", section: "dashboard", related: ["dash-9", "dash-12", "dash-20"] },
  { id: "dash-48", section: "dashboard", related: ["dash-3", "dash-38", "dash-44"] },
  { id: "dash-49", section: "dashboard", related: ["dash-19", "dash-20", "dash-50"] },
  { id: "dash-50", section: "dashboard", related: ["dash-37", "dash-42", "dash-49"] },
];
