import type { HelpEntrySkeleton } from "../types";

export const DIETA_COMPARTIR_ENTRIES: HelpEntrySkeleton[] = [
  { id: "dc-1", section: "dieta-compartir", related: ["dc-2", "dc-13", "dc-14"] },
  { id: "dc-2", section: "dieta-compartir", related: ["dc-1", "dc-3", "dc-16"] },
  { id: "dc-3", section: "dieta-compartir", related: ["dc-2", "dc-4", "dc-5"] },
  { id: "dc-4", section: "dieta-compartir", related: ["dc-3", "dc-5", "dc-14"] },
  { id: "dc-5", section: "dieta-compartir", related: ["dc-3", "dc-4", "dc-11"] },
  { id: "dc-6", section: "dieta-compartir", related: ["dc-7", "dc-8", "dc-22"] },
  { id: "dc-7", section: "dieta-compartir", related: ["dc-6", "dc-13", "dc-14"] },
  { id: "dc-8", section: "dieta-compartir", related: ["dc-6", "dc-13", "dc-27"] },
  { id: "dc-9", section: "dieta-compartir", related: ["dc-10", "dc-17", "dc-20"] },
  { id: "dc-10", section: "dieta-compartir", related: ["dc-9", "dc-15", "dc-17"] },
  { id: "dc-11", section: "dieta-compartir", related: ["dc-16", "dc-17", "dc-9"] },
  { id: "dc-12", section: "dieta-compartir", related: ["dc-19", "dc-20", "dc-6"] },
  { id: "dc-13", section: "dieta-compartir", related: ["dc-7", "dc-14", "dc-27"] },
  { id: "dc-14", section: "dieta-compartir", related: ["dc-13", "dc-7", "dc-27"] },
  { id: "dc-15", section: "dieta-compartir", related: ["dc-9", "dc-10", "dc-17"] },
  { id: "dc-16", section: "dieta-compartir", related: ["dc-11", "dc-10", "dc-17"] },
  { id: "dc-17", section: "dieta-compartir", related: ["dc-10", "dc-9", "dc-11"] },
  { id: "dc-18", section: "dieta-compartir", related: ["dc-19", "dc-28", "dc-6"] },
  { id: "dc-19", section: "dieta-compartir", related: ["dc-18", "dc-13", "dc-28"] },
  { id: "dc-20", section: "dieta-compartir", related: ["dc-9", "dc-12", "dc-2"] },
  { id: "dc-21", section: "dieta-compartir", related: ["dc-28", "dc-6", "dc-24"] },
  { id: "dc-22", section: "dieta-compartir", related: ["dc-6", "dc-21", "dc-28"] },
  { id: "dc-23", section: "dieta-compartir", related: ["dc-6", "dc-24", "dc-25"] },
  { id: "dc-24", section: "dieta-compartir", related: ["dc-6", "dc-21", "dc-22"] },
  { id: "dc-25", section: "dieta-compartir", related: ["dc-6", "dc-23", "dc-24"] },
  { id: "dc-26", section: "dieta-compartir", related: ["dc-2", "dc-4", "dc-5"] },
  { id: "dc-27", section: "dieta-compartir", related: ["dc-8", "dc-13", "dc-14"] },
  { id: "dc-28", section: "dieta-compartir", related: ["dc-18", "dc-21", "dc-19"] },
  { id: "dc-29", section: "dieta-compartir", related: ["dc-6", "dc-22", "dc-8"] },
  { id: "dc-30", section: "dieta-compartir", related: ["dc-3", "dc-10", "dc-17"] },
  { id: "dc-31", section: "dieta-compartir", related: ["dc-12", "dc-17", "dc-20"] },
  { id: "dc-32", section: "dieta-compartir", related: ["dc-2", "dc-10", "dc-5"] },
  { id: "dc-33", section: "dieta-compartir", related: ["dc-4", "dc-5", "dc-23"] },
  { id: "dc-34", section: "dieta-compartir", related: ["dc-9", "dc-10", "dc-20"] },
  { id: "dc-35", section: "dieta-compartir", related: ["dc-12", "dc-20", "dc-15"] },
];
