import type { HelpEntrySkeleton } from "../types";

export const DIETAS_ENTRIES: HelpEntrySkeleton[] = [
  { id: "di-1", section: "dietas", related: ["di-2", "di-4", "di-26"] },
  { id: "di-2", section: "dietas", related: ["di-3", "di-14", "di-15"] },
  { id: "di-3", section: "dietas", related: ["di-2", "di-8", "di-11"] },
  { id: "di-4", section: "dietas", related: ["di-5", "di-6", "di-7"] },
  { id: "di-5", section: "dietas", related: ["di-22", "di-37", "di-4"] },
  { id: "di-6", section: "dietas", related: ["di-4", "di-30", "di-34"] },
  { id: "di-7", section: "dietas", related: ["di-25", "di-26", "di-4"] },
  { id: "di-8", section: "dietas", related: ["di-9", "di-10", "di-17"] },
  { id: "di-9", section: "dietas", related: ["di-8", "di-10", "di-17"] },
  { id: "di-10", section: "dietas", related: ["di-8", "di-9", "di-17"] },
  { id: "di-11", section: "dietas", related: ["di-12", "di-13", "di-39"] },
  { id: "di-12", section: "dietas", related: ["di-11", "di-13", "di-28"] },
  { id: "di-13", section: "dietas", related: ["di-11", "di-12", "di-39"] },
  { id: "di-14", section: "dietas", related: ["di-15", "di-16", "di-2"] },
  { id: "di-15", section: "dietas", related: ["di-14", "di-16", "di-11"] },
  { id: "di-16", section: "dietas", related: ["di-14", "di-15", "di-45"] },
  { id: "di-17", section: "dietas", related: ["di-18", "di-19", "di-22"] },
  { id: "di-18", section: "dietas", related: ["di-17", "di-25", "di-31"] },
  { id: "di-19", section: "dietas", related: ["di-17", "di-18", "di-31"] },
  { id: "di-20", section: "dietas", related: ["di-21", "di-39", "di-43"] },
  { id: "di-21", section: "dietas", related: ["di-20", "di-3"] },
  { id: "di-22", section: "dietas", related: ["di-5", "di-37", "di-16"] },
  { id: "di-23", section: "dietas", related: ["di-3", "di-28", "di-45"] },
  { id: "di-24", section: "dietas", related: ["di-7", "di-25", "di-26"] },
  { id: "di-25", section: "dietas", related: ["di-24", "di-7", "di-18"] },
  { id: "di-26", section: "dietas", related: ["di-11", "di-27", "di-39"] },
  { id: "di-27", section: "dietas", related: ["di-26", "di-11", "di-13"] },
  { id: "di-28", section: "dietas", related: ["di-23", "di-11", "di-17"] },
  { id: "di-29", section: "dietas", related: ["di-30", "di-34", "di-6"] },
  { id: "di-30", section: "dietas", related: ["di-29", "di-6", "di-17"] },
  { id: "di-31", section: "dietas", related: ["di-19", "di-18", "di-12"] },
  { id: "di-32", section: "dietas", related: ["di-4", "di-7", "di-17"] },
  { id: "di-33", section: "dietas", related: ["di-11", "di-20", "di-26"] },
  { id: "di-34", section: "dietas", related: ["di-5", "di-22", "di-37"] },
  { id: "di-35", section: "dietas", related: ["di-22", "di-3", "di-11"] },
  { id: "di-36", section: "dietas", related: ["di-2", "di-23", "di-14"] },
  { id: "di-37", section: "dietas", related: ["di-5", "di-22", "di-17"] },
  { id: "di-38", section: "dietas", related: ["di-19", "di-11", "di-13"] },
  { id: "di-39", section: "dietas", related: ["di-13", "di-11", "di-33"] },
  { id: "di-40", section: "dietas", related: ["di-14", "di-27", "di-12"] },
  { id: "di-41", section: "dietas", related: ["di-3", "di-17"] },
  { id: "di-42", section: "dietas", related: ["di-15", "di-14", "di-11"] },
  { id: "di-43", section: "dietas", related: ["di-20", "di-33"] },
  { id: "di-44", section: "dietas", related: ["di-40", "di-14", "di-3"] },
  { id: "di-45", section: "dietas", related: ["di-14", "di-15", "di-16"] },
];
