import type { HelpEntry } from "../types";

export const DIETAS_ENTRIES: HelpEntry[] = [
  {
    id: "di-1",
    section: "dietas",
    question: "¿Qué es la sección Dietas?",
    answer: "La sección Dietas (ruta /dietas) es el centro donde se listan todos los planes alimenticios que has creado para tus pacientes. Desde aquí puedes consultar, filtrar, crear, editar, compartir y eliminar cualquier plan, así como marcar cuál es el plan Actual de cada paciente. Es el punto de partida para trabajar la parte nutricional de la consulta.",
    related: ["di-2", "di-4", "di-26"],
    keywords: ["dietas", "sección", "planes", "alimenticios", "qué es"],
  },
  {
    id: "di-2",
    section: "dietas",
    question: "¿Cómo se ve el listado de planes?",
    answer: "El listado muestra una cuadrícula de tarjetas, una por plan. Cada tarjeta resume la información clave: nombre del plan, paciente al que pertenece, calorías objetivo, macros objetivo, fecha de creación, número de días y comidas y un distintivo \"Actual\" si es el plan vigente del paciente. Arriba dispones de filtros por paciente, por estado y de un buscador.",
    related: ["di-3", "di-14", "di-15"],
    keywords: ["listado", "planes", "vista", "tarjetas", "cards"],
  },
  {
    id: "di-3",
    section: "dietas",
    question: "¿Qué información muestra la card de un plan?",
    answer: "Cada card de plan incluye: nombre del plan, paciente asociado (con foto o iniciales), calorías objetivo diarias, macros objetivo en gramos (proteínas, carbohidratos y grasas), fecha de creación, número de días y de comidas configurados y el distintivo \"Actual\" si corresponde. En la parte inferior encontrarás los botones de abrir, editar, compartir y eliminar.",
    related: ["di-2", "di-8", "di-11"],
    keywords: ["card", "tarjeta", "plan", "información", "datos"],
  },
  {
    id: "di-4",
    section: "dietas",
    question: "¿Cómo creo un nuevo plan?",
    answer: "Pulsa el botón \"+ Nuevo plan\" arriba a la derecha del listado. Se abrirá la ruta /dietas/nuevo con el formulario de creación. Selecciona el paciente, escribe un nombre para el plan y, opcionalmente, parte de una plantilla o ajusta las calorías y los macros objetivo. Al guardar se crea el plan vacío y se abre el editor para añadir días y comidas.",
    related: ["di-5", "di-6", "di-7"],
    keywords: ["crear", "nuevo", "plan", "alta", "añadir"],
  },
  {
    id: "di-5",
    section: "dietas",
    question: "¿Qué escribo en el campo \"Nombre del plan\"?",
    answer: "El nombre del plan es un texto libre que te ayuda a identificarlo en el listado. Puedes usar frases como \"Plan semana 1\", \"Definición marzo\", \"Mantenimiento post-objetivo\" o \"Plan hipocalórico 1600 kcal\". Es obligatorio y aparecerá en la card, en la ficha del paciente y en el portal del paciente.",
    related: ["di-22", "di-37", "di-4"],
    keywords: ["nombre", "título", "plan", "campo"],
  },
  {
    id: "di-6",
    section: "dietas",
    question: "¿Cómo selecciono el paciente al crear un plan?",
    answer: "En el formulario de /dietas/nuevo tienes un desplegable \"Paciente\" con todos los pacientes activos de tu consulta. Empieza a escribir el nombre para filtrar. Debes seleccionar uno para poder guardar el plan, salvo que tu suscripción permita planes sin asignar. El plan quedará vinculado a ese paciente.",
    related: ["di-4", "di-30", "di-34"],
    keywords: ["seleccionar", "paciente", "asignar", "desplegable"],
  },
  {
    id: "di-7",
    section: "dietas",
    question: "¿Puedo empezar desde cero o usar una plantilla?",
    answer: "En el formulario de nuevo plan puedes elegir \"Empezar desde cero\", que crea un plan vacío al que añades días y comidas manualmente, o \"Partir de plantilla\", que clona una plantilla tuya previamente guardada. Partir de plantilla es útil para no empezar siempre desde la página en blanco cuando repites esquemas.",
    related: ["di-25", "di-26", "di-4"],
    keywords: ["plantilla", "cero", "empezar", "partir"],
  },
  {
    id: "di-8",
    section: "dietas",
    question: "¿Qué son las calorías objetivo del plan?",
    answer: "Las calorías objetivo son el total de kilocalorías diarias que persigue el plan. Se definen al crear el plan y actúan como referencia: en el editor verás cuántas kcal acumulan los alimentos añadidos frente al objetivo marcado. Puedes cambiarlas en cualquier momento desde \"Editar plan\".",
    related: ["di-9", "di-10", "di-17"],
    keywords: ["calorías", "kcal", "objetivo", "total", "diarias"],
  },
  {
    id: "di-9",
    section: "dietas",
    question: "¿Qué son los macros objetivo?",
    answer: "Los macros objetivo son los gramos diarios de proteínas, carbohidratos y grasas que quieres que tenga el plan. Se expresan en gramos y sirven de guía al componer las comidas. Si no los defines, se calculan orientativamente a partir de las calorías objetivo con un reparto porcentual estándar.",
    related: ["di-8", "di-10", "di-17"],
    keywords: ["macros", "macronutrientes", "proteínas", "carbohidratos", "grasas"],
  },
  {
    id: "di-10",
    section: "dietas",
    question: "¿Cómo se calculan los macros a partir de las calorías?",
    answer: "Si solo indicas calorías, la aplicación propone un reparto orientativo (por defecto ~30% proteínas, ~40% carbohidratos y ~30% grasas). Usa los factores 4 kcal/g para proteínas y carbohidratos y 9 kcal/g para grasas. El cálculo es una sugerencia: puedes sobrescribir los gramos manualmente si tu enfoque clínico es distinto.",
    related: ["di-8", "di-9", "di-17"],
    keywords: ["cálculo", "macros", "porcentaje", "orientativo", "reparto"],
  },
  {
    id: "di-11",
    section: "dietas",
    question: "¿Qué significa que un plan sea \"Actual\"?",
    answer: "El plan marcado como \"Actual\" es el que se considera vigente para el paciente en ese momento. Es el que se muestra en el portal del paciente, el que se usa como referencia en el tab Plan de alimentación de su ficha y el que aparece destacado en el listado con el distintivo \"Actual\". Solo puede haber un plan Actual por paciente a la vez.",
    related: ["di-12", "di-13", "di-39"],
    keywords: ["actual", "vigente", "activo", "plan actual"],
  },
  {
    id: "di-12",
    section: "dietas",
    question: "¿Puede un paciente tener varios planes?",
    answer: "Sí. Un paciente puede tener todos los planes que quieras guardados en su histórico (fase de volumen, definición, mantenimiento, etapas de tratamiento, etc.), pero solo uno estará marcado como \"Actual\" en cada momento. Los demás quedan archivados como referencia y puedes volver a activarlos cuando lo necesites.",
    related: ["di-11", "di-13", "di-28"],
    keywords: ["varios", "múltiples", "planes", "paciente", "histórico"],
  },
  {
    id: "di-13",
    section: "dietas",
    question: "¿Cómo cambio cuál es el plan Actual?",
    answer: "Abre el plan que quieras marcar como vigente y pulsa el botón \"Marcar como Actual\", o usa la acción equivalente en la card del listado. El plan seleccionado pasa a ser el Actual y el anterior queda desmarcado automáticamente. El cambio se refleja al instante en el portal del paciente.",
    related: ["di-11", "di-12", "di-39"],
    keywords: ["cambiar", "actual", "vigente", "marcar"],
  },
  {
    id: "di-14",
    section: "dietas",
    question: "¿Cómo uso el filtro por paciente?",
    answer: "En la parte superior del listado hay un desplegable \"Paciente\". Selecciona uno para ver solo sus planes; selecciona \"Todos\" para volver a ver el conjunto. Es útil cuando quieres repasar el histórico de un paciente concreto o comparar planes sucesivos.",
    related: ["di-15", "di-16", "di-2"],
    keywords: ["filtro", "paciente", "filtrar", "select"],
  },
  {
    id: "di-15",
    section: "dietas",
    question: "¿Cómo filtro por estado del plan?",
    answer: "El filtro \"Estado\" tiene tres valores: \"Todos\" (muestra todos los planes), \"Activos\" (solo el plan Actual de cada paciente) e \"Inactivos\" (planes guardados que no son el Actual). Es la forma rápida de quedarte solo con los planes vigentes si gestionas muchos pacientes.",
    related: ["di-14", "di-16", "di-11"],
    keywords: ["filtro", "estado", "activos", "inactivos", "todos"],
  },
  {
    id: "di-16",
    section: "dietas",
    question: "¿Cómo funciona el buscador de planes?",
    answer: "El buscador de la parte superior busca por nombre del plan y por nombre del paciente asociado. Escribe cualquier fragmento (por ejemplo \"definición\" o \"García\") y el listado se filtra en tiempo real. Combina el buscador con los filtros de paciente y estado para acotar al máximo los resultados.",
    related: ["di-14", "di-15", "di-45"],
    keywords: ["buscador", "buscar", "search", "filtrar"],
  },
  {
    id: "di-17",
    section: "dietas",
    question: "¿Cómo edito un plan existente?",
    answer: "Pulsa el botón \"Editar\" en la card del plan o abre el plan y entra en el editor. La ruta es /dietas/[id]/editar. Desde allí puedes cambiar el nombre, las calorías y macros objetivo, añadir o quitar días y comidas, y ajustar los alimentos de cada comida. Los cambios se guardan automáticamente o con el botón Guardar, según la vista.",
    related: ["di-18", "di-19", "di-22"],
    keywords: ["editar", "modificar", "plan", "cambiar"],
  },
  {
    id: "di-18",
    section: "dietas",
    question: "¿Puedo duplicar un plan?",
    answer: "Sí. Desde la card del plan o desde el propio editor tienes la acción \"Duplicar\", que crea una copia del plan con el mismo contenido y un nombre sufijado con \"(copia)\". La copia queda asignada al mismo paciente por defecto, pero puedes reasignarla. Es la forma rápida de crear variantes sin perder el original.",
    related: ["di-17", "di-25", "di-31"],
    keywords: ["duplicar", "copiar", "clonar", "replicar"],
  },
  {
    id: "di-19",
    section: "dietas",
    question: "¿Cómo elimino un plan?",
    answer: "Pulsa el icono de papelera en la card o el botón \"Eliminar\" dentro del plan. Se abrirá un diálogo de confirmación. Al confirmar, el plan desaparece del listado y de la ficha del paciente. La acción es irreversible: si borras un plan por error, tendrás que volver a crearlo.",
    related: ["di-17", "di-18", "di-31"],
    keywords: ["eliminar", "borrar", "quitar", "plan", "irreversible"],
  },
  {
    id: "di-20",
    section: "dietas",
    question: "¿Cómo comparto un plan con el paciente?",
    answer: "Pulsa el botón \"Compartir\" en la card o dentro del plan. Se genera un enlace único que puedes copiar y enviar al paciente por mensaje, email o WhatsApp. Si el paciente tiene portal activo, el plan Actual aparece directamente allí sin necesidad de enlace. Desde la vista de compartir también puedes controlar la caducidad del enlace.",
    related: ["di-21", "di-39", "di-43"],
    keywords: ["compartir", "enlace", "link", "enviar", "paciente"],
  },
  {
    id: "di-21",
    section: "dietas",
    question: "¿Puedo imprimir o exportar el plan a PDF?",
    answer: "Sí. Dentro del plan tienes la acción \"Imprimir / Exportar PDF\", que genera una vista preparada para impresión con el resumen de calorías, macros y el detalle de días y comidas. Puedes imprimir directamente o guardar como PDF desde el diálogo del navegador para adjuntarlo en email o archivarlo en el histórico.",
    related: ["di-20", "di-3"],
    keywords: ["imprimir", "pdf", "exportar", "descargar"],
  },
  {
    id: "di-22",
    section: "dietas",
    question: "¿Qué buenas prácticas seguir al nombrar un plan?",
    answer: "Recomendamos incluir fase o enfoque, fecha o semana y, si aplica, kcal. Ejemplos válidos: \"Definición semana 3 (1800 kcal)\", \"Mantenimiento abril\", \"Volumen post-lesión\". Evita nombres genéricos como \"Plan 1\" cuando gestiones muchos planes: te será más fácil localizarlos en el buscador.",
    related: ["di-5", "di-37", "di-16"],
    keywords: ["nombrar", "buenas prácticas", "convención", "nombre"],
  },
  {
    id: "di-23",
    section: "dietas",
    question: "¿Dónde veo la fecha de creación y última modificación?",
    answer: "La fecha de creación aparece en la card del plan y en su cabecera dentro del editor. La fecha de última modificación se muestra en la cabecera del editor y en las vistas de detalle, así sabes cuándo lo tocaste por última vez. Ambas se actualizan automáticamente al guardar cambios.",
    related: ["di-3", "di-28", "di-45"],
    keywords: ["fecha", "creación", "modificación", "última", "actualización"],
  },
  {
    id: "di-24",
    section: "dietas",
    question: "¿Cuál es la diferencia entre un plan y una plantilla?",
    answer: "Un plan está siempre asignado a un paciente concreto y forma parte de su histórico. Una plantilla es un modelo reutilizable que no pertenece a ningún paciente y se usa como base para generar planes nuevos. Las plantillas se gestionan desde /dietas/plantillas y sirven para replicar esquemas que repites a menudo.",
    related: ["di-7", "di-25", "di-26"],
    keywords: ["plantilla", "diferencia", "modelo", "reutilizable"],
  },
  {
    id: "di-25",
    section: "dietas",
    question: "¿Cómo creo una plantilla a partir de un plan existente?",
    answer: "Abre el plan y pulsa \"Guardar como plantilla\". Se te pedirá un nombre y una descripción breve. La plantilla se guardará en /dietas/plantillas sin asignación a paciente y podrás usarla la próxima vez que crees un plan nuevo. El plan original no se modifica.",
    related: ["di-24", "di-7", "di-18"],
    keywords: ["plantilla", "guardar como", "crear plantilla", "template"],
  },
  {
    id: "di-26",
    section: "dietas",
    question: "¿Cómo se relaciona Dietas con el tab \"Plan de alimentación\" del paciente?",
    answer: "Dentro de la ficha del paciente, el tab \"Plan de alimentación\" muestra de forma directa su plan Actual. Es una vista embebida pensada para la consulta: los cambios que hagas allí se reflejan en /dietas, y viceversa. El listado general de /dietas es útil para comparar o gestionar planes entre pacientes.",
    related: ["di-11", "di-27", "di-39"],
    keywords: ["ficha paciente", "tab", "plan alimentación", "relación"],
  },
  {
    id: "di-27",
    section: "dietas",
    question: "¿Puedo ver el plan desde la ficha del paciente?",
    answer: "Sí. Entra en /pacientes/[id] y abre el tab \"Plan de alimentación\". Verás el plan Actual del paciente con sus días, comidas y alimentos. Desde allí puedes editarlo directamente, crear un plan nuevo para ese paciente o cambiar el Actual sin necesidad de pasar por el listado general de /dietas.",
    related: ["di-26", "di-11", "di-13"],
    keywords: ["ver plan", "ficha paciente", "tab", "acceder"],
  },
  {
    id: "di-28",
    section: "dietas",
    question: "¿Qué ocurre si un plan lleva mucho tiempo sin actualizarse?",
    answer: "Si el plan Actual de un paciente lleva más de 30 días sin modificarse, aparecerá un aviso de \"Plan antiguo\" en la card y en la ficha del paciente. Es solo un recordatorio para que lo revises o lo adaptes; el plan sigue siendo funcional. Puedes silenciar el aviso editándolo o marcando otro plan como Actual.",
    related: ["di-23", "di-11", "di-17"],
    keywords: ["antiguo", "sin actualizar", "aviso", "30 días"],
  },
  {
    id: "di-29",
    section: "dietas",
    question: "¿Puedo tener un plan sin asignar a ningún paciente?",
    answer: "Según tu suscripción, es posible guardar borradores sin asignar, que aparecen marcados como \"Sin paciente\" en el listado. Son útiles para preparar planes antes de conocer al paciente. En cuanto quieras usarlo, bastará con asignarle un paciente desde el propio plan. Si tu plan no permite borradores, tendrás que asignar paciente al crearlo.",
    related: ["di-30", "di-34", "di-6"],
    keywords: ["sin asignar", "borrador", "sin paciente", "no asignado"],
  },
  {
    id: "di-30",
    section: "dietas",
    question: "¿Cómo reasigno un plan a otro paciente?",
    answer: "Abre el plan y pulsa \"Editar\". En la cabecera encontrarás el campo \"Paciente\" con el nombre actual; cámbialo por el nuevo paciente y guarda. El plan se trasladará al histórico del nuevo paciente. Ten en cuenta que si ya era el Actual, perderá ese estado en el paciente anterior al reasignarlo.",
    related: ["di-29", "di-6", "di-17"],
    keywords: ["reasignar", "cambiar paciente", "mover", "transferir"],
  },
  {
    id: "di-31",
    section: "dietas",
    question: "¿Hay un número máximo de planes que puedo crear?",
    answer: "El número máximo depende de tu plan de suscripción. Los planes Free tienen un límite por paciente y un total acotado; los planes de pago amplían o eliminan esos límites. Cuando te acerques al límite recibirás un aviso y, al llegar a él, se desactivará el botón \"+ Nuevo plan\" hasta que elimines planes o mejores la suscripción.",
    related: ["di-19", "di-18", "di-12"],
    keywords: ["máximo", "límite", "suscripción", "cuota"],
  },
  {
    id: "di-32",
    section: "dietas",
    question: "¿Puedo generar un plan con IA desde aquí?",
    answer: "Sí. En el formulario de nuevo plan y en la card de cualquier plan existe el acceso rápido \"Generar con IA\", que te lleva al asistente de /dietas/ia. Allí indicas paciente, calorías, restricciones y preferencias y la IA propone un plan inicial que puedes revisar y editar antes de guardarlo como plan Actual.",
    related: ["di-4", "di-7", "di-17"],
    keywords: ["ia", "inteligencia artificial", "generar", "asistente"],
  },
  {
    id: "di-33",
    section: "dietas",
    question: "¿Qué ve el paciente en su portal respecto al plan?",
    answer: "En el portal del paciente solo se muestra el plan marcado como Actual. No ve el histórico completo ni los planes inactivos, para evitar confusión. Verá los días, comidas y alimentos con sus cantidades, junto con el resumen de calorías y macros objetivo. Los cambios que hagas como nutricionista aparecen al instante en su portal.",
    related: ["di-11", "di-20", "di-26"],
    keywords: ["portal paciente", "solo actual", "vista paciente", "qué ve"],
  },
  {
    id: "di-34",
    section: "dietas",
    question: "¿Hay límite de caracteres para el nombre del plan?",
    answer: "Sí. El nombre admite hasta 80 caracteres, suficiente para incluir fase, kcal y fecha si lo necesitas. Si superas ese límite, la aplicación cortará el exceso al guardar. Procura mantener los nombres cortos y descriptivos para que se lean bien en la card sin truncarse.",
    related: ["di-5", "di-22", "di-37"],
    keywords: ["límite", "caracteres", "longitud", "nombre"],
  },
  {
    id: "di-35",
    section: "dietas",
    question: "¿Existen colores o categorías para los planes?",
    answer: "Por defecto la card usa un color neutro, con un acento para el distintivo \"Actual\". No hay categorías de color configurables por el usuario; la diferenciación se hace por nombre, paciente y fecha. Si necesitas separar tipos de plan, usa convenciones en el nombre (por ejemplo prefijos como \"[Def]\" o \"[Vol]\").",
    related: ["di-22", "di-3", "di-11"],
    keywords: ["colores", "categorías", "etiquetas", "tipos"],
  },
  {
    id: "di-36",
    section: "dietas",
    question: "¿Cómo ordeno el listado de planes?",
    answer: "En la parte superior derecha del listado tienes un selector de orden. Puedes ordenar por fecha de creación (más recientes primero, por defecto), fecha de última modificación o nombre del paciente (A-Z). El orden se aplica al instante sobre el listado filtrado.",
    related: ["di-2", "di-23", "di-14"],
    keywords: ["ordenar", "orden", "fecha", "paciente", "clasificar"],
  },
  {
    id: "di-37",
    section: "dietas",
    question: "¿Puedo renombrar un plan después de crearlo?",
    answer: "Sí. Entra en el editor del plan y cambia el texto del campo \"Nombre\" en la cabecera. Al guardar, el nuevo nombre se actualiza en el listado, en la ficha del paciente y en el portal. Renombrar no afecta al contenido ni al estado Actual del plan.",
    related: ["di-5", "di-22", "di-17"],
    keywords: ["renombrar", "cambiar nombre", "modificar título"],
  },
  {
    id: "di-38",
    section: "dietas",
    question: "¿Qué pasa si elimino el plan marcado como Actual?",
    answer: "Al eliminar el plan Actual, el paciente se queda sin plan vigente y su tab \"Plan de alimentación\" aparecerá vacío hasta que marques otro como Actual o crees uno nuevo. El portal del paciente mostrará un mensaje indicando que aún no hay plan asignado. Por eso conviene tener otro listo antes de borrar el vigente.",
    related: ["di-19", "di-11", "di-13"],
    keywords: ["eliminar actual", "borrar vigente", "consecuencias"],
  },
  {
    id: "di-39",
    section: "dietas",
    question: "¿Qué cambia para el paciente al marcar otro plan como Actual?",
    answer: "Al cambiar el plan Actual, el portal del paciente actualiza la vista de forma inmediata con el nuevo plan. El paciente verá el nuevo nombre, las nuevas calorías y macros objetivo y el detalle de días y comidas. El plan anterior queda en tu listado como inactivo, pero el paciente deja de tener acceso directo a él.",
    related: ["di-13", "di-11", "di-33"],
    keywords: ["cambio actual", "paciente", "portal", "efecto"],
  },
  {
    id: "di-40",
    section: "dietas",
    question: "¿Puedo ver un histórico completo de planes de un paciente?",
    answer: "Sí. Usa el filtro por paciente en /dietas para ver todos sus planes ordenados por fecha. Alternativamente, desde la ficha del paciente puedes acceder al histórico de planes anteriores. Es útil para revisar la evolución del enfoque nutricional y para recuperar planes que volviste a necesitar.",
    related: ["di-14", "di-27", "di-12"],
    keywords: ["histórico", "planes anteriores", "historial", "evolución"],
  },
  {
    id: "di-41",
    section: "dietas",
    question: "¿Cómo sé cuántos días y comidas tiene un plan?",
    answer: "Cada card muestra el recuento de días y de comidas por día. Un plan típico suele tener 7 días y 4-5 comidas (desayuno, media mañana, comida, merienda y cena), pero puedes configurarlo con los días y comidas que quieras desde el editor. El recuento se actualiza automáticamente al añadir o quitar.",
    related: ["di-3", "di-17"],
    keywords: ["días", "comidas", "número", "recuento"],
  },
  {
    id: "di-42",
    section: "dietas",
    question: "¿Qué pasa si un paciente pasa a Inactivo?",
    answer: "Los planes del paciente se conservan, pero dejan de aparecer por defecto en el filtro \"Activos\" del listado. Puedes verlos cambiando el filtro de estado o buscando al paciente por nombre. Si reactivas al paciente, los planes vuelven a estar accesibles como antes sin necesidad de recrearlos.",
    related: ["di-15", "di-14", "di-11"],
    keywords: ["paciente inactivo", "archivado", "baja", "estado"],
  },
  {
    id: "di-43",
    section: "dietas",
    question: "¿Los enlaces de compartir caducan?",
    answer: "Sí. Los enlaces de compartir generados desde el botón \"Compartir\" tienen caducidad configurable (por ejemplo 7, 30 días o permanente). Si caduca, el paciente verá un mensaje de enlace expirado y tendrás que generar uno nuevo. El portal del paciente no depende de estos enlaces: siempre muestra el plan Actual.",
    related: ["di-20", "di-33"],
    keywords: ["enlace", "caducidad", "compartir", "expirar"],
  },
  {
    id: "di-44",
    section: "dietas",
    question: "¿Puedo comparar dos planes del mismo paciente?",
    answer: "No hay una vista de comparación directa lado a lado, pero puedes abrir cada plan en una pestaña distinta del navegador y contrastarlos. En el listado, al filtrar por paciente, verás calorías y macros objetivo de cada plan en las cards, lo que facilita la comparación rápida entre fases.",
    related: ["di-40", "di-14", "di-3"],
    keywords: ["comparar", "planes", "diferencias", "cotejar"],
  },
  {
    id: "di-45",
    section: "dietas",
    question: "¿Por qué no encuentro un plan en el listado?",
    answer: "Suele ser por un filtro activo: revisa que el filtro de estado no esté en \"Inactivos\" cuando buscas el Actual, o que el filtro de paciente esté en \"Todos\". Comprueba también el buscador: si tiene texto, solo verás los planes que coinciden. Si aun así no aparece, puede estar eliminado o asignado a otro paciente; usa el buscador por nombre del plan.",
    related: ["di-14", "di-15", "di-16"],
    keywords: ["no encuentro", "no aparece", "buscar", "problema"],
  },
];
