import type { HelpEntrySkeleton } from "../types";

export const DIETA_PLANTILLAS_ENTRIES: HelpEntrySkeleton[] = [
  { id: "dpl-1", section: "dieta-plantillas", related: ["dpl-2", "dpl-3", "dpl-5"] },
  { id: "dpl-2", section: "dieta-plantillas", related: ["dpl-1", "dpl-27", "dpl-5"] },
  { id: "dpl-3", section: "dieta-plantillas", related: ["dpl-4", "dpl-1", "dpl-13"] },
  { id: "dpl-4", section: "dieta-plantillas", related: ["dpl-3", "dpl-18", "dpl-2"] },
  { id: "dpl-5", section: "dieta-plantillas", related: ["dpl-1", "dpl-21", "dpl-3"] },
  { id: "dpl-6", section: "dieta-plantillas", related: ["dpl-3", "dpl-20", "dpl-7"] },
  { id: "dpl-7", section: "dieta-plantillas", related: ["dpl-6", "dpl-3", "dpl-5"] },
  { id: "dpl-8", section: "dieta-plantillas", related: ["dpl-27", "dpl-6", "dpl-12"] },
  { id: "dpl-9", section: "dieta-plantillas", related: ["dpl-26", "dpl-13", "dpl-1"] },
  { id: "dpl-10", section: "dieta-plantillas", related: ["dpl-13", "dpl-23", "dpl-24"] },
  { id: "dpl-11", section: "dieta-plantillas", related: ["dpl-28", "dpl-29", "dpl-30"] },
  { id: "dpl-12", section: "dieta-plantillas", related: ["dpl-8", "dpl-26", "dpl-13"] },
  { id: "dpl-13", section: "dieta-plantillas", related: ["dpl-10", "dpl-14", "dpl-23"] },
  { id: "dpl-14", section: "dieta-plantillas", related: ["dpl-13", "dpl-10", "dpl-1"] },
  { id: "dpl-15", section: "dieta-plantillas", related: ["dpl-3", "dpl-17", "dpl-1"] },
  { id: "dpl-16", section: "dieta-plantillas", related: ["dpl-1", "dpl-21", "dpl-23"] },
  { id: "dpl-17", section: "dieta-plantillas", related: ["dpl-18", "dpl-5", "dpl-1"] },
  { id: "dpl-18", section: "dieta-plantillas", related: ["dpl-17", "dpl-5", "dpl-4"] },
  { id: "dpl-19", section: "dieta-plantillas", related: ["dpl-20", "dpl-5", "dpl-1"] },
  { id: "dpl-20", section: "dieta-plantillas", related: ["dpl-6", "dpl-8", "dpl-27"] },
  { id: "dpl-21", section: "dieta-plantillas", related: ["dpl-5", "dpl-26", "dpl-27"] },
  { id: "dpl-22", section: "dieta-plantillas", related: ["dpl-10", "dpl-26", "dpl-13"] },
  { id: "dpl-23", section: "dieta-plantillas", related: ["dpl-10", "dpl-13", "dpl-24"] },
  { id: "dpl-24", section: "dieta-plantillas", related: ["dpl-23", "dpl-10", "dpl-13"] },
  { id: "dpl-25", section: "dieta-plantillas", related: ["dpl-9", "dpl-13", "dpl-10"] },
  { id: "dpl-26", section: "dieta-plantillas", related: ["dpl-20", "dpl-8", "dpl-12"] },
  { id: "dpl-27", section: "dieta-plantillas", related: ["dpl-2", "dpl-20", "dpl-8"] },
  { id: "dpl-28", section: "dieta-plantillas", related: ["dpl-11", "dpl-1", "dpl-29"] },
  { id: "dpl-29", section: "dieta-plantillas", related: ["dpl-11", "dpl-30", "dpl-28"] },
  { id: "dpl-30", section: "dieta-plantillas", related: ["dpl-29", "dpl-11", "dpl-4"] },
];
