import type { HelpEntrySkeleton } from "../types";

export const GENERAL_ENTRIES: HelpEntrySkeleton[] = [
  { id: "gen-1", section: "general", related: ["gen-2", "gen-11", "gen-45"] },
  { id: "gen-2", section: "general", related: ["gen-1", "gen-7", "gen-47"] },
  { id: "gen-3", section: "general", related: ["gen-4", "gen-15", "gen-29"] },
  { id: "gen-4", section: "general", related: ["gen-3", "gen-15"] },
  { id: "gen-5", section: "general", related: ["gen-6", "gen-22"] },
  { id: "gen-6", section: "general", related: ["gen-5"] },
  { id: "gen-7", section: "general", related: ["gen-8", "gen-29"] },
  { id: "gen-8", section: "general", related: ["gen-7"] },
  { id: "gen-9", section: "general", related: ["gen-10"] },
  { id: "gen-10", section: "general", related: ["gen-9", "gen-24"] },
  { id: "gen-11", section: "general", related: ["gen-12", "gen-13"] },
  { id: "gen-12", section: "general", related: ["gen-11", "gen-13"] },
  { id: "gen-13", section: "general", related: ["gen-11", "gen-12"] },
  { id: "gen-14", section: "general", related: ["gen-24", "gen-46"] },
  { id: "gen-15", section: "general", related: ["gen-3", "gen-4"] },
  { id: "gen-16", section: "general", related: ["gen-2", "gen-47"] },
  { id: "gen-17", section: "general", related: ["gen-18", "gen-31"] },
  { id: "gen-18", section: "general", related: ["gen-17"] },
  { id: "gen-19", section: "general", related: ["gen-20", "gen-21"] },
  { id: "gen-20", section: "general", related: ["gen-19", "gen-21"] },
  { id: "gen-21", section: "general", related: ["gen-19", "gen-20"] },
  { id: "gen-22", section: "general", related: ["gen-23"] },
  { id: "gen-23", section: "general", related: ["gen-22", "gen-44"] },
  { id: "gen-24", section: "general", related: ["gen-33"] },
  { id: "gen-25", section: "general", related: ["gen-26", "gen-44"] },
  { id: "gen-26", section: "general", related: ["gen-25"] },
  { id: "gen-27", section: "general", related: ["gen-28", "gen-43"] },
  { id: "gen-28", section: "general", related: ["gen-27"] },
  { id: "gen-29", section: "general", related: ["gen-30"] },
  { id: "gen-30", section: "general", related: ["gen-29"] },
  { id: "gen-31", section: "general", related: ["gen-17", "gen-18"] },
  { id: "gen-32", section: "general", related: ["gen-2", "gen-47"] },
  { id: "gen-33", section: "general", related: ["gen-1"] },
  { id: "gen-34", section: "general", related: ["gen-17", "gen-31"] },
  { id: "gen-35", section: "general", related: ["gen-28", "gen-36"] },
  { id: "gen-36", section: "general", related: ["gen-14", "gen-35"] },
  { id: "gen-37", section: "general", related: ["gen-24"] },
  { id: "gen-38", section: "general", related: ["gen-24", "gen-26"] },
  { id: "gen-39", section: "general", related: ["gen-15", "gen-40"] },
  { id: "gen-40", section: "general", related: ["gen-39", "gen-23"] },
  { id: "gen-41", section: "general", related: ["gen-11", "gen-42"] },
  { id: "gen-42", section: "general", related: ["gen-41", "gen-43"] },
  { id: "gen-43", section: "general", related: ["gen-6", "gen-42"] },
  { id: "gen-44", section: "general", related: ["gen-23", "gen-25"] },
  { id: "gen-45", section: "general", related: ["gen-1", "gen-42"] },
  { id: "gen-46", section: "general", related: ["gen-14"] },
  { id: "gen-47", section: "general", related: ["gen-2", "gen-16"] },
  { id: "gen-48", section: "general", related: ["gen-37"] },
  { id: "gen-49", section: "general", related: ["gen-23", "gen-44"] },
  { id: "gen-50", section: "general", related: ["gen-16", "gen-25", "gen-44"] },
];
