import type { HelpEntry } from "../types";

export const GENERAL_ENTRIES: HelpEntry[] = [
  {
    id: "gen-1",
    section: "general",
    question: "¿Qué es Annonia y para quién está pensada?",
    answer: "Annonia es una aplicación web profesional diseñada específicamente para dietistas-nutricionistas que quieren digitalizar toda su consulta. Integra gestión de pacientes, diseño de dietas con ayuda de inteligencia artificial, agenda con videollamadas, mensajería, recetas, cobros online y un portal para el paciente. Está pensada tanto para profesionales autónomos como para clínicas pequeñas que buscan centralizar su trabajo en una sola herramienta. No es apta para uso directo del paciente sin un nutricionista asociado.",
    related: ["gen-2", "gen-11", "gen-45"],
    keywords: ["app", "aplicación", "nutricionista", "dietista", "qué es", "para quién"],
  },
  {
    id: "gen-2",
    section: "general",
    question: "¿Cómo empiezo a usar la app por primera vez?",
    answer: "Tras registrarte con tu correo o con Google, lo primero es completar tu perfil profesional en Ajustes (nombre, foto, número de colegiado si procede). Después te recomendamos activar el paciente demo desde Ajustes para explorar todas las funciones sin tocar datos reales. Una vez familiarizado, crea tu primer paciente desde la sección Pacientes y prueba a generarle una dieta con la IA. El tour interactivo del dashboard te guiará por los pasos iniciales de forma automática.",
    related: ["gen-1", "gen-7", "gen-47"],
    keywords: ["empezar", "inicio", "primeros pasos", "setup", "configurar"],
  },
  {
    id: "gen-3",
    section: "general",
    question: "¿Cómo está organizada la navegación del sidebar?",
    answer: "El sidebar lateral está agrupado en cuatro bloques lógicos: Gestión (Dashboard, Pacientes, Recetas), Dietas (editor y plantillas), Acompañamiento (Agenda, Mensajes) y Centro de control (Reportes, Pagos, Ajustes). Cada bloque agrupa funciones relacionadas para que encuentres todo por contexto y no por orden alfabético. En móvil el sidebar se colapsa en un menú hamburguesa que despliega los mismos grupos. Puedes minimizarlo en escritorio para ganar espacio de trabajo.",
    related: ["gen-4", "gen-15", "gen-29"],
    keywords: ["sidebar", "menú", "navegación", "secciones", "estructura"],
  },
  {
    id: "gen-4",
    section: "general",
    question: "¿Qué encuentro exactamente en cada bloque del sidebar?",
    answer: "En Gestión tienes el Dashboard con resumen diario, la lista de Pacientes y tu biblioteca de Recetas. En Dietas están las plantillas reutilizables y el acceso al editor cuando abres una dieta concreta. Acompañamiento reúne Agenda (con Google Calendar) y Mensajes para comunicación con pacientes. Centro de control concentra Reportes, Pagos (Stripe Connect) y Ajustes con todas las configuraciones transversales. Esta agrupación evita que tengas que buscar funciones entre decenas de enlaces sueltos.",
    related: ["gen-3", "gen-15"],
    keywords: ["gestión", "dietas", "acompañamiento", "centro de control", "bloques"],
  },
  {
    id: "gen-5",
    section: "general",
    question: "¿Cómo cambio entre tema claro y oscuro?",
    answer: "Hay un botón de alternancia con el icono de sol/luna en la parte inferior del sidebar del panel profesional. Un clic cambia instantáneamente todo el interfaz entre claro y oscuro, y la preferencia queda guardada en tu perfil. En el portal del paciente existe el mismo toggle, también en el sidebar, y es independiente del tema del profesional. Por defecto la app respeta el tema del sistema operativo la primera vez que entras, pero una vez elegido manualmente se mantiene fijo.",
    related: ["gen-6", "gen-22"],
    keywords: ["tema", "oscuro", "claro", "dark mode", "light mode", "toggle"],
  },
  {
    id: "gen-6",
    section: "general",
    question: "¿El tema oscuro afecta a los PDF o emails que envío?",
    answer: "No, el tema oscuro es solo visual dentro de la aplicación. Los PDF generados (dietas, informes, recomendaciones) siempre salen con fondo blanco y tinta oscura para que sean legibles al imprimir. Los emails transaccionales también usan una plantilla clara por defecto. Si tu paciente usa el portal en modo oscuro, lo que ve en pantalla sí se adapta, pero cualquier documento descargable mantiene el formato imprimible estándar.",
    related: ["gen-5"],
    keywords: ["tema", "pdf", "email", "impresión", "documentos"],
  },
  {
    id: "gen-7",
    section: "general",
    question: "¿Funciona bien la app en móvil?",
    answer: "Sí, toda la aplicación es completamente responsive y se adapta a pantallas de móvil, tablet y escritorio. En móvil el sidebar se convierte en un menú hamburguesa, las tablas se reorganizan como tarjetas apilables y los formularios usan inputs adaptados. El portal del paciente está especialmente optimizado para móvil porque es el dispositivo más habitual de consumo. No existe app nativa; se abre desde el navegador y puedes añadirla como icono en tu pantalla de inicio para acceder más rápido.",
    related: ["gen-8", "gen-29"],
    keywords: ["móvil", "responsive", "tablet", "smartphone", "pantalla"],
  },
  {
    id: "gen-8",
    section: "general",
    question: "¿Puedo instalar Annonia como app en el móvil?",
    answer: "Aunque no hay una app nativa en App Store o Google Play, puedes añadir la web a la pantalla de inicio desde el navegador: en Safari usa Compartir y luego Añadir a pantalla de inicio; en Chrome Android toca los tres puntos y Añadir a pantalla principal. A partir de ahí se abre en modo a pantalla completa como una app. Así accedes sin teclear la URL y con un icono propio. No tendrás notificaciones push nativas todavía, pero el resto de funciones se comporta igual.",
    related: ["gen-7"],
    keywords: ["instalar", "pwa", "móvil", "icono", "pantalla inicio"],
  },
  {
    id: "gen-9",
    section: "general",
    question: "¿Cómo cierro sesión o cambio de cuenta?",
    answer: "El botón para cerrar sesión está al final del sidebar, debajo del menú de tu perfil (haz clic en tu avatar o nombre). Al cerrar sesión se invalida tu cookie y vuelves a la pantalla de login. Para entrar con otra cuenta, simplemente inicia sesión con las nuevas credenciales o con otra cuenta Google. No existe un interruptor rápido para alternar entre varias cuentas, así que tendrás que cerrar una antes de abrir la otra.",
    related: ["gen-10"],
    keywords: ["cerrar sesión", "logout", "cuenta", "salir"],
  },
  {
    id: "gen-10",
    section: "general",
    question: "¿Me desconecta la app sola si no la uso?",
    answer: "Por seguridad, la sesión caduca pasado un periodo de inactividad prolongado y tendrás que volver a iniciar sesión. Mientras estés usando la app activamente, la sesión se renueva de forma transparente. Si notas desconexiones muy frecuentes, revisa que tu navegador no esté bloqueando cookies de terceros o borrando datos al cerrar. En dispositivos compartidos te recomendamos cerrar sesión manualmente al terminar.",
    related: ["gen-9", "gen-24"],
    keywords: ["sesión", "caducar", "inactividad", "desconexión"],
  },
  {
    id: "gen-11",
    section: "general",
    question: "¿Qué diferencia hay entre la vista del nutricionista y la del paciente?",
    answer: "El nutricionista usa el panel profesional con todas las herramientas de trabajo: crear dietas, gestionar pacientes, cobrar, agendar, etc. El paciente accede a un portal separado y más sencillo, donde solo ve lo que tú le compartes: su plan de alimentación, citas, mensajes, seguimiento diario y entregables. Son dos interfaces distintas con el mismo backend. Un paciente nunca puede ver datos de otros pacientes ni tu panel profesional.",
    related: ["gen-12", "gen-13"],
    keywords: ["nutricionista", "paciente", "portal", "diferencias", "vistas"],
  },
  {
    id: "gen-12",
    section: "general",
    question: "¿Cómo accede mi paciente a su portal?",
    answer: "Cuando creas un paciente y le activas el acceso al portal desde su ficha, recibe un email con un enlace de invitación para crear su contraseña. Después entra siempre por la misma URL de login con su email y su clave. También puedes generarle un enlace manual de acceso si prefieres compartírselo por WhatsApp. El paciente ve un sidebar reducido con Dashboard, Plan, Citas, Mensajes, Seguimiento y su Perfil.",
    related: ["gen-11", "gen-13"],
    keywords: ["portal", "paciente", "acceso", "invitación", "login"],
  },
  {
    id: "gen-13",
    section: "general",
    question: "¿Puedo ver lo que ve mi paciente en su portal?",
    answer: "Sí, desde la ficha del paciente hay una opción para previsualizar su portal o para suplantarle temporalmente y ver exactamente lo que él ve. Es útil cuando quieres comprobar que una dieta se muestra correctamente o que los entregables están visibles. También puedes configurar qué secciones están activas para cada paciente desde su panel de configuración del portal. Así adaptas la experiencia a quien solo necesita lo básico frente a quien quiere todas las herramientas.",
    related: ["gen-11", "gen-12"],
    keywords: ["previsualizar", "portal", "ver como paciente", "suplantar"],
  },
  {
    id: "gen-14",
    section: "general",
    question: "¿Qué planes de suscripción existen?",
    answer: "Hay dos planes: Básico a 9.99 euros al mes y Profesional a 11.99 euros al mes. Todos los nuevos usuarios disfrutan de 14 días gratis para probar la aplicación sin compromiso y sin tarjeta en algunos casos. El plan Profesional incluye funciones avanzadas como exportación ilimitada, integración Stripe Connect completa y prioridad en la IA. Puedes cambiar entre planes o cancelar en cualquier momento desde Ajustes → Suscripción. La facturación se gestiona con Stripe y recibes factura automáticamente.",
    related: ["gen-24", "gen-46"],
    keywords: ["planes", "precio", "suscripción", "básico", "profesional", "14 días"],
  },
  {
    id: "gen-15",
    section: "general",
    question: "¿Dónde encuentro cada función principal? Mapa rápido",
    answer: "Pacientes está en el sidebar bajo Gestión; para crear una dieta entra en un paciente concreto o en la sección Dietas. La Agenda y los Mensajes están bajo Acompañamiento. Los Cobros y Ajustes están bajo Centro de control. Las Recetas tienen sección propia en Gestión. El Dashboard es la página de inicio y concentra accesos rápidos a lo más usado. Si no encuentras algo, revisa siempre primero dentro de la ficha del paciente, porque muchas funciones viven allí.",
    related: ["gen-3", "gen-4"],
    keywords: ["dónde está", "mapa", "funciones", "encontrar", "ubicación"],
  },
  {
    id: "gen-16",
    section: "general",
    question: "¿Qué son los tours interactivos y dónde los activo?",
    answer: "Los tours son guías paso a paso que resaltan elementos de la interfaz y explican cómo usar cada sección. Se lanzan automáticamente la primera vez que entras en zonas clave, pero puedes volver a iniciarlos cuando quieras desde Ajustes → Guías. Cada tour cubre una funcionalidad: dashboard, crear paciente, generar dieta con IA, agenda, etc. Son especialmente útiles cuando vuelves después de mucho tiempo o quieres formar a un colaborador en la app.",
    related: ["gen-2", "gen-47"],
    keywords: ["tour", "guía", "onboarding", "tutorial", "ayuda interactiva"],
  },
  {
    id: "gen-17",
    section: "general",
    question: "¿Dónde veo las notificaciones y qué significan los badges rojos?",
    answer: "En la parte superior derecha hay un icono de campana que abre el panel de notificaciones. Un badge rojo sobre la campana indica cuántas notificaciones tienes sin leer. También aparecen badges rojos junto a Mensajes en el sidebar cuando hay conversaciones con mensajes sin leer. Al hacer clic en una notificación te lleva directamente al contexto (paciente, cita o mensaje). Puedes marcar todas como leídas con un botón en el propio panel.",
    related: ["gen-18", "gen-31"],
    keywords: ["notificaciones", "campana", "badge", "sin leer", "alertas"],
  },
  {
    id: "gen-18",
    section: "general",
    question: "¿Puedo controlar qué notificaciones recibo?",
    answer: "Sí, en Ajustes → Perfil tienes un apartado de Notificaciones con preferencias granulares. Puedes activar o desactivar por separado: mensajes nuevos, recordatorios de citas, cambios en planes, pagos recibidos, feedback de pacientes, etc. También eliges si las quieres ver solo dentro de la app o también por email. La configuración se guarda al instante. Te recomendamos dejar activos al menos mensajes y citas para no perder nada importante.",
    related: ["gen-17"],
    keywords: ["preferencias", "notificaciones", "email", "configurar", "granular"],
  },
  {
    id: "gen-19",
    section: "general",
    question: "¿Qué nivel de seguridad y privacidad tiene la app?",
    answer: "Los datos se cifran en tránsito con HTTPS y en reposo en la base de datos. Las contraseñas se almacenan con hash seguro, nunca en texto plano. Cada usuario solo puede acceder a sus propios pacientes y datos; el aislamiento es estricto a nivel de backend. Las cookies de sesión usan el flag secure en producción y HttpOnly para evitar acceso desde JavaScript. No vendemos ni cedemos datos a terceros, y cumplimos con el RGPD europeo para ejercer derechos de acceso y supresión.",
    related: ["gen-20", "gen-21"],
    keywords: ["seguridad", "privacidad", "cifrado", "rgpd", "datos"],
  },
  {
    id: "gen-20",
    section: "general",
    question: "¿Dónde se guardan los datos de mis pacientes?",
    answer: "Todos los datos se alojan en servidores dentro del Espacio Económico Europeo para cumplir con el RGPD. La base de datos es gestionada y con copias de seguridad automáticas periódicas. Tú sigues siendo el responsable del tratamiento frente a tus pacientes, y Annonia actúa como encargado del tratamiento. Si algún paciente te solicita ejercer sus derechos (acceso, rectificación, supresión), puedes gestionarlo desde su ficha o contactando con soporte si necesitas ayuda.",
    related: ["gen-19", "gen-21"],
    keywords: ["datos", "servidores", "europa", "backup", "rgpd"],
  },
  {
    id: "gen-21",
    section: "general",
    question: "¿Puedo exportar o borrar todos mis datos?",
    answer: "Sí, desde Ajustes → Zona peligrosa puedes exportar un volcado de tus datos y pacientes, o solicitar la eliminación completa de la cuenta. La exportación genera un fichero descargable con tus pacientes, dietas y citas en formato estructurado. La eliminación es definitiva e irreversible, así que asegúrate de haber exportado antes. Para cumplir con el RGPD de un paciente individual, puedes eliminarlo o exportar solo sus datos desde su ficha, sin afectar al resto.",
    related: ["gen-19", "gen-20"],
    keywords: ["exportar", "borrar", "eliminar", "datos", "zona peligrosa"],
  },
  {
    id: "gen-22",
    section: "general",
    question: "¿En qué idioma está la app? ¿Hay versión en inglés?",
    answer: "La aplicación está íntegramente en castellano, tanto la interfaz como la ayuda, las plantillas de email y los documentos generados. De momento no hay versión en inglés ni en otros idiomas, pero está en el roadmap a medio plazo. Si necesitas enviar un plan a un paciente en otro idioma, puedes editar manualmente los textos del plan o usar una plantilla traducida por ti. El portal del paciente también está en castellano.",
    related: ["gen-23"],
    keywords: ["idioma", "inglés", "castellano", "traducción", "multilingüe"],
  },
  {
    id: "gen-23",
    section: "general",
    question: "¿Puedo pedir que se añadan nuevos idiomas o funciones?",
    answer: "Sí, tus sugerencias son bienvenidas y se tienen en cuenta al priorizar el roadmap. Puedes enviar ideas por el canal de soporte o por email. Indica con el mayor detalle posible el caso de uso y por qué lo necesitas, así es más fácil valorar impacto. Las funciones más pedidas suelen entrar antes. Los idiomas dependen de volumen de usuarios interesados, así que cuanta más demanda se manifieste, antes se abordará.",
    related: ["gen-22", "gen-44"],
    keywords: ["sugerencias", "feedback", "roadmap", "peticiones", "mejoras"],
  },
  {
    id: "gen-24",
    section: "general",
    question: "¿Cómo actualizo la aplicación a la última versión?",
    answer: "No tienes que actualizar nada manualmente. La app es una web construida con Next.js, así que cada vez que la recargas se sirve la última versión automáticamente. Si ves algo raro después de un cambio grande, prueba a forzar una recarga con Ctrl+F5 o Cmd+Shift+R para saltarte la caché del navegador. En móvil basta con cerrar la pestaña y volver a abrirla. No existen instaladores ni parches que tengas que aplicar tú.",
    related: ["gen-33"],
    keywords: ["actualizar", "versión", "update", "recargar", "nueva"],
  },
  {
    id: "gen-25",
    section: "general",
    question: "¿Cómo contacto con el soporte técnico?",
    answer: "El soporte técnico se gestiona por email y desde el propio Ajustes → Guías hay una sección de ayuda con enlaces de contacto. Al escribir, incluye siempre: qué estabas haciendo, qué esperabas, qué ha pasado y captura de pantalla si puedes. Si el problema es urgente (no puedes entrar, fallo de cobro), márcalo en el asunto. El tiempo de respuesta habitual es de menos de 24 horas en días laborables. Antes de escribir, prueba a revisar esta ayuda por si ya está resuelto.",
    related: ["gen-26", "gen-44"],
    keywords: ["soporte", "contacto", "email", "ayuda", "técnico"],
  },
  {
    id: "gen-26",
    section: "general",
    question: "¿Qué información debo dar al soporte cuando algo falla?",
    answer: "Incluye siempre tu email de cuenta, el navegador y sistema operativo que usas, la URL exacta donde ocurre el problema, los pasos para reproducirlo y cualquier mensaje de error visible. Si puedes, adjunta captura o vídeo. Indica también la hora aproximada del fallo para que podamos cruzarlo con los logs del servidor. Cuanta más información, más rápido se resuelve. Evita enviar contraseñas o datos sensibles de pacientes en el email.",
    related: ["gen-25"],
    keywords: ["bug", "error", "reportar", "información", "diagnóstico"],
  },
  {
    id: "gen-27",
    section: "general",
    question: "¿Dónde veo el estado de las integraciones externas?",
    answer: "En Ajustes → Integraciones tienes un panel con el estado de cada conexión: Google Calendar, Google Meet, Stripe Connect, Groq (IA), etc. Cada tarjeta muestra si está conectada, desconectada o con error. Desde ahí reconectas con un clic si se ha caducado el token. También puedes ver la última sincronización de la agenda o el último pago procesado. Es el primer sitio que revisar si algo externo no va como esperas.",
    related: ["gen-28", "gen-43"],
    keywords: ["integraciones", "estado", "google", "stripe", "conexión"],
  },
  {
    id: "gen-28",
    section: "general",
    question: "¿Qué integraciones externas usa Annonia?",
    answer: "Las principales son: Google Calendar y Google Meet para agenda y videoconsultas; Stripe y Stripe Connect para cobros y pagos online; Groq como motor de inteligencia artificial para generar dietas; y SendGrid o similar para emails transaccionales. Cada integración es opcional excepto la base de datos y el correo: puedes usar la app sin Google, sin Stripe y sin IA si no las necesitas. El panel de integraciones te indica cuáles están activas en tu cuenta.",
    related: ["gen-27"],
    keywords: ["integraciones", "google", "stripe", "groq", "ia", "externas"],
  },
  {
    id: "gen-29",
    section: "general",
    question: "¿Hay un buscador global para encontrar cualquier cosa?",
    answer: "De momento no existe un buscador universal que abarque pacientes, dietas, recetas y citas a la vez. Cada sección tiene su propio buscador: en Pacientes filtras por nombre o email, en Recetas por nombre o tag, en Dietas por nombre. Es una función que está en la lista de mejoras futuras. Mientras tanto, usa el buscador de cada listado o los atajos del navegador (Ctrl+F en la página actual) para encontrar texto concreto en pantalla.",
    related: ["gen-30"],
    keywords: ["buscador", "global", "búsqueda", "encontrar", "search"],
  },
  {
    id: "gen-30",
    section: "general",
    question: "¿Existen atajos de teclado?",
    answer: "Actualmente la app no tiene atajos de teclado propios configurados. Puedes usar los atajos estándar del navegador: Ctrl+F para buscar en la página, Ctrl+K no está enlazado aún, Esc cierra modales abiertos. En el editor de dietas sí hay algunos atajos implícitos (tabular, enter para añadir comida). Tenemos pendiente añadir un set de atajos globales para navegar entre secciones rápido; si es algo que usarías mucho, házlo saber al soporte para priorizarlo.",
    related: ["gen-29"],
    keywords: ["atajos", "teclado", "shortcuts", "keyboard", "hotkeys"],
  },
  {
    id: "gen-31",
    section: "general",
    question: "¿Qué tipo de notificaciones envía la app por email?",
    answer: "Por email se envían: recordatorios de cita 24 horas antes (a ti y al paciente), confirmación de pagos recibidos, resumen semanal opcional, invitaciones al portal del paciente, recuperación de contraseña y avisos de facturación de la suscripción. Cada tipo se puede activar o desactivar desde las preferencias de notificaciones de tu perfil. Los mensajes del chat dentro de la app no se envían por email, solo aparecen como badge en el sidebar.",
    related: ["gen-17", "gen-18"],
    keywords: ["email", "notificaciones", "recordatorios", "avisos"],
  },
  {
    id: "gen-32",
    section: "general",
    question: "¿Qué es el paciente demo y cómo lo uso?",
    answer: "El paciente demo es un paciente ficticio con datos realistas que puedes activar desde Ajustes → Demo. Sirve para probar funciones como crear dietas, citas o mensajes sin tocar pacientes reales. Se marca visualmente como demo en la lista para que no lo confundas. Puedes activarlo y desactivarlo las veces que quieras; al desactivarlo se borra todo lo generado sobre él. Es la forma más segura de explorar la app, especialmente durante los 14 días de prueba gratuita.",
    related: ["gen-2", "gen-47"],
    keywords: ["paciente demo", "prueba", "ficticio", "explorar", "test"],
  },
  {
    id: "gen-33",
    section: "general",
    question: "¿Qué es Annonia? ¿Es la marca de la app?",
    answer: "Annonia es el nombre de la marca comercial bajo la que se ofrece Annonia. Puedes ver el logo o el nombre en documentos públicos, emails transaccionales o la web corporativa. A efectos prácticos y de uso, la aplicación se llama Annonia dentro del panel, y Annonia es la entidad detrás. No es una herramienta distinta ni un producto separado. Si ves referencias a Annonia en facturas o correos, es la misma empresa.",
    related: ["gen-1"],
    keywords: ["annonia", "marca", "nombre", "empresa", "logo"],
  },
  {
    id: "gen-34",
    section: "general",
    question: "¿Qué es una contrapropuesta en la app?",
    answer: "Una contrapropuesta es la respuesta que un paciente envía cuando no acepta un plan de alimentación o una cita tal cual se la propones. Desde su portal puede sugerir cambios (otro horario, otra comida) y tú los ves reflejados en mensajes o en la propia cita/plan para aceptar o rechazar. Es un flujo para negociar sin tener que escribir mensajes largos. La contrapropuesta llega con notificación y queda registrada para que haya trazabilidad de lo acordado.",
    related: ["gen-17", "gen-31"],
    keywords: ["contrapropuesta", "paciente", "negociar", "cambios", "propuesta"],
  },
  {
    id: "gen-35",
    section: "general",
    question: "¿Cómo funciona el asistente de IA para dietas?",
    answer: "El generador de dietas con IA usa Groq como motor y requiere que rellenes previamente los datos clave del paciente: objetivo, alergias, preferencias, mediciones y hábitos. Con esa información genera un plan base que tú revisas, editas y validas antes de enviar. Nunca se envía directamente al paciente sin tu aprobación. Es una herramienta de ayuda, no un sustituto del criterio profesional. Aprovéchala para ganar tiempo en el borrador inicial y afinar desde ahí.",
    related: ["gen-28", "gen-36"],
    keywords: ["ia", "groq", "dieta", "asistente", "generador"],
  },
  {
    id: "gen-36",
    section: "general",
    question: "¿Hay límites de uso de la IA?",
    answer: "Dependiendo de tu plan, hay un número razonable de generaciones de dietas con IA al mes. El plan Básico cubre la mayoría de consultas típicas; el Profesional es más generoso. Si te quedas sin cuota, la app te avisa y puedes editar dietas manualmente o esperar al siguiente ciclo. También puedes duplicar dietas existentes para no gastar cuota en casos parecidos. Los límites están pensados para evitar abuso automatizado, no para limitar un uso normal.",
    related: ["gen-14", "gen-35"],
    keywords: ["límites", "ia", "cuota", "uso", "generaciones"],
  },
  {
    id: "gen-37",
    section: "general",
    question: "¿Puedo trabajar sin conexión a internet?",
    answer: "No, Annonia necesita conexión a internet para funcionar porque todos los datos y las funciones de IA corren en servidor. Si pierdes conexión durante una sesión, los formularios que no hayas guardado pueden perderse al recuperar la conexión. Te recomendamos guardar con frecuencia en cambios largos. Para consultas domiciliarias sin cobertura, usa el móvil con datos o planifica la edición cuando vuelvas a tener wifi.",
    related: ["gen-24"],
    keywords: ["offline", "sin conexión", "internet", "conexión"],
  },
  {
    id: "gen-38",
    section: "general",
    question: "¿Qué navegadores soporta Annonia?",
    answer: "La app funciona con las versiones recientes de Chrome, Firefox, Safari y Edge, tanto en escritorio como en móvil. Recomendamos mantener el navegador actualizado para evitar problemas visuales o de compatibilidad con APIs modernas. Internet Explorer no está soportado y puede dar errores graves. Si usas un navegador minoritario y ves algo raro, prueba primero en Chrome para descartar que sea un tema de compatibilidad.",
    related: ["gen-24", "gen-26"],
    keywords: ["navegadores", "chrome", "firefox", "safari", "edge", "compatibilidad"],
  },
  {
    id: "gen-39",
    section: "general",
    question: "¿Qué veo exactamente en el Dashboard principal?",
    answer: "El Dashboard es tu página de inicio y reúne un resumen diario: próximas citas del día, mensajes pendientes, pagos recientes, pacientes con seguimiento atrasado y accesos rápidos a las acciones más frecuentes (crear paciente, nueva cita, generar dieta). También hay widgets con métricas de los últimos días y un calendario compacto. Está pensado para que en 10 segundos sepas qué toca hacer hoy sin tener que entrar en cada sección.",
    related: ["gen-15", "gen-40"],
    keywords: ["dashboard", "inicio", "home", "resumen", "panel"],
  },
  {
    id: "gen-40",
    section: "general",
    question: "¿Puedo personalizar el Dashboard?",
    answer: "De momento el Dashboard tiene un layout fijo pensado para cubrir los casos de uso más habituales. No puedes mover widgets ni ocultarlos. Sí puedes, indirectamente, influir en lo que ves configurando qué notificaciones y seguimientos activas. Tenemos en el roadmap permitir personalización de widgets según el tipo de consulta (clínica, deporte, estética). Si tienes ideas sobre qué te gustaría ver destacado, mándalas al soporte.",
    related: ["gen-39", "gen-23"],
    keywords: ["personalizar", "dashboard", "layout", "widgets"],
  },
  {
    id: "gen-41",
    section: "general",
    question: "¿Qué es el seguimiento diario y dónde lo encuentro?",
    answer: "El seguimiento diario es un registro que el paciente rellena cada día desde su portal (peso, comidas reales, ánimo, agua, pasos, notas). Tú lo ves desde la ficha del paciente en la pestaña Seguimiento, con gráficas y calendarios agregados. Permite identificar patrones y desviaciones respecto al plan. Puedes configurar qué campos son obligatorios y cuáles opcionales para cada paciente. Es una herramienta clave para acompañamientos de larga duración.",
    related: ["gen-11", "gen-42"],
    keywords: ["seguimiento", "diario", "registro", "paciente", "hábitos"],
  },
  {
    id: "gen-42",
    section: "general",
    question: "¿Qué son las planificaciones en Annonia?",
    answer: "Las planificaciones son documentos adicionales al plan de alimentación donde puedes incluir entrenamientos, objetivos semanales, hitos, seguimiento de medidas o notas estratégicas para el paciente. Se crean desde la ficha del paciente y aparecen en su portal como entregables. Son útiles cuando combinas nutrición con entrenamiento o cuando das pautas que no encajan en el editor de dieta clásico. Puedes exportarlas a PDF como el resto de documentos.",
    related: ["gen-41", "gen-43"],
    keywords: ["planificación", "entrenamiento", "objetivos", "documentos"],
  },
  {
    id: "gen-43",
    section: "general",
    question: "¿Cómo exporto documentos a PDF?",
    answer: "En la mayoría de vistas con documento (dieta, informe, planificación, recomendaciones) hay un botón Exportar a PDF en la esquina. Genera un PDF con tu branding (logo, datos del nutricionista) y los datos del paciente. Puedes descargarlo o enviarlo directamente al paciente. Los PDF siempre salen en formato claro e imprimible, independientemente del tema que uses en pantalla. Revisa el resultado antes de compartirlo porque el volcado es definitivo.",
    related: ["gen-6", "gen-42"],
    keywords: ["pdf", "exportar", "imprimir", "documento", "descargar"],
  },
  {
    id: "gen-44",
    section: "general",
    question: "¿Cómo envío sugerencias o feedback sobre la app?",
    answer: "Puedes enviar sugerencias por el canal de soporte (email o el formulario desde Ajustes → Guías). Describe con detalle qué te gustaría ver, por qué te ayudaría y con qué frecuencia lo usarías. El feedback real de profesionales en ejercicio es la fuente principal de mejoras. Las ideas repetidas por varios usuarios suben de prioridad de forma natural. Si tu sugerencia se implementa, recibirás aviso cuando esté disponible.",
    related: ["gen-23", "gen-25"],
    keywords: ["feedback", "sugerencias", "opinión", "mejoras", "ideas"],
  },
  {
    id: "gen-45",
    section: "general",
    question: "¿La app sirve también para entrenadores o coaches no nutricionistas?",
    answer: "El núcleo del producto está diseñado para dietistas-nutricionistas titulados, pero muchas funciones (agenda, mensajes, planificaciones, seguimiento diario, cobros, portal del paciente) son perfectamente aprovechables por entrenadores personales, coaches de hábitos o profesionales de salud afines. Ten en cuenta que la IA está especializada en nutrición, así que su valor para otras disciplinas es limitado. Si no haces dietas, puedes usar la app como CRM de acompañamiento.",
    related: ["gen-1", "gen-42"],
    keywords: ["entrenador", "coach", "profesionales", "uso", "afines"],
  },
  {
    id: "gen-46",
    section: "general",
    question: "¿Qué pasa cuando terminan los 14 días de prueba gratuita?",
    answer: "Al terminar el periodo de prueba, si no has activado un plan, tu cuenta pasa a modo limitado: conservas el acceso a tus datos y a tus pacientes pero no puedes crear nuevos ni usar funciones premium hasta suscribirte. Nunca se borran datos por no pagar; tu trabajo queda salvo. Desde Ajustes → Suscripción puedes activar el plan Básico o Profesional en cualquier momento y retomar el uso completo al instante.",
    related: ["gen-14"],
    keywords: ["prueba", "14 días", "gratis", "fin", "trial"],
  },
  {
    id: "gen-47",
    section: "general",
    question: "¿Puedo reiniciar los tours interactivos si ya los he cerrado?",
    answer: "Sí, desde Ajustes → Guías tienes un listado de todos los tours disponibles con un botón para volver a lanzar cada uno. Esto es útil cuando un compañero empieza a usar la app o cuando vuelves tras mucho tiempo. También hay una opción global para reiniciar el estado de onboarding, que hará que los tours vuelvan a aparecer automáticamente cuando entres en cada sección por primera vez. No borra datos, solo reinicia banderas de visto.",
    related: ["gen-2", "gen-16"],
    keywords: ["tours", "reiniciar", "guías", "onboarding", "repetir"],
  },
  {
    id: "gen-48",
    section: "general",
    question: "¿Cómo sé si un cambio que he hecho se ha guardado?",
    answer: "La mayoría de formularios guardan automáticamente al cambiar de foco o al pulsar un botón Guardar visible, y muestran un mensaje tipo toast confirmando el éxito. Si ves un indicador de guardando o un pequeño spinner, espera a que termine antes de salir. Si cierras la pestaña antes de que se complete, puedes perder los cambios. Ante la duda, pulsa guardar manualmente y comprueba el toast de confirmación.",
    related: ["gen-37"],
    keywords: ["guardar", "cambios", "autosave", "confirmación", "toast"],
  },
  {
    id: "gen-49",
    section: "general",
    question: "¿Puedo colaborar con otros nutricionistas en la misma cuenta?",
    answer: "Actualmente la cuenta es individual: un usuario con sus pacientes, agenda y dietas. No hay multiusuario con roles, así que dos nutricionistas trabajando juntos necesitan dos cuentas separadas. Es una función muy solicitada y está en el roadmap para clínicas con varios profesionales. Mientras tanto, la forma más sencilla es que cada uno tenga su cuenta y compartáis recetas y plantillas manualmente. Si tienes una clínica mediana, escribe a soporte para comentar opciones.",
    related: ["gen-23", "gen-44"],
    keywords: ["colaborar", "multiusuario", "clínica", "equipo", "roles"],
  },
  {
    id: "gen-50",
    section: "general",
    question: "¿Dónde encuentro esta ayuda completa de la aplicación?",
    answer: "Esta ayuda está accesible desde el icono de ayuda (interrogación) o desde Ajustes → Guías, y se organiza por secciones que reflejan la estructura del menú principal. Puedes buscar por palabras clave y navegar entre preguntas relacionadas. Se actualiza con cada novedad importante de la app. Si no encuentras tu pregunta, escribe a soporte y la añadiremos si es de interés general. Úsala como primer paso antes de contactar, porque la mayoría de dudas habituales ya están resueltas aquí.",
    related: ["gen-16", "gen-25", "gen-44"],
    keywords: ["ayuda", "faq", "preguntas", "documentación", "help"],
  },
];
