import type { HelpEntrySkeleton } from "../types";

export const MENSAJES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "msg-1", section: "mensajes", related: ["msg-2", "msg-3", "msg-29"] },
  { id: "msg-2", section: "mensajes", related: ["msg-6", "msg-12", "msg-13"] },
  { id: "msg-3", section: "mensajes", related: ["msg-4", "msg-5", "msg-6"] },
  { id: "msg-4", section: "mensajes", related: ["msg-3", "msg-39"] },
  { id: "msg-5", section: "mensajes", related: ["msg-3", "msg-4"] },
  { id: "msg-6", section: "mensajes", related: ["msg-2", "msg-7"] },
  { id: "msg-7", section: "mensajes", related: ["msg-6", "msg-22"] },
  { id: "msg-8", section: "mensajes", related: ["msg-9", "msg-11"] },
  { id: "msg-9", section: "mensajes", related: ["msg-8", "msg-17"] },
  { id: "msg-10", section: "mensajes", related: ["msg-11", "msg-17"] },
  { id: "msg-11", section: "mensajes", related: ["msg-8", "msg-10"] },
  { id: "msg-12", section: "mensajes", related: ["msg-2", "msg-13"] },
  { id: "msg-13", section: "mensajes", related: ["msg-2", "msg-12"] },
  { id: "msg-14", section: "mensajes", related: ["msg-27", "msg-35"] },
  { id: "msg-15", section: "mensajes", related: ["msg-30", "msg-33"] },
  { id: "msg-16", section: "mensajes", related: ["msg-7"] },
  { id: "msg-17", section: "mensajes", related: ["msg-9", "msg-10"] },
  { id: "msg-18", section: "mensajes", related: ["msg-19", "msg-20"] },
  { id: "msg-19", section: "mensajes", related: ["msg-18", "msg-38"] },
  { id: "msg-20", section: "mensajes", related: ["msg-19", "msg-44"] },
  { id: "msg-21", section: "mensajes", related: ["msg-22", "msg-24"] },
  { id: "msg-22", section: "mensajes", related: ["msg-21", "msg-24"] },
  { id: "msg-23", section: "mensajes", related: ["msg-25", "msg-43"] },
  { id: "msg-24", section: "mensajes", related: ["msg-21", "msg-22"] },
  { id: "msg-25", section: "mensajes", related: ["msg-23", "msg-26"] },
  { id: "msg-26", section: "mensajes", related: ["msg-42", "msg-44"] },
  { id: "msg-27", section: "mensajes", related: ["msg-14", "msg-35"] },
  { id: "msg-28", section: "mensajes", related: ["msg-29", "msg-31"] },
  { id: "msg-29", section: "mensajes", related: ["msg-1", "msg-28"] },
  { id: "msg-30", section: "mensajes", related: ["msg-31", "msg-32"] },
  { id: "msg-31", section: "mensajes", related: ["msg-32", "msg-33"] },
  { id: "msg-32", section: "mensajes", related: ["msg-31", "msg-33"] },
  { id: "msg-33", section: "mensajes", related: ["msg-28", "msg-32"] },
  { id: "msg-34", section: "mensajes", related: ["msg-35", "msg-36"] },
  { id: "msg-35", section: "mensajes", related: ["msg-14", "msg-34"] },
  { id: "msg-36", section: "mensajes", related: ["msg-34", "msg-37"] },
  { id: "msg-37", section: "mensajes", related: ["msg-36"] },
  { id: "msg-38", section: "mensajes", related: ["msg-39", "msg-40"] },
  { id: "msg-39", section: "mensajes", related: ["msg-38", "msg-40"] },
  { id: "msg-40", section: "mensajes", related: ["msg-38", "msg-39"] },
  { id: "msg-41", section: "mensajes", related: ["msg-4", "msg-23"] },
  { id: "msg-42", section: "mensajes", related: ["msg-26", "msg-43"] },
  { id: "msg-43", section: "mensajes", related: ["msg-42"] },
  { id: "msg-44", section: "mensajes", related: ["msg-20", "msg-42"] },
  { id: "msg-45", section: "mensajes", related: ["msg-1", "msg-6"] },
];
