import type { HelpEntrySkeleton } from "../types";

export const PACIENTE_DETALLE_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pd-1", section: "paciente-detalle", related: ["pd-2", "pd-3", "pd-11"] },
  { id: "pd-2", section: "paciente-detalle", related: ["pd-3", "pd-11", "pd-12"] },
  { id: "pd-3", section: "paciente-detalle", related: ["pd-2", "pd-4"] },
  { id: "pd-4", section: "paciente-detalle", related: ["pd-5", "pd-6"] },
  { id: "pd-5", section: "paciente-detalle", related: ["pd-4", "pd-6"] },
  { id: "pd-6", section: "paciente-detalle", related: ["pd-4", "pd-5"] },
  { id: "pd-7", section: "paciente-detalle", related: ["pd-8", "pd-9", "pd-10"] },
  { id: "pd-8", section: "paciente-detalle", related: ["pd-7", "pd-24"] },
  { id: "pd-9", section: "paciente-detalle", related: ["pd-7", "pd-39", "pd-40"] },
  { id: "pd-10", section: "paciente-detalle", related: ["pd-7", "pd-33", "pd-45"] },
  { id: "pd-11", section: "paciente-detalle", related: ["pd-10", "pd-12", "pd-45"] },
  { id: "pd-12", section: "paciente-detalle", related: ["pd-11", "pd-45"] },
  { id: "pd-13", section: "paciente-detalle", related: ["pd-1", "pd-2"] },
  { id: "pd-14", section: "paciente-detalle", related: ["pd-15", "pd-16", "pd-28"] },
  { id: "pd-15", section: "paciente-detalle", related: ["pd-14", "pd-16", "pd-27"] },
  { id: "pd-16", section: "paciente-detalle", related: ["pd-14", "pd-17"] },
  { id: "pd-17", section: "paciente-detalle", related: ["pd-14", "pd-18", "pd-29"] },
  { id: "pd-18", section: "paciente-detalle", related: ["pd-17", "pd-19"] },
  { id: "pd-19", section: "paciente-detalle", related: ["pd-18", "pd-20", "pd-31"] },
  { id: "pd-20", section: "paciente-detalle", related: ["pd-4", "pd-19", "pd-32"] },
  { id: "pd-21", section: "paciente-detalle", related: ["pd-22", "pd-41"] },
  { id: "pd-22", section: "paciente-detalle", related: ["pd-23", "pd-26"] },
  { id: "pd-23", section: "paciente-detalle", related: ["pd-22", "pd-24"] },
  { id: "pd-24", section: "paciente-detalle", related: ["pd-17", "pd-25"] },
  { id: "pd-25", section: "paciente-detalle", related: ["pd-14", "pd-26"] },
  { id: "pd-26", section: "paciente-detalle", related: ["pd-25", "pd-14"] },
  { id: "pd-27", section: "paciente-detalle", related: ["pd-15", "pd-17"] },
  { id: "pd-28", section: "paciente-detalle", related: ["pd-15", "pd-16"] },
  { id: "pd-29", section: "paciente-detalle", related: ["pd-17", "pd-4", "pd-30"] },
  { id: "pd-30", section: "paciente-detalle", related: ["pd-4", "pd-29"] },
  { id: "pd-31", section: "paciente-detalle", related: ["pd-19", "pd-14"] },
  { id: "pd-32", section: "paciente-detalle", related: ["pd-4", "pd-5", "pd-20"] },
  { id: "pd-33", section: "paciente-detalle", related: ["pd-10", "pd-11"] },
  { id: "pd-34", section: "paciente-detalle", related: ["pd-9", "pd-35", "pd-39"] },
  { id: "pd-35", section: "paciente-detalle", related: ["pd-9", "pd-34", "pd-23"] },
  { id: "pd-36", section: "paciente-detalle", related: ["pd-21", "pd-41"] },
  { id: "pd-37", section: "paciente-detalle", related: ["pd-15", "pd-38"] },
  { id: "pd-38", section: "paciente-detalle", related: ["pd-37", "pd-16"] },
  { id: "pd-39", section: "paciente-detalle", related: ["pd-9", "pd-34", "pd-35"] },
  { id: "pd-40", section: "paciente-detalle", related: ["pd-14", "pd-2", "pd-25"] },
  { id: "pd-41", section: "paciente-detalle", related: ["pd-21", "pd-36", "pd-23"] },
  { id: "pd-42", section: "paciente-detalle", related: ["pd-14", "pd-19"] },
  { id: "pd-43", section: "paciente-detalle", related: ["pd-25", "pd-26"] },
  { id: "pd-44", section: "paciente-detalle", related: ["pd-7", "pd-3"] },
  { id: "pd-45", section: "paciente-detalle", related: ["pd-11", "pd-12", "pd-10"] },
  { id: "pd-46", section: "paciente-detalle", related: ["pd-7", "pd-9"] },
  { id: "pd-47", section: "paciente-detalle", related: ["pd-25", "pd-26", "pd-40"] },
  { id: "pd-48", section: "paciente-detalle", related: ["pd-4", "pd-5", "pd-32"] },
  { id: "pd-49", section: "paciente-detalle", related: ["pd-9", "pd-23"] },
  { id: "pd-50", section: "paciente-detalle", related: ["pd-4", "pd-14", "pd-25"] },
];
