import type { HelpEntrySkeleton } from "../types";

export const PACIENTE_PLAN_ALIMENTACION_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pa-1", section: "paciente-plan-alimentacion", related: ["pa-2", "pa-3", "pa-10"] },
  { id: "pa-2", section: "paciente-plan-alimentacion", related: ["pa-1", "pa-3"] },
  { id: "pa-3", section: "paciente-plan-alimentacion", related: ["pa-1", "pa-2"] },
  { id: "pa-4", section: "paciente-plan-alimentacion", related: ["pa-13", "pa-21"] },
  { id: "pa-5", section: "paciente-plan-alimentacion", related: ["pa-6", "pa-7", "pa-8"] },
  { id: "pa-6", section: "paciente-plan-alimentacion", related: ["pa-5", "pa-7"] },
  { id: "pa-7", section: "paciente-plan-alimentacion", related: ["pa-8", "pa-9", "pa-50"] },
  { id: "pa-8", section: "paciente-plan-alimentacion", related: ["pa-7", "pa-9", "pa-50"] },
  { id: "pa-9", section: "paciente-plan-alimentacion", related: ["pa-8", "pa-50", "pa-68"] },
  { id: "pa-10", section: "paciente-plan-alimentacion", related: ["pa-5", "pa-52"] },
  { id: "pa-11", section: "paciente-plan-alimentacion", related: ["pa-5", "pa-8"] },
  { id: "pa-12", section: "paciente-plan-alimentacion", related: ["pa-13", "pa-14", "pa-55"] },
  { id: "pa-13", section: "paciente-plan-alimentacion", related: ["pa-12", "pa-21", "pa-22"] },
  { id: "pa-14", section: "paciente-plan-alimentacion", related: ["pa-13", "pa-25", "pa-26"] },
  { id: "pa-15", section: "paciente-plan-alimentacion", related: ["pa-12", "pa-56"] },
  { id: "pa-16", section: "paciente-plan-alimentacion", related: ["pa-17", "pa-18", "pa-19"] },
  { id: "pa-17", section: "paciente-plan-alimentacion", related: ["pa-13", "pa-22", "pa-60"] },
  { id: "pa-18", section: "paciente-plan-alimentacion", related: ["pa-25", "pa-27", "pa-28"] },
  { id: "pa-19", section: "paciente-plan-alimentacion", related: ["pa-35", "pa-36", "pa-37"] },
  { id: "pa-20", section: "paciente-plan-alimentacion", related: ["pa-16", "pa-17", "pa-19"] },
  { id: "pa-21", section: "paciente-plan-alimentacion", related: ["pa-4", "pa-16"] },
  { id: "pa-22", section: "paciente-plan-alimentacion", related: ["pa-17", "pa-60"] },
  { id: "pa-23", section: "paciente-plan-alimentacion", related: ["pa-17", "pa-22"] },
  { id: "pa-24", section: "paciente-plan-alimentacion", related: ["pa-18", "pa-30"] },
  { id: "pa-25", section: "paciente-plan-alimentacion", related: ["pa-18", "pa-26"] },
  { id: "pa-26", section: "paciente-plan-alimentacion", related: ["pa-25", "pa-27"] },
  { id: "pa-27", section: "paciente-plan-alimentacion", related: ["pa-25", "pa-28", "pa-29"] },
  { id: "pa-28", section: "paciente-plan-alimentacion", related: ["pa-42", "pa-44"] },
  { id: "pa-29", section: "paciente-plan-alimentacion", related: ["pa-27", "pa-66"] },
  { id: "pa-30", section: "paciente-plan-alimentacion", related: ["pa-24", "pa-27", "pa-60"] },
  { id: "pa-31", section: "paciente-plan-alimentacion", related: ["pa-30", "pa-35"] },
  { id: "pa-32", section: "paciente-plan-alimentacion", related: ["pa-30", "pa-35"] },
  { id: "pa-33", section: "paciente-plan-alimentacion", related: ["pa-24", "pa-30", "pa-60"] },
  { id: "pa-34", section: "paciente-plan-alimentacion", related: ["pa-22", "pa-33"] },
  { id: "pa-35", section: "paciente-plan-alimentacion", related: ["pa-19", "pa-36"] },
  { id: "pa-36", section: "paciente-plan-alimentacion", related: ["pa-35", "pa-37", "pa-61"] },
  { id: "pa-37", section: "paciente-plan-alimentacion", related: ["pa-36", "pa-61"] },
  { id: "pa-38", section: "paciente-plan-alimentacion", related: ["pa-19", "pa-39"] },
  { id: "pa-39", section: "paciente-plan-alimentacion", related: ["pa-38"] },
  { id: "pa-40", section: "paciente-plan-alimentacion", related: ["pa-28", "pa-42", "pa-44"] },
  { id: "pa-41", section: "paciente-plan-alimentacion", related: ["pa-40", "pa-69"] },
  { id: "pa-42", section: "paciente-plan-alimentacion", related: ["pa-40", "pa-44"] },
  { id: "pa-43", section: "paciente-plan-alimentacion", related: ["pa-40", "pa-42"] },
  { id: "pa-44", section: "paciente-plan-alimentacion", related: ["pa-42", "pa-45"] },
  { id: "pa-45", section: "paciente-plan-alimentacion", related: ["pa-44", "pa-46"] },
  { id: "pa-46", section: "paciente-plan-alimentacion", related: ["pa-45", "pa-57"] },
  { id: "pa-47", section: "paciente-plan-alimentacion", related: ["pa-40", "pa-42"] },
  { id: "pa-48", section: "paciente-plan-alimentacion", related: ["pa-29", "pa-49"] },
  { id: "pa-49", section: "paciente-plan-alimentacion", related: ["pa-25", "pa-48"] },
  { id: "pa-50", section: "paciente-plan-alimentacion", related: ["pa-8", "pa-9", "pa-68"] },
  { id: "pa-51", section: "paciente-plan-alimentacion", related: ["pa-42", "pa-52"] },
  { id: "pa-52", section: "paciente-plan-alimentacion", related: ["pa-5", "pa-10", "pa-11"] },
  { id: "pa-53", section: "paciente-plan-alimentacion", related: ["pa-54", "pa-57"] },
  { id: "pa-54", section: "paciente-plan-alimentacion", related: ["pa-53"] },
  { id: "pa-55", section: "paciente-plan-alimentacion", related: ["pa-12", "pa-46"] },
  { id: "pa-56", section: "paciente-plan-alimentacion", related: ["pa-15", "pa-58"] },
  { id: "pa-57", section: "paciente-plan-alimentacion", related: ["pa-55", "pa-56"] },
  { id: "pa-58", section: "paciente-plan-alimentacion", related: ["pa-25", "pa-56"] },
  { id: "pa-59", section: "paciente-plan-alimentacion", related: ["pa-51"] },
  { id: "pa-60", section: "paciente-plan-alimentacion", related: ["pa-30", "pa-35"] },
  { id: "pa-61", section: "paciente-plan-alimentacion", related: ["pa-36", "pa-37"] },
  { id: "pa-62", section: "paciente-plan-alimentacion", related: ["pa-41", "pa-42"] },
  { id: "pa-63", section: "paciente-plan-alimentacion", related: ["pa-9", "pa-64"] },
  { id: "pa-64", section: "paciente-plan-alimentacion", related: ["pa-63"] },
  { id: "pa-65", section: "paciente-plan-alimentacion", related: ["pa-9", "pa-50"] },
  { id: "pa-66", section: "paciente-plan-alimentacion", related: ["pa-29", "pa-48", "pa-50"] },
  { id: "pa-67", section: "paciente-plan-alimentacion", related: ["pa-5", "pa-10", "pa-52"] },
  { id: "pa-68", section: "paciente-plan-alimentacion", related: ["pa-50", "pa-66"] },
  { id: "pa-69", section: "paciente-plan-alimentacion", related: ["pa-41", "pa-42"] },
  { id: "pa-70", section: "paciente-plan-alimentacion", related: ["pa-40", "pa-42", "pa-47"] },
];
