import type { HelpEntrySkeleton } from "../types";

export const PACIENTE_MEDICIONES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "med-1", section: "paciente-mediciones", related: ["med-2", "med-3", "med-52"] },
  { id: "med-2", section: "paciente-mediciones", related: ["med-1", "med-3"] },
  { id: "med-3", section: "paciente-mediciones", related: ["med-4", "med-5", "med-14"] },
  { id: "med-4", section: "paciente-mediciones", related: ["med-3", "med-39", "med-40"] },
  { id: "med-5", section: "paciente-mediciones", related: ["med-6", "med-11", "med-12"] },
  { id: "med-6", section: "paciente-mediciones", related: ["med-5", "med-11", "med-13"] },
  { id: "med-7", section: "paciente-mediciones", related: ["med-8", "med-39", "med-56"] },
  { id: "med-8", section: "paciente-mediciones", related: ["med-7", "med-39", "med-57"] },
  { id: "med-9", section: "paciente-mediciones", related: ["med-7", "med-8", "med-39"] },
  { id: "med-10", section: "paciente-mediciones", related: ["med-7", "med-39", "med-56"] },
  { id: "med-11", section: "paciente-mediciones", related: ["med-12", "med-13", "med-27"] },
  { id: "med-12", section: "paciente-mediciones", related: ["med-11", "med-13", "med-55"] },
  { id: "med-13", section: "paciente-mediciones", related: ["med-11", "med-12", "med-55"] },
  { id: "med-14", section: "paciente-mediciones", related: ["med-15", "med-16", "med-50"] },
  { id: "med-15", section: "paciente-mediciones", related: ["med-14", "med-16", "med-66"] },
  { id: "med-16", section: "paciente-mediciones", related: ["med-14", "med-15"] },
  { id: "med-17", section: "paciente-mediciones", related: ["med-18", "med-19", "med-54"] },
  { id: "med-18", section: "paciente-mediciones", related: ["med-17", "med-19", "med-54"] },
  { id: "med-19", section: "paciente-mediciones", related: ["med-18", "med-17", "med-54"] },
  { id: "med-20", section: "paciente-mediciones", related: ["med-17", "med-21", "med-54"] },
  { id: "med-21", section: "paciente-mediciones", related: ["med-17", "med-20", "med-54"] },
  { id: "med-22", section: "paciente-mediciones", related: ["med-17", "med-20", "med-54"] },
  { id: "med-23", section: "paciente-mediciones", related: ["med-17", "med-21", "med-54"] },
  { id: "med-24", section: "paciente-mediciones", related: ["med-17", "med-18", "med-54"] },
  { id: "med-25", section: "paciente-mediciones", related: ["med-3", "med-26", "med-44"] },
  { id: "med-26", section: "paciente-mediciones", related: ["med-25", "med-44"] },
  { id: "med-27", section: "paciente-mediciones", related: ["med-11", "med-6", "med-28"] },
  { id: "med-28", section: "paciente-mediciones", related: ["med-11", "med-6", "med-27"] },
  { id: "med-29", section: "paciente-mediciones", related: ["med-30", "med-31", "med-32"] },
  { id: "med-30", section: "paciente-mediciones", related: ["med-29", "med-31"] },
  { id: "med-31", section: "paciente-mediciones", related: ["med-29", "med-32", "med-33"] },
  { id: "med-32", section: "paciente-mediciones", related: ["med-29", "med-31", "med-33"] },
  { id: "med-33", section: "paciente-mediciones", related: ["med-31", "med-32", "med-69"] },
  { id: "med-34", section: "paciente-mediciones", related: ["med-29", "med-33", "med-55"] },
  { id: "med-35", section: "paciente-mediciones", related: ["med-36", "med-37", "med-38"] },
  { id: "med-36", section: "paciente-mediciones", related: ["med-35", "med-37"] },
  { id: "med-37", section: "paciente-mediciones", related: ["med-38", "med-41", "med-42"] },
  { id: "med-38", section: "paciente-mediciones", related: ["med-37", "med-41"] },
  { id: "med-39", section: "paciente-mediciones", related: ["med-7", "med-8", "med-40"] },
  { id: "med-40", section: "paciente-mediciones", related: ["med-4", "med-5", "med-39"] },
  { id: "med-41", section: "paciente-mediciones", related: ["med-37", "med-42", "med-43"] },
  { id: "med-42", section: "paciente-mediciones", related: ["med-37", "med-41", "med-43"] },
  { id: "med-43", section: "paciente-mediciones", related: ["med-44", "med-45", "med-46"] },
  { id: "med-44", section: "paciente-mediciones", related: ["med-43", "med-45"] },
  { id: "med-45", section: "paciente-mediciones", related: ["med-43", "med-44"] },
  { id: "med-46", section: "paciente-mediciones", related: ["med-43", "med-41"] },
  { id: "med-47", section: "paciente-mediciones", related: ["med-48", "med-52"] },
  { id: "med-48", section: "paciente-mediciones", related: ["med-47", "med-52"] },
  { id: "med-49", section: "paciente-mediciones", related: ["med-50", "med-51", "med-70"] },
  { id: "med-50", section: "paciente-mediciones", related: ["med-5", "med-6", "med-17"] },
  { id: "med-51", section: "paciente-mediciones", related: ["med-17", "med-18", "med-52"] },
  { id: "med-52", section: "paciente-mediciones", related: ["med-17", "med-20", "med-21", "med-22"] },
  { id: "med-53", section: "paciente-mediciones", related: ["med-60", "med-63"] },
  { id: "med-54", section: "paciente-mediciones", related: ["med-17", "med-18", "med-25"] },
  { id: "med-55", section: "paciente-mediciones", related: ["med-11", "med-12", "med-13"] },
  { id: "med-56", section: "paciente-mediciones", related: ["med-10", "med-39"] },
  { id: "med-57", section: "paciente-mediciones", related: ["med-8", "med-29", "med-34"] },
  { id: "med-58", section: "paciente-mediciones", related: ["med-59", "med-60"] },
  { id: "med-59", section: "paciente-mediciones", related: ["med-58", "med-60"] },
  { id: "med-60", section: "paciente-mediciones", related: ["med-58", "med-59"] },
  { id: "med-61", section: "paciente-mediciones", related: ["med-29", "med-49", "med-62"] },
  { id: "med-62", section: "paciente-mediciones", related: ["med-61", "med-34"] },
  { id: "med-63", section: "paciente-mediciones", related: ["med-15", "med-66"] },
  { id: "med-64", section: "paciente-mediciones", related: ["med-47", "med-65"] },
  { id: "med-65", section: "paciente-mediciones", related: ["med-64", "med-25"] },
  { id: "med-66", section: "paciente-mediciones", related: ["med-41", "med-14", "med-15"] },
  { id: "med-67", section: "paciente-mediciones", related: ["med-4", "med-29", "med-30"] },
  { id: "med-68", section: "paciente-mediciones", related: ["med-29", "med-34", "med-41"] },
  { id: "med-69", section: "paciente-mediciones", related: ["med-49", "med-70"] },
  { id: "med-70", section: "paciente-mediciones", related: ["med-49", "med-69"] },
];
