import type { HelpEntrySkeleton } from "../types";

export const PACIENTE_ENTREGABLES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "entr-1", section: "paciente-entregables", related: ["entr-2", "entr-4", "entr-5"] },
  { id: "entr-2", section: "paciente-entregables", related: ["entr-1", "entr-3"] },
  { id: "entr-3", section: "paciente-entregables", related: ["entr-1", "entr-4", "entr-5", "entr-14"] },
  { id: "entr-4", section: "paciente-entregables", related: ["entr-1", "entr-3", "entr-5", "entr-20"] },
  { id: "entr-5", section: "paciente-entregables", related: ["entr-4", "entr-20", "entr-23"] },
  { id: "entr-6", section: "paciente-entregables", related: ["entr-3", "entr-7", "entr-8"] },
  { id: "entr-7", section: "paciente-entregables", related: ["entr-6", "entr-8", "entr-9"] },
  { id: "entr-8", section: "paciente-entregables", related: ["entr-7", "entr-9"] },
  { id: "entr-9", section: "paciente-entregables", related: ["entr-7", "entr-8", "entr-15"] },
  { id: "entr-10", section: "paciente-entregables", related: ["entr-3", "entr-11", "entr-17"] },
  { id: "entr-11", section: "paciente-entregables", related: ["entr-12", "entr-13", "entr-22"] },
  { id: "entr-12", section: "paciente-entregables", related: ["entr-11", "entr-13"] },
  { id: "entr-13", section: "paciente-entregables", related: ["entr-11", "entr-12"] },
  { id: "entr-14", section: "paciente-entregables", related: ["entr-11", "entr-27"] },
  { id: "entr-15", section: "paciente-entregables", related: ["entr-9", "entr-16", "entr-17"] },
  { id: "entr-16", section: "paciente-entregables", related: ["entr-12", "entr-15"] },
  { id: "entr-17", section: "paciente-entregables", related: ["entr-10", "entr-15", "entr-34"] },
  { id: "entr-18", section: "paciente-entregables", related: ["entr-19", "entr-36"] },
  { id: "entr-19", section: "paciente-entregables", related: ["entr-18", "entr-36"] },
  { id: "entr-20", section: "paciente-entregables", related: ["entr-4", "entr-5", "entr-23"] },
  { id: "entr-21", section: "paciente-entregables", related: ["entr-22", "entr-30"] },
  { id: "entr-22", section: "paciente-entregables", related: ["entr-21", "entr-30"] },
  { id: "entr-23", section: "paciente-entregables", related: ["entr-4", "entr-5", "entr-24"] },
  { id: "entr-24", section: "paciente-entregables", related: ["entr-23", "entr-25"] },
  { id: "entr-25", section: "paciente-entregables", related: ["entr-24"] },
  { id: "entr-26", section: "paciente-entregables", related: ["entr-4", "entr-5"] },
  { id: "entr-27", section: "paciente-entregables", related: ["entr-4", "entr-5", "entr-28"] },
  { id: "entr-28", section: "paciente-entregables", related: ["entr-27", "entr-20"] },
  { id: "entr-29", section: "paciente-entregables", related: ["entr-4", "entr-5", "entr-31"] },
  { id: "entr-30", section: "paciente-entregables", related: ["entr-21", "entr-31", "entr-34"] },
  { id: "entr-31", section: "paciente-entregables", related: ["entr-30", "entr-32", "entr-39"] },
  { id: "entr-32", section: "paciente-entregables", related: ["entr-31", "entr-39"] },
  { id: "entr-33", section: "paciente-entregables", related: ["entr-21", "entr-30"] },
  { id: "entr-34", section: "paciente-entregables", related: ["entr-12", "entr-35"] },
  { id: "entr-35", section: "paciente-entregables", related: ["entr-34", "entr-12"] },
  { id: "entr-36", section: "paciente-entregables", related: ["entr-12", "entr-19", "entr-34"] },
  { id: "entr-37", section: "paciente-entregables", related: ["entr-10", "entr-38"] },
  { id: "entr-38", section: "paciente-entregables", related: ["entr-6", "entr-7", "entr-37"] },
  { id: "entr-39", section: "paciente-entregables", related: ["entr-29", "entr-40"] },
  { id: "entr-40", section: "paciente-entregables", related: ["entr-36", "entr-39"] },
];
