import type { HelpEntrySkeleton } from "../types";

export const PACIENTES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pac-1", section: "pacientes", related: ["pac-2", "pac-3", "pac-60"] },
  { id: "pac-2", section: "pacientes", related: ["pac-1", "pac-3"] },
  { id: "pac-3", section: "pacientes", related: ["pac-1", "pac-2"] },
  { id: "pac-4", section: "pacientes", related: ["pac-5", "pac-1"] },
  { id: "pac-5", section: "pacientes", related: ["pac-4"] },
  { id: "pac-6", section: "pacientes", related: ["pac-7", "pac-8", "pac-42"] },
  { id: "pac-7", section: "pacientes", related: ["pac-6", "pac-8"] },
  { id: "pac-8", section: "pacientes", related: ["pac-6", "pac-7"] },
  { id: "pac-9", section: "pacientes", related: ["pac-10", "pac-11"] },
  { id: "pac-10", section: "pacientes", related: ["pac-9", "pac-11"] },
  { id: "pac-11", section: "pacientes", related: ["pac-12", "pac-13"] },
  { id: "pac-12", section: "pacientes", related: ["pac-11", "pac-13"] },
  { id: "pac-13", section: "pacientes", related: ["pac-11", "pac-12"] },
  { id: "pac-14", section: "pacientes", related: ["pac-15", "pac-24"] },
  { id: "pac-15", section: "pacientes", related: ["pac-14", "pac-24"] },
  { id: "pac-16", section: "pacientes", related: ["pac-17"] },
  { id: "pac-17", section: "pacientes", related: ["pac-16"] },
  { id: "pac-18", section: "pacientes", related: ["pac-1"] },
  { id: "pac-19", section: "pacientes", related: ["pac-20"] },
  { id: "pac-20", section: "pacientes", related: ["pac-19"] },
  { id: "pac-21", section: "pacientes", related: ["pac-22", "pac-23"] },
  { id: "pac-22", section: "pacientes", related: ["pac-21", "pac-23"] },
  { id: "pac-23", section: "pacientes", related: ["pac-21", "pac-22"] },
  { id: "pac-24", section: "pacientes", related: ["pac-25", "pac-31"] },
  { id: "pac-25", section: "pacientes", related: ["pac-24"] },
  { id: "pac-26", section: "pacientes", related: ["pac-27", "pac-28"] },
  { id: "pac-27", section: "pacientes", related: ["pac-26"] },
  { id: "pac-28", section: "pacientes", related: ["pac-26"] },
  { id: "pac-29", section: "pacientes", related: ["pac-30", "pac-38"] },
  { id: "pac-30", section: "pacientes", related: ["pac-29", "pac-39"] },
  { id: "pac-31", section: "pacientes", related: ["pac-24"] },
  { id: "pac-32", section: "pacientes", related: ["pac-33", "pac-34", "pac-35"] },
  { id: "pac-33", section: "pacientes", related: ["pac-32", "pac-34"] },
  { id: "pac-34", section: "pacientes", related: ["pac-32", "pac-33"] },
  { id: "pac-35", section: "pacientes", related: ["pac-32", "pac-33"] },
  { id: "pac-36", section: "pacientes", related: ["pac-37"] },
  { id: "pac-37", section: "pacientes", related: ["pac-36", "pac-48"] },
  { id: "pac-38", section: "pacientes", related: ["pac-39", "pac-46", "pac-48"] },
  { id: "pac-39", section: "pacientes", related: ["pac-38", "pac-46"] },
  { id: "pac-40", section: "pacientes", related: ["pac-41", "pac-48"] },
  { id: "pac-41", section: "pacientes", related: ["pac-40", "pac-48"] },
  { id: "pac-42", section: "pacientes", related: ["pac-6", "pac-7", "pac-8"] },
  { id: "pac-43", section: "pacientes", related: ["pac-44", "pac-29"] },
  { id: "pac-44", section: "pacientes", related: ["pac-43", "pac-29"] },
  { id: "pac-45", section: "pacientes", related: ["pac-29", "pac-38", "pac-46"] },
  { id: "pac-46", section: "pacientes", related: ["pac-38", "pac-40"] },
  { id: "pac-47", section: "pacientes", related: ["pac-24"] },
  { id: "pac-48", section: "pacientes", related: ["pac-40", "pac-38"] },
  { id: "pac-49", section: "pacientes", related: ["pac-50"] },
  { id: "pac-50", section: "pacientes", related: ["pac-49", "pac-55"] },
  { id: "pac-51", section: "pacientes", related: ["pac-52", "pac-53"] },
  { id: "pac-52", section: "pacientes", related: ["pac-51", "pac-53"] },
  { id: "pac-53", section: "pacientes", related: ["pac-51", "pac-52"] },
  { id: "pac-54", section: "pacientes", related: ["pac-55"] },
  { id: "pac-55", section: "pacientes", related: ["pac-54"] },
  { id: "pac-56", section: "pacientes", related: ["pac-57"] },
  { id: "pac-57", section: "pacientes", related: ["pac-56"] },
  { id: "pac-58", section: "pacientes", related: ["pac-5"] },
  { id: "pac-59", section: "pacientes", related: ["pac-1", "pac-60"] },
  { id: "pac-60", section: "pacientes", related: ["pac-1", "pac-59"] },
  { id: "pac-61", section: "pacientes", related: ["pac-62"] },
  { id: "pac-62", section: "pacientes", related: ["pac-61"] },
  { id: "pac-63", section: "pacientes", related: ["pac-64"] },
  { id: "pac-64", section: "pacientes", related: ["pac-63"] },
  { id: "pac-65", section: "pacientes", related: ["pac-6", "pac-42"] },
  { id: "pac-66", section: "pacientes", related: ["pac-29", "pac-51"] },
  { id: "pac-67", section: "pacientes", related: ["pac-25", "pac-29"] },
  { id: "pac-68", section: "pacientes", related: ["pac-55"] },
  { id: "pac-69", section: "pacientes", related: ["pac-38", "pac-39"] },
  { id: "pac-70", section: "pacientes", related: ["pac-1", "pac-43"] },
];
