import type { HelpEntry } from "../types";

export const PACIENTES_ENTRIES: HelpEntry[] = [
  {
    id: "pac-1",
    section: "pacientes",
    question: "¿Cómo creo un nuevo paciente?",
    answer: "Pulsa el botón \"+ Nuevo paciente\" arriba a la derecha de la página /pacientes. Se abrirá el formulario en /pacientes/nuevo, donde podrás introducir datos personales, historial médico, objetivo y preferencias. Al guardar, el paciente aparecerá en el listado como Activo.",
    related: ["pac-2", "pac-3", "pac-60"],
    keywords: ["nuevo", "crear", "alta", "añadir", "paciente"],
  },
  {
    id: "pac-2",
    section: "pacientes",
    question: "¿Qué campos son obligatorios al dar de alta un paciente?",
    answer: "Los campos obligatorios son nombre, apellidos y email. El resto (teléfono, fecha de nacimiento, sexo, altura, peso inicial, objetivo, foto, alergias, patologías, medicamentos, suplementos, preferencias y notas) son opcionales, pero rellenarlos mejora la calidad de las recomendaciones y del plan.",
    related: ["pac-1", "pac-3"],
    keywords: ["obligatorios", "opcionales", "campos", "requeridos"],
  },
  {
    id: "pac-3",
    section: "pacientes",
    question: "¿Qué campos contiene el formulario de alta?",
    answer: "El formulario incluye: nombre, apellidos, email, teléfono, foto, fecha de nacimiento, sexo, altura, peso inicial, objetivo, alergias, intolerancias, patologías, medicamentos, suplementos, preferencias alimentarias y notas libres. Está dividido en bloques para facilitar el relleno.",
    related: ["pac-1", "pac-2"],
    keywords: ["campos", "formulario", "alta", "datos"],
  },
  {
    id: "pac-4",
    section: "pacientes",
    question: "¿Qué objetivos puedo asignar a un paciente?",
    answer: "Los objetivos disponibles son: Perder peso, Ganar masa muscular, Mantenimiento, Mejora del rendimiento deportivo, Salud general y Control de patología. Se selecciona uno en el desplegable del formulario y marca el enfoque del plan nutricional.",
    related: ["pac-5", "pac-1"],
    keywords: ["objetivo", "meta", "perder peso", "ganar masa", "mantenimiento", "rendimiento"],
  },
  {
    id: "pac-5",
    section: "pacientes",
    question: "¿Puedo cambiar el objetivo de un paciente más adelante?",
    answer: "Sí. Entra en la ficha del paciente, pulsa Editar y cambia el objetivo en el desplegable. El cambio se guarda al pulsar Guardar y afectará a las recomendaciones futuras, no a los planes ya creados.",
    related: ["pac-4"],
    keywords: ["cambiar", "objetivo", "editar", "modificar"],
  },
  {
    id: "pac-6",
    section: "pacientes",
    question: "¿Cómo subo la foto de un paciente?",
    answer: "En el formulario de alta o en la ficha pulsa el avatar/botón \"Cambiar foto\". Se abrirá el selector de archivos. Admite formatos JPG, PNG y WebP. El tamaño máximo es 2 MB. Si no subes foto, se muestran las iniciales del paciente sobre un color generado automáticamente.",
    related: ["pac-7", "pac-8", "pac-42"],
    keywords: ["foto", "avatar", "imagen", "subir", "cambiar"],
  },
  {
    id: "pac-7",
    section: "pacientes",
    question: "¿Qué formatos de imagen admite la foto del paciente?",
    answer: "Se admiten JPG, PNG y WebP. Otros formatos (HEIC, BMP, TIFF) no se suben. Si tu foto viene de iPhone en HEIC, conviértela antes a JPG.",
    related: ["pac-6", "pac-8"],
    keywords: ["formato", "jpg", "png", "webp", "imagen"],
  },
  {
    id: "pac-8",
    section: "pacientes",
    question: "¿Cuál es el tamaño máximo de la foto?",
    answer: "El límite es 2 MB por imagen. Si la foto pesa más, redúcela o comprímela antes de subirla. La aplicación la redimensiona internamente para optimizar el almacenamiento.",
    related: ["pac-6", "pac-7"],
    keywords: ["tamaño", "peso", "mb", "máximo", "foto"],
  },
  {
    id: "pac-9",
    section: "pacientes",
    question: "¿Cómo añado las alergias del paciente?",
    answer: "En el formulario hay un campo \"Alergias\" donde puedes escribir las alergias separadas por coma. Ejemplo: \"frutos secos, marisco, huevo\". Se guardan como etiquetas y se muestran en la ficha y en los planes generados.",
    related: ["pac-10", "pac-11"],
    keywords: ["alergias", "separadas", "coma", "añadir"],
  },
  {
    id: "pac-10",
    section: "pacientes",
    question: "¿Cómo registro las intolerancias alimentarias?",
    answer: "Usa el campo \"Intolerancias\" en la ficha del paciente. Escribe cada intolerancia separada por comas (por ejemplo: \"lactosa, gluten, fructosa\"). Las intolerancias se tienen en cuenta al generar el plan con IA y se muestran como aviso en recetas incompatibles.",
    related: ["pac-9", "pac-11"],
    keywords: ["intolerancias", "lactosa", "gluten", "fructosa"],
  },
  {
    id: "pac-11",
    section: "pacientes",
    question: "¿Cómo añado patologías?",
    answer: "En el bloque de historial médico tienes el campo \"Patologías\". Escribe las patologías o diagnósticos separados por coma (diabetes tipo 2, hipertensión, hipotiroidismo, etc.). Quedan registradas en la ficha y se pueden consultar en la sección de información clínica.",
    related: ["pac-12", "pac-13"],
    keywords: ["patologías", "enfermedades", "diagnóstico"],
  },
  {
    id: "pac-12",
    section: "pacientes",
    question: "¿Cómo registro los medicamentos que toma el paciente?",
    answer: "Usa el campo \"Medicamentos\" en el formulario. Introduce los medicamentos separados por coma, preferentemente indicando principio activo (por ejemplo: \"metformina 850 mg, enalapril 10 mg\"). Aparecerán en la ficha como etiquetas.",
    related: ["pac-11", "pac-13"],
    keywords: ["medicamentos", "fármacos", "medicación"],
  },
  {
    id: "pac-13",
    section: "pacientes",
    question: "¿Cómo anoto los suplementos que toma el paciente?",
    answer: "En el campo \"Suplementos\" escribe los suplementos separados por coma (por ejemplo: \"vitamina D, omega 3, creatina\"). Se guardan como etiquetas y se tienen en cuenta al revisar ingestas totales y al recomendar ajustes.",
    related: ["pac-11", "pac-12"],
    keywords: ["suplementos", "vitaminas", "creatina"],
  },
  {
    id: "pac-14",
    section: "pacientes",
    question: "¿Se calcula el IMC automáticamente?",
    answer: "Sí. Cuando introduces la altura y el peso inicial, la ficha calcula el IMC (peso en kg dividido por la altura en m al cuadrado) y lo muestra en la tabla de pacientes. Si falta altura o peso, la columna IMC aparece como \"—\".",
    related: ["pac-15", "pac-24"],
    keywords: ["imc", "índice masa corporal", "calcular"],
  },
  {
    id: "pac-15",
    section: "pacientes",
    question: "¿Qué unidades usa la aplicación para peso y altura?",
    answer: "El peso se guarda en kilogramos (kg) y la altura en centímetros (cm). Introduce solo números, sin la unidad. Por ejemplo: 72.5 para el peso y 168 para la altura.",
    related: ["pac-14", "pac-24"],
    keywords: ["unidades", "kg", "cm", "peso", "altura"],
  },
  {
    id: "pac-16",
    section: "pacientes",
    question: "¿La edad se calcula sola a partir de la fecha de nacimiento?",
    answer: "Sí. Al introducir la fecha de nacimiento en el formulario, la aplicación calcula la edad automáticamente y la muestra en la ficha del paciente. Se actualiza cada día, así que no tienes que recalcularla manualmente.",
    related: ["pac-17"],
    keywords: ["edad", "fecha nacimiento", "automática", "calcular"],
  },
  {
    id: "pac-17",
    section: "pacientes",
    question: "¿Puedo dejar la fecha de nacimiento vacía?",
    answer: "Sí, es un campo opcional. Si la dejas vacía, no se mostrará edad en la ficha y ciertos cálculos (como el gasto energético basal) pedirán que la completes antes de usarlos.",
    related: ["pac-16"],
    keywords: ["fecha", "nacimiento", "vacía", "opcional"],
  },
  {
    id: "pac-18",
    section: "pacientes",
    question: "¿Qué valores acepta el campo Sexo?",
    answer: "El campo Sexo acepta tres valores: Hombre, Mujer y Prefiero no decirlo. Se usa únicamente para los cálculos energéticos (Harris-Benedict, Mifflin) y no aparece en la vista pública del paciente si selecciona \"Prefiero no decirlo\".",
    related: ["pac-1"],
    keywords: ["sexo", "género", "hombre", "mujer"],
  },
  {
    id: "pac-19",
    section: "pacientes",
    question: "¿Qué son las preferencias alimentarias?",
    answer: "Es un campo de texto libre donde anotas gustos, aversiones, tipo de dieta (vegetariana, vegana, keto...), alimentos que el paciente no quiere comer o frecuencia habitual. Esta información se muestra en la ficha y se usa al generar planes con IA.",
    related: ["pac-20"],
    keywords: ["preferencias", "gustos", "dieta", "vegetariano", "vegano"],
  },
  {
    id: "pac-20",
    section: "pacientes",
    question: "¿Para qué sirve el campo Notas?",
    answer: "Es un campo libre para apuntar observaciones del profesional: horarios laborales, estado emocional, contexto familiar, motivaciones, etc. No se comparte con el paciente y es solo para tu referencia interna.",
    related: ["pac-19"],
    keywords: ["notas", "observaciones", "comentarios"],
  },
  {
    id: "pac-21",
    section: "pacientes",
    question: "¿Cómo cambio entre vista de tabla y vista de tarjetas?",
    answer: "En la esquina superior derecha del listado hay un conmutador con dos iconos: filas (tabla) y cuadrícula (tarjetas). Pulsa el que prefieras. Tu elección se recuerda en tu navegador hasta que la cambies.",
    related: ["pac-22", "pac-23"],
    keywords: ["vista", "tabla", "tarjetas", "toggle", "cambiar"],
  },
  {
    id: "pac-22",
    section: "pacientes",
    question: "¿Cuándo conviene la vista de tabla?",
    answer: "La vista de tabla es útil cuando tienes muchos pacientes y quieres ver de un vistazo columnas como IMC, estado, objetivo y fecha de alta. También facilita ordenar por columna y localizar visualmente a quien buscas.",
    related: ["pac-21", "pac-23"],
    keywords: ["tabla", "vista", "listado"],
  },
  {
    id: "pac-23",
    section: "pacientes",
    question: "¿Cuándo conviene la vista de tarjetas?",
    answer: "La vista de tarjetas es más visual y destaca la foto y el nombre. Es recomendable cuando tienes pocos pacientes o quieres un panel limpio para revisar avatares y badges de notificación de forma rápida.",
    related: ["pac-21", "pac-22"],
    keywords: ["tarjetas", "cards", "vista"],
  },
  {
    id: "pac-24",
    section: "pacientes",
    question: "¿Qué columnas muestra la vista de tabla?",
    answer: "La tabla tiene seis columnas: Paciente (avatar + nombre), Contacto (email y teléfono), Objetivo, IMC, Estado (Activo/Inactivo) y Fecha de alta. En pantallas pequeñas algunas columnas se ocultan para priorizar lo esencial.",
    related: ["pac-25", "pac-31"],
    keywords: ["columnas", "tabla", "paciente", "imc", "estado"],
  },
  {
    id: "pac-25",
    section: "pacientes",
    question: "¿Puedo ordenar por columnas en la tabla?",
    answer: "Sí. Pulsa en la cabecera de columnas como Nombre, IMC o Fecha de alta para ordenar ascendente o descendente. Una flecha indica el orden aplicado. Tocar dos veces la misma cabecera invierte el orden.",
    related: ["pac-24"],
    keywords: ["ordenar", "columnas", "ascendente", "descendente"],
  },
  {
    id: "pac-26",
    section: "pacientes",
    question: "¿Cómo funciona el buscador de pacientes?",
    answer: "El campo de búsqueda filtra sobre la marcha por nombre, apellidos o email. Ignora mayúsculas y acentos, así que \"maria\" encuentra a \"María\". No busca por teléfono ni por notas internas.",
    related: ["pac-27", "pac-28"],
    keywords: ["buscador", "búsqueda", "filtrar", "nombre", "email"],
  },
  {
    id: "pac-27",
    section: "pacientes",
    question: "¿El buscador distingue acentos o mayúsculas?",
    answer: "No. El buscador normaliza el texto: ignora mayúsculas, minúsculas y acentos. Puedes escribir \"jose\" y encontrarás a \"José\".",
    related: ["pac-26"],
    keywords: ["acentos", "mayúsculas", "normalizar", "buscar"],
  },
  {
    id: "pac-28",
    section: "pacientes",
    question: "¿Puedo buscar por teléfono?",
    answer: "No. El buscador actual trabaja con nombre, apellidos y email. Si necesitas localizar a alguien por teléfono, ordena por la columna Contacto o pega el número en el campo de email (si lo guardaste así).",
    related: ["pac-26"],
    keywords: ["teléfono", "buscar", "móvil"],
  },
  {
    id: "pac-29",
    section: "pacientes",
    question: "¿Qué hace el filtro \"Solo activos\"?",
    answer: "Cuando está marcado, el listado oculta los pacientes desactivados. Úsalo para ver tu cartera real de pacientes en curso. Al desmarcarlo aparecen también los inactivos (útil para reactivar o revisar históricos).",
    related: ["pac-30", "pac-38"],
    keywords: ["filtro", "solo activos", "activos", "inactivos"],
  },
  {
    id: "pac-30",
    section: "pacientes",
    question: "¿Dónde veo los pacientes inactivos?",
    answer: "Desmarca el check \"Solo activos\" en la parte superior del listado. Aparecerán todos los pacientes, incluidos los desactivados, que se identifican con la etiqueta \"Inactivo\" en la columna Estado.",
    related: ["pac-29", "pac-39"],
    keywords: ["inactivos", "desactivados", "ver"],
  },
  {
    id: "pac-31",
    section: "pacientes",
    question: "¿Qué columnas se ocultan en pantallas pequeñas?",
    answer: "En móvil y tablets verticales se ocultan primero Fecha de alta, IMC y parte del Contacto, priorizando avatar, nombre, objetivo y estado. En la vista de tarjetas toda la información se reordena para caber en una sola columna.",
    related: ["pac-24"],
    keywords: ["responsive", "móvil", "columnas", "pantalla"],
  },
  {
    id: "pac-32",
    section: "pacientes",
    question: "¿Qué significa el badge rojo con número sobre el avatar?",
    answer: "Es un indicador de notificaciones pendientes para ese paciente. El número es la cantidad de avisos abiertos. Al pasar el ratón sobre el badge se muestra un tooltip con los detalles concretos.",
    related: ["pac-33", "pac-34", "pac-35"],
    keywords: ["badge", "rojo", "notificaciones", "avatar"],
  },
  {
    id: "pac-33",
    section: "pacientes",
    question: "¿Qué tipos de avisos genera el badge rojo?",
    answer: "Hay cuatro: SIN_MEDIDAS (lleva tiempo sin registrar peso o medidas), SIN_CONSULTA (hace demasiado que no tiene consulta), DIARIO_NUEVO (ha subido entradas en el diario sin revisar) y PLAN_ANTIGUO (su plan actual lleva muchos días sin actualizarse).",
    related: ["pac-32", "pac-34"],
    keywords: ["sin medidas", "sin consulta", "diario nuevo", "plan antiguo", "tipos"],
  },
  {
    id: "pac-34",
    section: "pacientes",
    question: "¿Cómo consulto el detalle de las notificaciones de un paciente?",
    answer: "Pasa el ratón sobre el badge rojo del avatar. Aparece un tooltip con la lista de avisos (por ejemplo: \"Sin medidas desde hace 20 días\" o \"Diario con 3 entradas nuevas\"). Pulsando en el paciente entras en su ficha para resolverlos.",
    related: ["pac-32", "pac-33"],
    keywords: ["tooltip", "detalle", "notificaciones", "avisos"],
  },
  {
    id: "pac-35",
    section: "pacientes",
    question: "¿Cómo hago desaparecer el badge rojo?",
    answer: "Los avisos se limpian al resolver su causa: registrar una medida, crear una consulta, revisar el diario o actualizar el plan. En cuanto la condición deja de cumplirse, el contador baja y cuando llega a cero el badge desaparece.",
    related: ["pac-32", "pac-33"],
    keywords: ["quitar", "badge", "resolver", "notificaciones"],
  },
  {
    id: "pac-36",
    section: "pacientes",
    question: "¿Qué es el badge amarillo \"Ejemplo\" del paciente demo?",
    answer: "El paciente \"Paciente Prueba\" es un paciente de demostración creado para que explores la aplicación sin introducir datos reales. El badge amarillo \"Ejemplo\" lo identifica para que no lo confundas con uno real.",
    related: ["pac-37"],
    keywords: ["ejemplo", "demo", "paciente prueba", "badge amarillo"],
  },
  {
    id: "pac-37",
    section: "pacientes",
    question: "¿Puedo borrar el paciente demo \"Paciente Prueba\"?",
    answer: "Sí. Puedes eliminarlo desde su ficha en la sección de acciones, igual que cualquier otro paciente. También puedes dejarlo como referencia para revisar ejemplos de planes, medidas y mensajes.",
    related: ["pac-36", "pac-48"],
    keywords: ["borrar", "ejemplo", "paciente prueba", "eliminar"],
  },
  {
    id: "pac-38",
    section: "pacientes",
    question: "¿Cómo desactivo un paciente?",
    answer: "Entra en la ficha del paciente, baja a la sección \"Acciones\" y pulsa \"Desactivar paciente\". Pasará a estado Inactivo, dejará de contar para el límite de tu suscripción y no aparecerá en el listado salvo que desmarques \"Solo activos\".",
    related: ["pac-39", "pac-46", "pac-48"],
    keywords: ["desactivar", "inactivo", "pausar"],
  },
  {
    id: "pac-39",
    section: "pacientes",
    question: "¿Cómo reactivo un paciente desactivado?",
    answer: "Desmarca \"Solo activos\" para ver los inactivos, abre la ficha del paciente y pulsa \"Reactivar\" en la sección de acciones. Vuelve a contar como paciente activo y aparecerá con normalidad en el listado.",
    related: ["pac-38", "pac-46"],
    keywords: ["reactivar", "volver a activar", "activo"],
  },
  {
    id: "pac-40",
    section: "pacientes",
    question: "¿Cómo elimino un paciente definitivamente?",
    answer: "En la ficha, sección \"Acciones\", pulsa \"Eliminar paciente\". Tendrás que confirmar escribiendo el nombre. Esto borra datos personales, medidas, planes y mensajes asociados y no se puede deshacer.",
    related: ["pac-41", "pac-48"],
    keywords: ["eliminar", "borrar", "delete", "definitivo"],
  },
  {
    id: "pac-41",
    section: "pacientes",
    question: "¿Puedo recuperar un paciente eliminado?",
    answer: "No. La eliminación es irreversible: se borran ficha, medidas, consultas, diario y planes. Si solo quieres dejar de atenderle, usa la opción Desactivar para conservar el histórico.",
    related: ["pac-40", "pac-48"],
    keywords: ["recuperar", "deshacer", "eliminado"],
  },
  {
    id: "pac-42",
    section: "pacientes",
    question: "¿Cómo cambio la foto de un paciente existente?",
    answer: "Abre la ficha, pulsa sobre el avatar o el botón \"Cambiar foto\" y selecciona la nueva imagen (JPG, PNG o WebP, máximo 2 MB). El cambio se guarda automáticamente y se reflejará en el listado.",
    related: ["pac-6", "pac-7", "pac-8"],
    keywords: ["cambiar", "foto", "actualizar", "avatar"],
  },
  {
    id: "pac-43",
    section: "pacientes",
    question: "¿Puedo exportar el listado de pacientes?",
    answer: "Sí. En la parte superior del listado hay un botón \"Exportar\" que descarga un CSV con los pacientes visibles según los filtros aplicados. Incluye nombre, email, teléfono, objetivo, IMC, estado y fecha de alta.",
    related: ["pac-44", "pac-29"],
    keywords: ["exportar", "csv", "descargar", "listado"],
  },
  {
    id: "pac-44",
    section: "pacientes",
    question: "¿Qué filtros respeta la exportación?",
    answer: "La exportación respeta el texto del buscador y el filtro \"Solo activos\". Si exportas con \"Solo activos\" marcado, el CSV contiene únicamente activos. Desmarca el filtro para exportar también los inactivos.",
    related: ["pac-43", "pac-29"],
    keywords: ["exportar", "filtros", "csv"],
  },
  {
    id: "pac-45",
    section: "pacientes",
    question: "¿Qué significa el estado \"Activo\" / \"Inactivo\"?",
    answer: "Activo es el paciente en seguimiento normal: puede acceder al portal, recibir mensajes y consume una plaza de tu suscripción. Inactivo está archivado: no cuenta para el límite, no recibe recordatorios y no aparece si filtras \"Solo activos\".",
    related: ["pac-29", "pac-38", "pac-46"],
    keywords: ["estado", "activo", "inactivo", "significa"],
  },
  {
    id: "pac-46",
    section: "pacientes",
    question: "¿Cuándo conviene desactivar y cuándo eliminar?",
    answer: "Desactiva cuando el paciente deja de venir temporalmente o cuando quieres conservar su historial sin gastar plaza. Elimina solo si te lo pide por borrado de datos o si fue un alta errónea, ya que no se puede recuperar.",
    related: ["pac-38", "pac-40"],
    keywords: ["desactivar", "eliminar", "diferencia", "cuándo"],
  },
  {
    id: "pac-47",
    section: "pacientes",
    question: "¿Qué es la Fecha de alta?",
    answer: "Es la fecha en la que creaste la ficha del paciente. Se asigna automáticamente y no se puede editar. Sirve como referencia histórica para saber desde cuándo le atiendes.",
    related: ["pac-24"],
    keywords: ["fecha alta", "creación", "registro"],
  },
  {
    id: "pac-48",
    section: "pacientes",
    question: "¿Dónde está el botón de eliminar en la ficha?",
    answer: "Entra en la ficha del paciente y baja hasta la sección \"Acciones\" (o \"Zona de peligro\"). Ahí encontrarás los botones \"Desactivar\" y \"Eliminar paciente\", separados visualmente del resto de contenidos.",
    related: ["pac-40", "pac-38"],
    keywords: ["eliminar", "botón", "acciones", "zona peligro"],
  },
  {
    id: "pac-49",
    section: "pacientes",
    question: "¿En qué formato debo guardar el teléfono?",
    answer: "No hay formato obligatorio, pero se recomienda el formato internacional con prefijo, por ejemplo \"+34 612 345 678\". Así funcionan los enlaces WhatsApp y las llamadas desde móvil. Se permiten también formatos locales sin prefijo.",
    related: ["pac-50"],
    keywords: ["teléfono", "formato", "prefijo", "whatsapp"],
  },
  {
    id: "pac-50",
    section: "pacientes",
    question: "¿En qué formato debo introducir el email?",
    answer: "Un email estándar del tipo nombre@dominio.com. La aplicación valida el formato al guardar. Este email se usa para mensajes internos y, si es el mismo que el del portal del paciente, para que inicie sesión.",
    related: ["pac-49", "pac-55"],
    keywords: ["email", "correo", "formato"],
  },
  {
    id: "pac-51",
    section: "pacientes",
    question: "¿Cuántos pacientes puedo tener con el plan Básico?",
    answer: "El plan Básico admite hasta 25 pacientes activos. Los inactivos no cuentan. Al llegar al límite, la creación de nuevos pacientes quedará bloqueada hasta que desactives a alguno o cambies de plan.",
    related: ["pac-52", "pac-53"],
    keywords: ["límite", "básico", "25", "suscripción"],
  },
  {
    id: "pac-52",
    section: "pacientes",
    question: "¿Cuántos pacientes puedo tener con el plan Profesional?",
    answer: "El plan Profesional ofrece pacientes ilimitados. No verás el bloqueo al crear nuevos pacientes ni tendrás que desactivar para hacer hueco.",
    related: ["pac-51", "pac-53"],
    keywords: ["profesional", "ilimitado", "suscripción"],
  },
  {
    id: "pac-53",
    section: "pacientes",
    question: "¿Qué pasa si supero el límite de pacientes de mi plan?",
    answer: "Si intentas crear uno más del límite del plan Básico, la aplicación te lo impide y sugiere desactivar a algún paciente o cambiar al plan Profesional. Los pacientes inactivos no cuentan para el límite.",
    related: ["pac-51", "pac-52"],
    keywords: ["límite", "superar", "25", "bloqueo"],
  },
  {
    id: "pac-54",
    section: "pacientes",
    question: "¿Cómo comparto la ficha del paciente con el propio paciente?",
    answer: "No se comparte una ficha completa con datos internos, pero sí tiene acceso a su portal. Desde la ficha, sección \"Portal\", pulsa \"Invitar al portal\" y el paciente recibirá un correo con un enlace para entrar con su email.",
    related: ["pac-55"],
    keywords: ["compartir", "portal", "paciente", "invitar"],
  },
  {
    id: "pac-55",
    section: "pacientes",
    question: "¿Qué ve el paciente en su portal?",
    answer: "El paciente ve sus medidas, su plan de alimentación, su agenda de citas, sus mensajes y el diario de comidas, además de los recursos que le compartas. No ve notas internas ni el contenido de \"Acciones\" ni su objetivo si lo ocultas.",
    related: ["pac-54"],
    keywords: ["portal", "ve", "paciente", "privacidad"],
  },
  {
    id: "pac-56",
    section: "pacientes",
    question: "¿Puedo pasar un paciente de un nutricionista a otro?",
    answer: "No. De momento no se soporta transferir un paciente entre cuentas de nutricionistas. La única opción manual es dar de alta al paciente en la nueva cuenta e introducir de nuevo sus datos clave.",
    related: ["pac-57"],
    keywords: ["transferir", "pasar", "otro nutricionista"],
  },
  {
    id: "pac-57",
    section: "pacientes",
    question: "¿Puedo duplicar un paciente?",
    answer: "No existe una opción de duplicar pacientes. Lo más parecido es dar de alta uno nuevo y copiar manualmente los campos que te interesen. Duplicar pacientes reales generaría datos confusos y por eso no está contemplado.",
    related: ["pac-56"],
    keywords: ["duplicar", "clonar", "copia"],
  },
  {
    id: "pac-58",
    section: "pacientes",
    question: "¿Puedo cambiar el nombre de un paciente después de creado?",
    answer: "Sí. Entra en la ficha del paciente, pulsa Editar y modifica nombre y/o apellidos. Al guardar, el cambio se refleja en el listado, en las consultas y en los planes sin perder el histórico.",
    related: ["pac-5"],
    keywords: ["cambiar", "nombre", "editar", "apellidos"],
  },
  {
    id: "pac-59",
    section: "pacientes",
    question: "¿Puedo añadir un paciente desde el dashboard?",
    answer: "Sí. En el dashboard de inicio hay una tarjeta de \"Accesos rápidos\" con el botón \"Nuevo paciente\", que lleva directamente al formulario /pacientes/nuevo sin pasar por el listado.",
    related: ["pac-1", "pac-60"],
    keywords: ["dashboard", "accesos rápidos", "nuevo paciente"],
  },
  {
    id: "pac-60",
    section: "pacientes",
    question: "¿Desde dónde puedo llegar al formulario de alta?",
    answer: "Hay tres atajos: el botón \"+ Nuevo paciente\" en la esquina superior derecha de /pacientes, la tarjeta \"Nuevo paciente\" en Accesos rápidos del dashboard y el menú de la barra lateral (si la configuras con ese acceso).",
    related: ["pac-1", "pac-59"],
    keywords: ["formulario", "alta", "atajos", "acceso"],
  },
  {
    id: "pac-61",
    section: "pacientes",
    question: "¿Cómo veo todas las citas de un paciente?",
    answer: "Desde la ficha del paciente, abre la pestaña \"Citas\" o \"Consultas\". Verás la lista completa de consultas pasadas y futuras ordenadas por fecha, con el motivo y su estado.",
    related: ["pac-62"],
    keywords: ["citas", "consultas", "agenda", "paciente"],
  },
  {
    id: "pac-62",
    section: "pacientes",
    question: "¿Puedo crear una cita directamente desde la ficha?",
    answer: "Sí. En la pestaña \"Citas\" de la ficha hay un botón \"+ Nueva cita\". Se abrirá el formulario de agenda con el paciente ya seleccionado, solo tienes que elegir fecha, hora y duración.",
    related: ["pac-61"],
    keywords: ["crear", "cita", "nueva", "ficha"],
  },
  {
    id: "pac-63",
    section: "pacientes",
    question: "¿Cómo entro en la ficha de un paciente desde el listado?",
    answer: "Haz clic sobre su fila en la tabla o sobre su tarjeta en la vista de tarjetas. Se abrirá la ficha completa con datos personales, medidas, planes, consultas, mensajes y acciones.",
    related: ["pac-64"],
    keywords: ["entrar", "ficha", "listado", "abrir"],
  },
  {
    id: "pac-64",
    section: "pacientes",
    question: "¿El avatar siempre es clicable?",
    answer: "Sí. En ambas vistas, clicar el avatar, el nombre o cualquier parte de la fila/tarjeta abre la ficha del paciente. El tooltip del badge rojo no interfiere con ese clic.",
    related: ["pac-63"],
    keywords: ["avatar", "clicable", "entrar", "ficha"],
  },
  {
    id: "pac-65",
    section: "pacientes",
    question: "¿Qué se muestra si el paciente no tiene foto?",
    answer: "Se muestra un avatar con las iniciales del nombre y apellido sobre un color de fondo generado a partir del nombre. El color es siempre el mismo para el mismo paciente, así es fácil reconocerlo.",
    related: ["pac-6", "pac-42"],
    keywords: ["sin foto", "iniciales", "avatar", "color"],
  },
  {
    id: "pac-66",
    section: "pacientes",
    question: "¿Cómo sé cuántos pacientes tengo activos?",
    answer: "En el listado, con \"Solo activos\" marcado, el contador al lado del título muestra el número actual. También puedes ver el consumo y el límite de tu plan en Ajustes > Suscripción.",
    related: ["pac-29", "pac-51"],
    keywords: ["contador", "cuántos", "activos", "total"],
  },
  {
    id: "pac-67",
    section: "pacientes",
    question: "¿Puedo filtrar por objetivo en el listado?",
    answer: "El filtro principal es \"Solo activos\" más el buscador de texto. No hay filtro específico por objetivo, pero puedes ordenar por la columna Objetivo (en vista tabla) para agrupar visualmente a los pacientes que comparten meta.",
    related: ["pac-25", "pac-29"],
    keywords: ["filtrar", "objetivo", "ordenar"],
  },
  {
    id: "pac-68",
    section: "pacientes",
    question: "¿Los datos del paciente son privados?",
    answer: "Sí. Solo tú (y los colaboradores con permiso en tu cuenta) accedéis a la información clínica y a las notas internas. El paciente solo ve desde su portal lo que le compartes. Todo se almacena cifrado.",
    related: ["pac-55"],
    keywords: ["privacidad", "privados", "seguridad"],
  },
  {
    id: "pac-69",
    section: "pacientes",
    question: "¿Qué pasa con las citas y planes si desactivo a un paciente?",
    answer: "Se conservan intactos en la ficha. Solo cambia que el paciente deja de aparecer en filtros \"Solo activos\", no recibe recordatorios y no cuenta para el límite. Si lo reactivas, todo vuelve a estar disponible tal cual.",
    related: ["pac-38", "pac-39"],
    keywords: ["desactivar", "citas", "planes", "histórico"],
  },
  {
    id: "pac-70",
    section: "pacientes",
    question: "¿Puedo añadir pacientes en bloque (importación masiva)?",
    answer: "La importación masiva desde CSV no está disponible actualmente. Los pacientes deben crearse uno a uno mediante el formulario de alta. Si llegas desde otra herramienta, usa la exportación de la original y ve copiando los campos clave al formulario.",
    related: ["pac-1", "pac-43"],
    keywords: ["importar", "masiva", "csv", "bloque"],
  },
];
