import type { HelpEntrySkeleton } from "../types";

export const PACIENTE_PLANIFICACION_ENTRIES: HelpEntrySkeleton[] = [
  { id: "plan-1", section: "paciente-planificacion", related: ["plan-2", "plan-3", "plan-19"] },
  { id: "plan-2", section: "paciente-planificacion", related: ["plan-1", "plan-19", "plan-17"] },
  { id: "plan-3", section: "paciente-planificacion", related: ["plan-4", "plan-10", "plan-11"] },
  { id: "plan-4", section: "paciente-planificacion", related: ["plan-3", "plan-11"] },
  { id: "plan-5", section: "paciente-planificacion", related: ["plan-6", "plan-11", "plan-14"] },
  { id: "plan-6", section: "paciente-planificacion", related: ["plan-5", "plan-11", "plan-7"] },
  { id: "plan-7", section: "paciente-planificacion", related: ["plan-8", "plan-9", "plan-15"] },
  { id: "plan-8", section: "paciente-planificacion", related: ["plan-7", "plan-9", "plan-15"] },
  { id: "plan-9", section: "paciente-planificacion", related: ["plan-7", "plan-8", "plan-15"] },
  { id: "plan-10", section: "paciente-planificacion", related: ["plan-3", "plan-11", "plan-12"] },
  { id: "plan-11", section: "paciente-planificacion", related: ["plan-10", "plan-3", "plan-12"] },
  { id: "plan-12", section: "paciente-planificacion", related: ["plan-11", "plan-10"] },
  { id: "plan-13", section: "paciente-planificacion", related: ["plan-14", "plan-20"] },
  { id: "plan-14", section: "paciente-planificacion", related: ["plan-13", "plan-20"] },
  { id: "plan-15", section: "paciente-planificacion", related: ["plan-16", "plan-31"] },
  { id: "plan-16", section: "paciente-planificacion", related: ["plan-15", "plan-31"] },
  { id: "plan-17", section: "paciente-planificacion", related: ["plan-18", "plan-24", "plan-25"] },
  { id: "plan-18", section: "paciente-planificacion", related: ["plan-17", "plan-24", "plan-25"] },
  { id: "plan-19", section: "paciente-planificacion", related: ["plan-1", "plan-2", "plan-22"] },
  { id: "plan-20", section: "paciente-planificacion", related: ["plan-13", "plan-23", "plan-14"] },
  { id: "plan-21", section: "paciente-planificacion", related: ["plan-7", "plan-8", "plan-32"] },
  { id: "plan-22", section: "paciente-planificacion", related: ["plan-5", "plan-25", "plan-23"] },
  { id: "plan-23", section: "paciente-planificacion", related: ["plan-21", "plan-22", "plan-33"] },
  { id: "plan-24", section: "paciente-planificacion", related: ["plan-17", "plan-18", "plan-25"] },
  { id: "plan-25", section: "paciente-planificacion", related: ["plan-24", "plan-26", "plan-17"] },
  { id: "plan-26", section: "paciente-planificacion", related: ["plan-25", "plan-24", "plan-30"] },
  { id: "plan-27", section: "paciente-planificacion", related: ["plan-28", "plan-29", "plan-17"] },
  { id: "plan-28", section: "paciente-planificacion", related: ["plan-27", "plan-29", "plan-17"] },
  { id: "plan-29", section: "paciente-planificacion", related: ["plan-27", "plan-28", "plan-17"] },
  { id: "plan-30", section: "paciente-planificacion", related: ["plan-24", "plan-25", "plan-19"] },
  { id: "plan-31", section: "paciente-planificacion", related: ["plan-32", "plan-15", "plan-16"] },
  { id: "plan-32", section: "paciente-planificacion", related: ["plan-31", "plan-15", "plan-16"] },
  { id: "plan-33", section: "paciente-planificacion", related: ["plan-7", "plan-8", "plan-21"] },
  { id: "plan-34", section: "paciente-planificacion", related: ["plan-7", "plan-35"] },
  { id: "plan-35", section: "paciente-planificacion", related: ["plan-34", "plan-10", "plan-11"] },
  { id: "plan-36", section: "paciente-planificacion", related: ["plan-37", "plan-30"] },
  { id: "plan-37", section: "paciente-planificacion", related: ["plan-36", "plan-25"] },
  { id: "plan-38", section: "paciente-planificacion", related: ["plan-17", "plan-39"] },
  { id: "plan-39", section: "paciente-planificacion", related: ["plan-24", "plan-17", "plan-40"] },
  { id: "plan-40", section: "paciente-planificacion", related: ["plan-39", "plan-18"] },
  { id: "plan-41", section: "paciente-planificacion", related: ["plan-31", "plan-32", "plan-21"] },
  { id: "plan-42", section: "paciente-planificacion", related: ["plan-17", "plan-5"] },
  { id: "plan-43", section: "paciente-planificacion", related: ["plan-5", "plan-15"] },
  { id: "plan-44", section: "paciente-planificacion", related: ["plan-36", "plan-37"] },
  { id: "plan-45", section: "paciente-planificacion", related: ["plan-3", "plan-5", "plan-21", "plan-31"] },
];
