import type { HelpEntrySkeleton } from "../types";

export const PACIENTE_RECOMENDACIONES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "rec-1", section: "paciente-recomendaciones", related: ["rec-2", "rec-11", "rec-12"] },
  { id: "rec-2", section: "paciente-recomendaciones", related: ["rec-1", "rec-16"] },
  { id: "rec-3", section: "paciente-recomendaciones", related: ["rec-4", "rec-5", "rec-19"] },
  { id: "rec-4", section: "paciente-recomendaciones", related: ["rec-3", "rec-5"] },
  { id: "rec-5", section: "paciente-recomendaciones", related: ["rec-3", "rec-4"] },
  { id: "rec-6", section: "paciente-recomendaciones", related: ["rec-7", "rec-8"] },
  { id: "rec-7", section: "paciente-recomendaciones", related: ["rec-6", "rec-8"] },
  { id: "rec-8", section: "paciente-recomendaciones", related: ["rec-6", "rec-7"] },
  { id: "rec-9", section: "paciente-recomendaciones", related: ["rec-10", "rec-11"] },
  { id: "rec-10", section: "paciente-recomendaciones", related: ["rec-9", "rec-28"] },
  { id: "rec-11", section: "paciente-recomendaciones", related: ["rec-9", "rec-12"] },
  { id: "rec-12", section: "paciente-recomendaciones", related: ["rec-13", "rec-24"] },
  { id: "rec-13", section: "paciente-recomendaciones", related: ["rec-14", "rec-21"] },
  { id: "rec-14", section: "paciente-recomendaciones", related: ["rec-12", "rec-21"] },
  { id: "rec-15", section: "paciente-recomendaciones", related: ["rec-1", "rec-16"] },
  { id: "rec-16", section: "paciente-recomendaciones", related: ["rec-2", "rec-15"] },
  { id: "rec-17", section: "paciente-recomendaciones", related: ["rec-7", "rec-20"] },
  { id: "rec-18", section: "paciente-recomendaciones", related: ["rec-19", "rec-20"] },
  { id: "rec-19", section: "paciente-recomendaciones", related: ["rec-14", "rec-20"] },
  { id: "rec-20", section: "paciente-recomendaciones", related: ["rec-2", "rec-17"] },
  { id: "rec-21", section: "paciente-recomendaciones", related: ["rec-13", "rec-17"] },
  { id: "rec-22", section: "paciente-recomendaciones", related: ["rec-12", "rec-23"] },
  { id: "rec-23", section: "paciente-recomendaciones", related: ["rec-14", "rec-22"] },
  { id: "rec-24", section: "paciente-recomendaciones", related: ["rec-10", "rec-25"] },
  { id: "rec-25", section: "paciente-recomendaciones", related: ["rec-10", "rec-24"] },
  { id: "rec-26", section: "paciente-recomendaciones", related: ["rec-4", "rec-19"] },
  { id: "rec-27", section: "paciente-recomendaciones", related: ["rec-11", "rec-14"] },
  { id: "rec-28", section: "paciente-recomendaciones", related: ["rec-5", "rec-21"] },
  { id: "rec-29", section: "paciente-recomendaciones", related: ["rec-19", "rec-20"] },
  { id: "rec-30", section: "paciente-recomendaciones", related: ["rec-1", "rec-12"] },
];
