import type { HelpEntrySkeleton } from "../types";

export const PACIENTE_PORTAL_CONFIG_ENTRIES: HelpEntrySkeleton[] = [
  { id: "ppc-1", section: "paciente-portal-config", related: ["ppc-2", "ppc-3", "ppc-7"] },
  { id: "ppc-2", section: "paciente-portal-config", related: ["ppc-1", "ppc-7", "ppc-13"] },
  { id: "ppc-3", section: "paciente-portal-config", related: ["ppc-4", "ppc-5", "ppc-6"] },
  { id: "ppc-4", section: "paciente-portal-config", related: ["ppc-3", "ppc-11", "ppc-17"] },
  { id: "ppc-5", section: "paciente-portal-config", related: ["ppc-3", "ppc-14", "ppc-21"] },
  { id: "ppc-6", section: "paciente-portal-config", related: ["ppc-3", "ppc-8", "ppc-22"] },
  { id: "ppc-7", section: "paciente-portal-config", related: ["ppc-2", "ppc-6", "ppc-22"] },
  { id: "ppc-8", section: "paciente-portal-config", related: ["ppc-5", "ppc-15", "ppc-21"] },
  { id: "ppc-9", section: "paciente-portal-config", related: ["ppc-8", "ppc-10", "ppc-29"] },
  { id: "ppc-10", section: "paciente-portal-config", related: ["ppc-9", "ppc-19", "ppc-20"] },
  { id: "ppc-11", section: "paciente-portal-config", related: ["ppc-4", "ppc-12", "ppc-26"] },
  { id: "ppc-12", section: "paciente-portal-config", related: ["ppc-11", "ppc-6", "ppc-26"] },
  { id: "ppc-13", section: "paciente-portal-config", related: ["ppc-2", "ppc-24", "ppc-25"] },
  { id: "ppc-14", section: "paciente-portal-config", related: ["ppc-5", "ppc-8", "ppc-23"] },
  { id: "ppc-15", section: "paciente-portal-config", related: ["ppc-8", "ppc-6", "ppc-30"] },
  { id: "ppc-16", section: "paciente-portal-config", related: ["ppc-27", "ppc-28", "ppc-29"] },
  { id: "ppc-17", section: "paciente-portal-config", related: ["ppc-6", "ppc-22", "ppc-35"] },
  { id: "ppc-18", section: "paciente-portal-config", related: ["ppc-13", "ppc-24", "ppc-33"] },
  { id: "ppc-19", section: "paciente-portal-config", related: ["ppc-20", "ppc-29", "ppc-32"] },
  { id: "ppc-20", section: "paciente-portal-config", related: ["ppc-19", "ppc-32", "ppc-29"] },
  { id: "ppc-21", section: "paciente-portal-config", related: ["ppc-5", "ppc-14", "ppc-8"] },
  { id: "ppc-22", section: "paciente-portal-config", related: ["ppc-6", "ppc-17", "ppc-7"] },
  { id: "ppc-23", section: "paciente-portal-config", related: ["ppc-14", "ppc-4", "ppc-26"] },
  { id: "ppc-24", section: "paciente-portal-config", related: ["ppc-13", "ppc-25", "ppc-33"] },
  { id: "ppc-25", section: "paciente-portal-config", related: ["ppc-13", "ppc-24", "ppc-33"] },
  { id: "ppc-26", section: "paciente-portal-config", related: ["ppc-4", "ppc-11", "ppc-23"] },
  { id: "ppc-27", section: "paciente-portal-config", related: ["ppc-16", "ppc-28", "ppc-29"] },
  { id: "ppc-28", section: "paciente-portal-config", related: ["ppc-16", "ppc-27", "ppc-29"] },
  { id: "ppc-29", section: "paciente-portal-config", related: ["ppc-8", "ppc-9", "ppc-32"] },
  { id: "ppc-30", section: "paciente-portal-config", related: ["ppc-15", "ppc-8", "ppc-35"] },
  { id: "ppc-31", section: "paciente-portal-config", related: ["ppc-3", "ppc-7", "ppc-22"] },
  { id: "ppc-32", section: "paciente-portal-config", related: ["ppc-19", "ppc-20", "ppc-29"] },
  { id: "ppc-33", section: "paciente-portal-config", related: ["ppc-13", "ppc-17", "ppc-2"] },
  { id: "ppc-34", section: "paciente-portal-config", related: ["ppc-13", "ppc-18", "ppc-25"] },
  { id: "ppc-35", section: "paciente-portal-config", related: ["ppc-9", "ppc-15", "ppc-29"] },
];
