import type { HelpEntrySkeleton } from "../types";

export const PAGOS_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pag-1", section: "pagos", related: ["pag-2", "pag-3", "pag-15"] },
  { id: "pag-2", section: "pagos", related: ["pag-1", "pag-4", "pag-10"] },
  { id: "pag-3", section: "pagos", related: ["pag-1", "pag-4", "pag-33"] },
  { id: "pag-4", section: "pagos", related: ["pag-5", "pag-6", "pag-7", "pag-42"] },
  { id: "pag-5", section: "pagos", related: ["pag-4", "pag-6", "pag-7"] },
  { id: "pag-6", section: "pagos", related: ["pag-4", "pag-7", "pag-20"] },
  { id: "pag-7", section: "pagos", related: ["pag-4", "pag-6", "pag-8", "pag-47"] },
  { id: "pag-8", section: "pagos", related: ["pag-4", "pag-6", "pag-7"] },
  { id: "pag-9", section: "pagos", related: ["pag-1", "pag-10", "pag-11", "pag-20"] },
  { id: "pag-10", section: "pagos", related: ["pag-9", "pag-20", "pag-22", "pag-25"] },
  { id: "pag-11", section: "pagos", related: ["pag-12", "pag-13", "pag-14"] },
  { id: "pag-12", section: "pagos", related: ["pag-11", "pag-13", "pag-43"] },
  { id: "pag-13", section: "pagos", related: ["pag-11", "pag-20", "pag-47"] },
  { id: "pag-14", section: "pagos", related: ["pag-11", "pag-13", "pag-18"] },
  { id: "pag-15", section: "pagos", related: ["pag-16", "pag-17", "pag-25", "pag-27"] },
  { id: "pag-16", section: "pagos", related: ["pag-15", "pag-17", "pag-18", "pag-19"] },
  { id: "pag-17", section: "pagos", related: ["pag-16", "pag-18", "pag-44"] },
  { id: "pag-18", section: "pagos", related: ["pag-16", "pag-19", "pag-43"] },
  { id: "pag-19", section: "pagos", related: ["pag-16", "pag-18"] },
  { id: "pag-20", section: "pagos", related: ["pag-21", "pag-22", "pag-23", "pag-30"] },
  { id: "pag-21", section: "pagos", related: ["pag-20", "pag-22", "pag-31"] },
  { id: "pag-22", section: "pagos", related: ["pag-20", "pag-21", "pag-23", "pag-47"] },
  { id: "pag-23", section: "pagos", related: ["pag-20", "pag-34", "pag-48", "pag-50"] },
  { id: "pag-24", section: "pagos", related: ["pag-20", "pag-31", "pag-26"] },
  { id: "pag-25", section: "pagos", related: ["pag-26", "pag-27", "pag-31", "pag-40"] },
  { id: "pag-26", section: "pagos", related: ["pag-25", "pag-27", "pag-40"] },
  { id: "pag-27", section: "pagos", related: ["pag-26", "pag-28", "pag-40"] },
  { id: "pag-28", section: "pagos", related: ["pag-27", "pag-40", "pag-46"] },
  { id: "pag-29", section: "pagos", related: ["pag-25", "pag-30", "pag-32", "pag-35"] },
  { id: "pag-30", section: "pagos", related: ["pag-29", "pag-31", "pag-32"] },
  { id: "pag-31", section: "pagos", related: ["pag-25", "pag-30", "pag-32", "pag-33"] },
  { id: "pag-32", section: "pagos", related: ["pag-31", "pag-33", "pag-34", "pag-42"] },
  { id: "pag-33", section: "pagos", related: ["pag-32", "pag-34", "pag-23"] },
  { id: "pag-34", section: "pagos", related: ["pag-23", "pag-33", "pag-35", "pag-50"] },
  { id: "pag-35", section: "pagos", related: ["pag-29", "pag-34", "pag-36"] },
  { id: "pag-36", section: "pagos", related: ["pag-35", "pag-37", "pag-46"] },
  { id: "pag-37", section: "pagos", related: ["pag-36", "pag-44", "pag-50"] },
  { id: "pag-38", section: "pagos", related: ["pag-39", "pag-41", "pag-45"] },
  { id: "pag-39", section: "pagos", related: ["pag-38", "pag-49"] },
  { id: "pag-40", section: "pagos", related: ["pag-26", "pag-27", "pag-39"] },
  { id: "pag-41", section: "pagos", related: ["pag-38", "pag-45"] },
  { id: "pag-42", section: "pagos", related: ["pag-32", "pag-34", "pag-47"] },
  { id: "pag-43", section: "pagos", related: ["pag-9", "pag-10", "pag-11"] },
  { id: "pag-44", section: "pagos", related: ["pag-17", "pag-37"] },
  { id: "pag-45", section: "pagos", related: ["pag-41", "pag-46"] },
  { id: "pag-46", section: "pagos", related: ["pag-41", "pag-45"] },
  { id: "pag-47", section: "pagos", related: ["pag-22", "pag-30", "pag-42"] },
  { id: "pag-48", section: "pagos", related: ["pag-15", "pag-41"] },
  { id: "pag-49", section: "pagos", related: ["pag-16", "pag-38", "pag-40"] },
  { id: "pag-50", section: "pagos", related: ["pag-23", "pag-34", "pag-37"] },
];
