import type { HelpEntry } from "../types";

export const PORTAL_HORARIO_ENTRIES: HelpEntry[] = [
  {
    id: "ph-1",
    section: "portal-horario",
    question: "¿Qué es 'Mi horario'?",
    answer: "Mi horario es una herramienta de tu portal donde configuras tu rutina semanal habitual: a qué horas trabajas, entrenas, duermes y comes. Se representa como una cuadrícula semanal de lunes a domingo con las 24 horas del día. Su objetivo es que tu nutricionista conozca tu día a día y pueda adaptar tu plan. Lo encuentras en Seguimiento → Mi horario.",
    related: ["ph-2", "ph-3"],
    keywords: ["mi horario", "rutina", "qué es", "seguimiento"],
  },
  {
    id: "ph-2",
    section: "portal-horario",
    question: "¿Para qué sirve configurar mi horario?",
    answer: "Sirve para que tu nutricionista entienda cuándo tienes tiempo real para comer, cocinar o entrenar, y ajuste tu plan a tu vida y no al revés. Si trabajas por turnos, haces deporte por la tarde o madrugas mucho, tu plan será diferente. También te ayuda a ti a visualizar tus huecos y organizar mejor las comidas. Cuanto más fiel sea a tu rutina, más útil será.",
    related: ["ph-1", "ph-28"],
    keywords: ["para qué", "utilidad", "nutricionista", "rutina"],
  },
  {
    id: "ph-3",
    section: "portal-horario",
    question: "¿Cómo funciona la cuadrícula semanal?",
    answer: "La cuadrícula muestra los siete días de la semana en columnas (lunes a domingo) y las 24 horas del día en filas. Cada celda representa una hora concreta de un día concreto. Sobre esa cuadrícula colocas bloques que ocupan las horas que quieras (por ejemplo, 'Trabajo de 9:00 a 17:00' el lunes). Es una vista visual para ver tu semana de un vistazo.",
    related: ["ph-1", "ph-4"],
    keywords: ["cuadrícula", "semana", "grid", "días", "horas"],
  },
  {
    id: "ph-4",
    section: "portal-horario",
    question: "¿Qué días incluye el horario?",
    answer: "Incluye los siete días de la semana, de lunes a domingo. Cada día se edita por separado, así que puedes poner rutinas distintas para días laborables y fin de semana. No hay concepto de 'semana A' o 'semana B': se asume una semana tipo que se repite. Si tu semana cambia mucho, guarda la más habitual.",
    related: ["ph-3", "ph-22"],
    keywords: ["días", "lunes a domingo", "semana", "laborables"],
  },
  {
    id: "ph-5",
    section: "portal-horario",
    question: "¿Qué horas cubre?",
    answer: "Las 24 horas del día, desde las 00:00 hasta las 23:59. Puedes colocar bloques en cualquier franja, incluidas horas nocturnas si trabajas de noche o tu sueño va de madrugada a mañana. Para ver las horas que no caben en pantalla puedes hacer scroll vertical dentro de la cuadrícula.",
    related: ["ph-3", "ph-24"],
    keywords: ["horas", "24 horas", "madrugada", "nocturno"],
  },
  {
    id: "ph-6",
    section: "portal-horario",
    question: "¿Qué tipos de bloques existen?",
    answer: "Hay cinco tipos de bloques: TRABAJO (tu jornada laboral o estudios), DEPORTE (entrenamientos y actividad física), COMIDA (desayunos, comidas, cenas, snacks), SUEÑO (horas en las que duermes) y OTRO (cualquier rutina que no encaje en los anteriores, como clases, terapia, viajes). Elegir el tipo correcto es importante porque determina el color y las estadísticas.",
    related: ["ph-7", "ph-12"],
    keywords: ["tipos", "bloques", "trabajo", "deporte", "comida", "sueño", "otro"],
  },
  {
    id: "ph-7",
    section: "portal-horario",
    question: "¿Cómo creo un bloque nuevo?",
    answer: "Pulsa en una hora vacía de la cuadrícula o en el botón 'Añadir bloque'. Se abre un editor modal donde eliges día, hora de inicio, hora de fin, tipo y, si quieres, una nota. Al guardar, el bloque aparece pintado en la cuadrícula con el color de su tipo. Puedes crear tantos como necesites.",
    related: ["ph-8", "ph-9"],
    keywords: ["crear", "nuevo bloque", "añadir"],
  },
  {
    id: "ph-8",
    section: "portal-horario",
    question: "¿Cómo es el editor modal?",
    answer: "El editor modal es una pequeña ventana que se abre al crear o editar un bloque. Tiene campos para el día de la semana, la hora de inicio, la hora de fin, el tipo de bloque y una nota opcional. Abajo hay botones para guardar o cancelar. Es la misma interfaz tanto para crear como para modificar.",
    related: ["ph-7", "ph-13"],
    keywords: ["modal", "editor", "ventana", "formulario"],
  },
  {
    id: "ph-9",
    section: "portal-horario",
    question: "¿Qué pongo en el campo 'Día'?",
    answer: "Elige el día de la semana al que pertenece el bloque: lunes, martes, miércoles, jueves, viernes, sábado o domingo. Cada bloque pertenece a un solo día. Si una rutina se repite varios días, créala una vez y luego usa la función de duplicar día, o crea un bloque por cada día.",
    related: ["ph-20", "ph-4"],
    keywords: ["día", "campo día", "lunes", "domingo"],
  },
  {
    id: "ph-10",
    section: "portal-horario",
    question: "¿Qué hora de inicio debo poner?",
    answer: "La hora a la que empieza la actividad, en formato 24 horas. Por ejemplo, para un entrenamiento que empieza a las siete y media de la mañana, pon 07:30. Puedes usar incrementos de media hora o de una hora según tu horario real. Cuanto más ajustado, mejor refleja tu día.",
    related: ["ph-11", "ph-5"],
    keywords: ["hora inicio", "desde", "comienza"],
  },
  {
    id: "ph-11",
    section: "portal-horario",
    question: "¿Qué hora de fin debo poner?",
    answer: "La hora a la que termina la actividad. Debe ser posterior a la hora de inicio. Si un bloque cruza la medianoche (por ejemplo, sueño de 23:00 a 07:00), lo normal es partirlo en dos: uno hasta las 23:59 y otro desde las 00:00, o usar la lógica que te permita la interfaz en tu versión.",
    related: ["ph-10", "ph-5"],
    keywords: ["hora fin", "hasta", "termina"],
  },
  {
    id: "ph-12",
    section: "portal-horario",
    question: "¿Cómo elijo el tipo de bloque?",
    answer: "En el campo 'Tipo' del editor eliges entre TRABAJO, DEPORTE, COMIDA, SUEÑO u OTRO. Piensa cuál describe mejor la actividad: una reunión es TRABAJO, un paseo rápido puede ser DEPORTE, un café con algo de comer es COMIDA. Si dudas, usa OTRO. El tipo determina el color y las métricas.",
    related: ["ph-6", "ph-15"],
    keywords: ["tipo", "seleccionar", "categoría"],
  },
  {
    id: "ph-13",
    section: "portal-horario",
    question: "¿Para qué sirve la nota del bloque?",
    answer: "La nota es un texto corto opcional para detallar el bloque, como 'Reunión equipo', 'Pádel con amigos' o 'Cena fuera'. No es imprescindible, pero ayuda a tu nutricionista a entender mejor tu semana. También te sirve a ti de recordatorio. Deja el campo vacío si no aporta nada.",
    related: ["ph-8", "ph-28"],
    keywords: ["nota", "descripción", "detalle", "comentario"],
  },
  {
    id: "ph-14",
    section: "portal-horario",
    question: "¿Puedo elegir el color del bloque?",
    answer: "El color es automático y depende del tipo de bloque: cada tipo tiene un color fijo para que toda la cuadrícula sea coherente. Por ejemplo, todos los bloques de DEPORTE se ven del mismo color, y los de SUEÑO de otro. No puedes cambiarlo manualmente, y eso ayuda a leer la semana de un vistazo.",
    related: ["ph-15", "ph-6"],
    keywords: ["color", "automático", "colores"],
  },
  {
    id: "ph-15",
    section: "portal-horario",
    question: "¿Qué color tiene cada tipo?",
    answer: "Cada tipo usa un color consistente: TRABAJO suele ir en un tono sobrio, DEPORTE en uno más vivo relacionado con actividad, COMIDA en un color cálido, SUEÑO en uno apagado o azulado y OTRO en un color neutro. Los tonos exactos pueden variar según el tema (claro u oscuro), pero la relación tipo-color se mantiene.",
    related: ["ph-14", "ph-6"],
    keywords: ["colores", "tipo color", "paleta"],
  },
  {
    id: "ph-16",
    section: "portal-horario",
    question: "¿Cómo edito un bloque existente?",
    answer: "Pulsa sobre el bloque en la cuadrícula y se abre el mismo editor modal que usaste para crearlo, pero con los datos cargados. Cambia lo que necesites (hora, tipo, nota) y guarda. El bloque se actualiza en el sitio. Si cambias el día, se moverá a la columna correspondiente.",
    related: ["ph-7", "ph-17"],
    keywords: ["editar", "modificar", "cambiar bloque"],
  },
  {
    id: "ph-17",
    section: "portal-horario",
    question: "¿Puedo mover un bloque a otra hora?",
    answer: "Sí. Abre el bloque pulsándolo y cambia su hora de inicio y de fin en el editor. Al guardar, se repinta en la nueva franja. Según la versión, también puede estar disponible arrastrar el bloque directamente sobre la cuadrícula, pero editar desde el modal funciona siempre.",
    related: ["ph-16", "ph-18"],
    keywords: ["mover", "arrastrar", "cambiar hora"],
  },
  {
    id: "ph-18",
    section: "portal-horario",
    question: "¿Cómo elimino un bloque?",
    answer: "Abre el bloque pulsándolo y dentro del editor verás un botón de eliminar (papelera o texto 'Borrar'). Confirma y el bloque desaparece de la cuadrícula. No hay papelera de reciclaje: si te arrepientes, créalo de nuevo. Eliminar un bloque no afecta al resto.",
    related: ["ph-16", "ph-25"],
    keywords: ["eliminar", "borrar", "quitar bloque"],
  },
  {
    id: "ph-19",
    section: "portal-horario",
    question: "¿Puedo duplicar un día entero?",
    answer: "Sí. La función 'Duplicar día' copia todos los bloques de un día a otros días que elijas. Es muy útil si tu rutina de lunes a viernes es casi igual: configuras el lunes, lo duplicas a martes, miércoles, jueves y viernes, y luego ajustas lo que cambie. Ahorra mucho tiempo.",
    related: ["ph-20", "ph-4"],
    keywords: ["duplicar", "copiar día", "replicar"],
  },
  {
    id: "ph-20",
    section: "portal-horario",
    question: "¿Cómo duplico un día a otros?",
    answer: "Pulsa el icono o botón de duplicar junto al día que quieres copiar. Se abre un selector donde marcas los días destino (por ejemplo, de martes a viernes). Al confirmar, todos los bloques del día origen se crean también en los destinos. Si los destinos ya tenían bloques, normalmente se sobreescriben: revisa antes.",
    related: ["ph-19", "ph-23"],
    keywords: ["duplicar a", "copiar otros días", "destino"],
  },
  {
    id: "ph-21",
    section: "portal-horario",
    question: "¿Qué son las plantillas?",
    answer: "Las plantillas son horarios prehechos que cubren casos frecuentes. En vez de partir de cero, aplicas una plantilla y luego la ajustas. Actualmente hay tres: 'Semana laboral' (oficina de lunes a viernes), 'Deportista' (entrenamientos fijos por la tarde o mañana) y 'Flexible' (horarios irregulares o autónomos). Son un punto de partida.",
    related: ["ph-22", "ph-23"],
    keywords: ["plantillas", "predefinidas", "prebuilt"],
  },
  {
    id: "ph-22",
    section: "portal-horario",
    question: "¿Qué plantillas hay disponibles?",
    answer: "Hay tres plantillas: 'Semana laboral' pensada para jornadas de oficina de 9 a 17-18h con comidas a horas fijas; 'Deportista' con entrenamientos programados y comidas adaptadas al rendimiento; y 'Flexible' con una rutina menos estricta para quien tiene horarios variables. Cada una rellena la cuadrícula con bloques orientativos que tú ajustas después.",
    related: ["ph-21", "ph-23"],
    keywords: ["plantillas disponibles", "laboral", "deportista", "flexible"],
  },
  {
    id: "ph-23",
    section: "portal-horario",
    question: "¿Qué pasa al aplicar una plantilla?",
    answer: "Al aplicar una plantilla, los bloques que contiene reemplazan lo que haya en la cuadrícula: es decir, sobreescribe tu horario actual. Por eso conviene aplicarla al principio, antes de haber hecho mucho trabajo. Después puedes editar, mover o eliminar bloques hasta adaptarla a tu caso real. La app suele pedirte confirmación.",
    related: ["ph-21", "ph-25"],
    keywords: ["aplicar plantilla", "sobreescribe", "reemplaza"],
  },
  {
    id: "ph-24",
    section: "portal-horario",
    question: "¿Qué KPIs muestra la página?",
    answer: "En la parte superior o inferior verás indicadores con tu distribución semanal: total de horas de trabajo, de deporte, de sueño y, según la versión, de comida. Así ves de un vistazo si duermes poco, si haces suficiente actividad o si trabajas demasiadas horas. Estos números se recalculan solos cuando cambias bloques.",
    related: ["ph-25", "ph-6"],
    keywords: ["kpis", "estadísticas", "horas semanales"],
  },
  {
    id: "ph-25",
    section: "portal-horario",
    question: "¿Qué significan las horas de trabajo, deporte y sueño?",
    answer: "Son la suma total de horas a la semana que has marcado con cada tipo. Por ejemplo, si tienes 8 bloques de TRABAJO de lunes a viernes de 9 a 17, el KPI mostrará 40 horas. Las de DEPORTE suman tus entrenamientos y las de SUEÑO tus horas nocturnas. Te ayuda a detectar desequilibrios.",
    related: ["ph-24", "ph-6"],
    keywords: ["sumas", "totales", "horas trabajo deporte sueño"],
  },
  {
    id: "ph-26",
    section: "portal-horario",
    question: "¿Hay vista de día o solo semana?",
    answer: "La vista principal es semanal, con los siete días a la vez. En móvil, como la pantalla es estrecha, puede aparecer una vista de día que se recorre deslizando de izquierda a derecha. En escritorio sueles ver la semana completa. En ambos casos, los datos son los mismos.",
    related: ["ph-27", "ph-29"],
    keywords: ["vista día", "vista semana", "visualización"],
  },
  {
    id: "ph-27",
    section: "portal-horario",
    question: "¿Cómo hago scroll por las horas?",
    answer: "Si tu horario incluye horas que no caben de golpe en pantalla, desplázate verticalmente dentro de la cuadrícula con la rueda del ratón o con el dedo en móvil. También puedes acercar la vista para ver más horas a la vez, según lo permita la interfaz. Las horas tempranas suelen aparecer arriba y las nocturnas abajo.",
    related: ["ph-5", "ph-26"],
    keywords: ["scroll", "desplazar", "ver horas"],
  },
  {
    id: "ph-28",
    section: "portal-horario",
    question: "¿Mi nutricionista ve mi horario?",
    answer: "Sí. Tu nutricionista ve tu horario en la pestaña 'General' de tu ficha, con la misma cuadrícula que tú editas. Le sirve para diseñar planes realistas: saber si comes en el trabajo, cuándo entrenas o cuántas horas duermes. Solo lo ve tu nutri, no otros pacientes ni usuarios ajenos.",
    related: ["ph-29", "ph-2"],
    keywords: ["nutricionista", "ficha", "ver horario"],
  },
  {
    id: "ph-29",
    section: "portal-horario",
    question: "¿Quién más puede ver mi horario?",
    answer: "Solo tú y tu nutricionista tenéis acceso a tu horario. No se comparte con otros pacientes, no aparece en redes ni se publica en ningún sitio. Se guarda cifrado en la base de datos, asociado a tu cuenta. Si un día cambias de nutri, el nuevo profesional lo verá, igual que ocurre con el resto de tu ficha.",
    related: ["ph-28", "ph-38"],
    keywords: ["privacidad", "quién ve", "acceso"],
  },
  {
    id: "ph-30",
    section: "portal-horario",
    question: "¿Puedo editarlo desde el móvil?",
    answer: "Sí. El portal está adaptado a móvil, así que puedes crear, editar y borrar bloques desde tu teléfono. En pantallas pequeñas la cuadrícula se reorganiza (vista por día) para que se vea bien. Es práctico para ajustar el horario en cualquier momento, por ejemplo cuando cambias de turno o añades un entrenamiento.",
    related: ["ph-26", "ph-27"],
    keywords: ["móvil", "teléfono", "responsive"],
  },
  {
    id: "ph-31",
    section: "portal-horario",
    question: "¿Cómo borro todo el horario?",
    answer: "Hay un botón para vaciar la cuadrícula y empezar de cero. Pulsa 'Borrar todo' o similar y confirma. Se eliminan todos los bloques de los siete días. Úsalo solo si quieres rehacer el horario desde cero, por ejemplo tras un cambio grande de rutina. La acción suele pedir confirmación porque no se puede deshacer.",
    related: ["ph-18", "ph-23"],
    keywords: ["borrar todo", "vaciar", "empezar de cero"],
  },
  {
    id: "ph-32",
    section: "portal-horario",
    question: "¿Se guardan los cambios automáticamente?",
    answer: "En la mayoría de casos sí: al crear, editar o eliminar un bloque, el cambio se guarda en el servidor en ese mismo momento. Verás un indicador de 'Guardado' cuando termine. Si en tu versión hay un botón 'Guardar cambios', pulsa siempre antes de salir para no perder lo que has modificado.",
    related: ["ph-33", "ph-36"],
    keywords: ["guardar", "automático", "cambios"],
  },
  {
    id: "ph-33",
    section: "portal-horario",
    question: "¿Qué pasa si cierro sin guardar?",
    answer: "Si los cambios se guardan automáticamente, al cerrar la pestaña no se pierde nada. Si hay botón 'Guardar' y sales sin pulsarlo, las modificaciones hechas desde la última vez que guardaste pueden perderse. Por seguridad, revisa que aparezca el aviso de guardado antes de salir.",
    related: ["ph-32", "ph-18"],
    keywords: ["cerrar sin guardar", "perder cambios"],
  },
  {
    id: "ph-34",
    section: "portal-horario",
    question: "¿Qué es la integración con Google Calendar?",
    answer: "En esta misma página hay una tarjeta para conectar tu cuenta de Google Calendar con Annonia. Su función es sincronizar tus citas con el nutricionista con tu calendario personal de Google, para que te aparezcan allí junto al resto de tus eventos. Es independiente de 'Mi horario' y opcional.",
    related: ["ph-35", "ph-36"],
    keywords: ["google calendar", "integración", "qué es"],
  },
  {
    id: "ph-35",
    section: "portal-horario",
    question: "¿Google Calendar sincroniza mi horario?",
    answer: "No. La integración con Google Calendar sincroniza tus CITAS con el nutricionista, no tu horario semanal. Los bloques de trabajo, deporte, sueño o comida de 'Mi horario' no se envían a Google. Si quieres esas rutinas en tu calendario personal, tendrás que crearlas tú allí. El horario solo vive dentro de Annonia.",
    related: ["ph-34", "ph-37"],
    keywords: ["sincronizar", "horario google", "no sincroniza"],
  },
  {
    id: "ph-36",
    section: "portal-horario",
    question: "¿Cómo conecto Google Calendar?",
    answer: "En la tarjeta 'Integración con Google Calendar' pulsa 'Conectar'. Se abre la pantalla de Google donde inicias sesión y das permiso a Annonia para crear eventos en tu calendario. Al volver, la tarjeta mostrará tu cuenta conectada. A partir de ahí, cada cita nueva con tu nutri aparecerá también en Google Calendar.",
    related: ["ph-34", "ph-37"],
    keywords: ["conectar google", "enlazar calendario", "vincular"],
  },
  {
    id: "ph-37",
    section: "portal-horario",
    question: "¿Cómo desconecto Google Calendar?",
    answer: "En la misma tarjeta pulsa 'Desconectar'. Annonia dejará de crear eventos en tu calendario y se eliminará el permiso de acceso. Las citas que ya estuvieran creadas en Google seguirán ahí, pero no se actualizarán si cambian en Annonia. Puedes volver a conectar cuando quieras.",
    related: ["ph-36", "ph-38"],
    keywords: ["desconectar", "desvincular", "revocar"],
  },
  {
    id: "ph-38",
    section: "portal-horario",
    question: "¿Qué datos comparte Annonia con Google?",
    answer: "Al conectar, Annonia solo envía a Google los datos necesarios para crear tus citas: título (por ejemplo, 'Cita con tu nutricionista'), fecha, hora y duración. No se envía tu horario, tus medidas, tu plan ni ningún otro dato de salud. Puedes revocar el acceso desde Google en cualquier momento, en la sección de aplicaciones conectadas de tu cuenta.",
    related: ["ph-29", "ph-37"],
    keywords: ["datos compartidos", "privacidad google", "qué envía"],
  },
  {
    id: "ph-39",
    section: "portal-horario",
    question: "Es mi primera vez, ¿por dónde empiezo?",
    answer: "La primera vez la cuadrícula está vacía. Lo más rápido es aplicar una plantilla que se parezca a tu rutina (laboral, deportista o flexible) y luego ajustar los bloques uno a uno. Si prefieres partir de cero, empieza por bloques de sueño y de trabajo en un día, duplícalo al resto y añade deporte y comidas. En quince minutos tienes la semana.",
    related: ["ph-21", "ph-19"],
    keywords: ["primer uso", "empezar", "primera vez", "vacío"],
  },
  {
    id: "ph-40",
    section: "portal-horario",
    question: "¿Por qué es útil para mi plan y mi adherencia?",
    answer: "Un plan de alimentación funciona mucho mejor cuando encaja con tus horarios reales. Si tu nutri sabe que sales de trabajar a las 20:00, no te pondrá una cena que requiera cocinar 40 minutos. Si ve que entrenas al mediodía, ajustará qué comes antes y después. Tener tu horario bien puesto mejora la adherencia a las comidas y reduce saltárselas por falta de tiempo.",
    related: ["ph-2", "ph-28"],
    keywords: ["adherencia", "plan", "horarios", "comidas", "utilidad"],
  },
];
