import type { HelpEntrySkeleton } from "../types";

export const PORTAL_GENERAL_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pg-1", section: "portal-general", related: ["pg-2", "pg-6"] },
  { id: "pg-2", section: "portal-general", related: ["pg-1", "pg-3"] },
  { id: "pg-3", section: "portal-general", related: ["pg-2", "pg-4"] },
  { id: "pg-4", section: "portal-general", related: ["pg-3", "pg-5"] },
  { id: "pg-5", section: "portal-general", related: ["pg-4", "pg-32"] },
  { id: "pg-6", section: "portal-general", related: ["pg-7", "pg-17"] },
  { id: "pg-7", section: "portal-general", related: ["pg-6", "pg-11"] },
  { id: "pg-8", section: "portal-general", related: ["pg-19", "pg-32"] },
  { id: "pg-9", section: "portal-general", related: ["pg-10", "pg-26"] },
  { id: "pg-10", section: "portal-general", related: ["pg-9", "pg-26"] },
  { id: "pg-11", section: "portal-general", related: ["pg-12", "pg-13"] },
  { id: "pg-12", section: "portal-general", related: ["pg-11", "pg-22"] },
  { id: "pg-13", section: "portal-general", related: ["pg-11", "pg-20"] },
  { id: "pg-14", section: "portal-general", related: ["pg-32", "pg-33"] },
  { id: "pg-15", section: "portal-general", related: ["pg-19", "pg-33"] },
  { id: "pg-16", section: "portal-general", related: ["pg-8", "pg-15"] },
  { id: "pg-17", section: "portal-general", related: ["pg-18", "pg-6"] },
  { id: "pg-18", section: "portal-general", related: ["pg-17", "pg-21"] },
  { id: "pg-19", section: "portal-general", related: ["pg-12", "pg-20"] },
  { id: "pg-20", section: "portal-general", related: ["pg-19", "pg-12"] },
  { id: "pg-21", section: "portal-general", related: ["pg-13", "pg-22"] },
  { id: "pg-22", section: "portal-general", related: ["pg-1", "pg-7"] },
  { id: "pg-23", section: "portal-general", related: ["pg-12", "pg-7"] },
  { id: "pg-24", section: "portal-general", related: ["pg-25", "pg-40"] },
  { id: "pg-25", section: "portal-general", related: ["pg-24", "pg-30"] },
  { id: "pg-26", section: "portal-general", related: ["pg-9", "pg-10"] },
  { id: "pg-27", section: "portal-general", related: ["pg-11", "pg-40"] },
  { id: "pg-28", section: "portal-general", related: ["pg-25", "pg-14"] },
  { id: "pg-29", section: "portal-general", related: ["pg-5", "pg-14"] },
  { id: "pg-30", section: "portal-general", related: ["pg-15", "pg-17"] },
  { id: "pg-31", section: "portal-general", related: ["pg-13", "pg-14"] },
  { id: "pg-32", section: "portal-general", related: ["pg-27", "pg-24"] },
  { id: "pg-33", section: "portal-general", related: ["pg-14", "pg-34"] },
  { id: "pg-34", section: "portal-general", related: ["pg-33", "pg-14"] },
  { id: "pg-35", section: "portal-general", related: ["pg-17", "pg-24"] },
  { id: "pg-36", section: "portal-general", related: ["pg-17", "pg-35"] },
  { id: "pg-37", section: "portal-general", related: ["pg-24", "pg-35"] },
  { id: "pg-38", section: "portal-general", related: ["pg-27", "pg-32"] },
  { id: "pg-39", section: "portal-general", related: ["pg-14", "pg-33"] },
  { id: "pg-40", section: "portal-general", related: ["pg-22", "pg-5"] },
];
