import type { HelpEntrySkeleton } from "../types";

export const PORTAL_DASHBOARD_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pdd-1", section: "portal-dashboard", related: ["pdd-2", "pdd-3"] },
  { id: "pdd-2", section: "portal-dashboard", related: ["pdd-1", "pdd-9"] },
  { id: "pdd-3", section: "portal-dashboard", related: ["pdd-4", "pdd-20"] },
  { id: "pdd-4", section: "portal-dashboard", related: ["pdd-3", "pdd-29"] },
  { id: "pdd-5", section: "portal-dashboard", related: ["pdd-6", "pdd-7"] },
  { id: "pdd-6", section: "portal-dashboard", related: ["pdd-5", "pdd-7"] },
  { id: "pdd-7", section: "portal-dashboard", related: ["pdd-5", "pdd-6"] },
  { id: "pdd-8", section: "portal-dashboard", related: ["pdd-9", "pdd-10"] },
  { id: "pdd-9", section: "portal-dashboard", related: ["pdd-8", "pdd-10"] },
  { id: "pdd-10", section: "portal-dashboard", related: ["pdd-8", "pdd-9"] },
  { id: "pdd-11", section: "portal-dashboard", related: ["pdd-12", "pdd-13"] },
  { id: "pdd-12", section: "portal-dashboard", related: ["pdd-11", "pdd-13"] },
  { id: "pdd-13", section: "portal-dashboard", related: ["pdd-11", "pdd-12"] },
  { id: "pdd-14", section: "portal-dashboard", related: ["pdd-15", "pdd-16"] },
  { id: "pdd-15", section: "portal-dashboard", related: ["pdd-14", "pdd-16"] },
  { id: "pdd-16", section: "portal-dashboard", related: ["pdd-14", "pdd-15"] },
  { id: "pdd-17", section: "portal-dashboard", related: ["pdd-18", "pdd-23"] },
  { id: "pdd-18", section: "portal-dashboard", related: ["pdd-19", "pdd-23"] },
  { id: "pdd-19", section: "portal-dashboard", related: ["pdd-18", "pdd-31"] },
  { id: "pdd-20", section: "portal-dashboard", related: ["pdd-21", "pdd-22"] },
  { id: "pdd-21", section: "portal-dashboard", related: ["pdd-20", "pdd-22"] },
  { id: "pdd-22", section: "portal-dashboard", related: ["pdd-20", "pdd-21"] },
  { id: "pdd-23", section: "portal-dashboard", related: ["pdd-5", "pdd-24"] },
  { id: "pdd-24", section: "portal-dashboard", related: ["pdd-8", "pdd-23"] },
  { id: "pdd-25", section: "portal-dashboard", related: ["pdd-1", "pdd-28"] },
  { id: "pdd-26", section: "portal-dashboard", related: ["pdd-27", "pdd-29"] },
  { id: "pdd-27", section: "portal-dashboard", related: ["pdd-5", "pdd-26"] },
  { id: "pdd-28", section: "portal-dashboard", related: ["pdd-19", "pdd-35"] },
  { id: "pdd-29", section: "portal-dashboard", related: ["pdd-21", "pdd-38"] },
  { id: "pdd-30", section: "portal-dashboard", related: ["pdd-6", "pdd-19"] },
  { id: "pdd-31", section: "portal-dashboard", related: ["pdd-18", "pdd-19"] },
  { id: "pdd-32", section: "portal-dashboard", related: ["pdd-33", "pdd-34"] },
  { id: "pdd-33", section: "portal-dashboard", related: ["pdd-32", "pdd-34"] },
  { id: "pdd-34", section: "portal-dashboard", related: ["pdd-1", "pdd-25"] },
  { id: "pdd-35", section: "portal-dashboard", related: ["pdd-28", "pdd-38"] },
  { id: "pdd-36", section: "portal-dashboard", related: ["pdd-37", "pdd-38"] },
  { id: "pdd-37", section: "portal-dashboard", related: ["pdd-36", "pdd-38"] },
  { id: "pdd-38", section: "portal-dashboard", related: ["pdd-36", "pdd-37"] },
  { id: "pdd-39", section: "portal-dashboard", related: ["pdd-19", "pdd-28"] },
  { id: "pdd-40", section: "portal-dashboard", related: ["pdd-26", "pdd-34"] },
];
