import type { HelpEntrySkeleton } from "../types";

export const PORTAL_ENTREGABLES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pe-1", section: "portal-entregables", related: ["pe-2", "pe-3"] },
  { id: "pe-2", section: "portal-entregables", related: ["pe-1", "pe-33"] },
  { id: "pe-3", section: "portal-entregables", related: ["pe-4", "pe-6"] },
  { id: "pe-4", section: "portal-entregables", related: ["pe-3", "pe-17"] },
  { id: "pe-5", section: "portal-entregables", related: ["pe-6", "pe-7"] },
  { id: "pe-6", section: "portal-entregables", related: ["pe-5", "pe-32"] },
  { id: "pe-7", section: "portal-entregables", related: ["pe-11", "pe-5"] },
  { id: "pe-8", section: "portal-entregables", related: ["pe-13", "pe-12"] },
  { id: "pe-9", section: "portal-entregables", related: ["pe-34", "pe-22"] },
  { id: "pe-10", section: "portal-entregables", related: ["pe-20", "pe-19"] },
  { id: "pe-11", section: "portal-entregables", related: ["pe-26", "pe-7"] },
  { id: "pe-12", section: "portal-entregables", related: ["pe-8", "pe-2"] },
  { id: "pe-13", section: "portal-entregables", related: ["pe-8", "pe-21"] },
  { id: "pe-14", section: "portal-entregables", related: ["pe-2", "pe-33"] },
  { id: "pe-15", section: "portal-entregables", related: ["pe-4", "pe-16"] },
  { id: "pe-16", section: "portal-entregables", related: ["pe-4", "pe-15"] },
  { id: "pe-17", section: "portal-entregables", related: ["pe-4", "pe-15"] },
  { id: "pe-18", section: "portal-entregables", related: ["pe-4", "pe-14"] },
  { id: "pe-19", section: "portal-entregables", related: ["pe-20", "pe-6"] },
  { id: "pe-20", section: "portal-entregables", related: ["pe-19", "pe-2"] },
  { id: "pe-21", section: "portal-entregables", related: ["pe-31", "pe-13"] },
  { id: "pe-22", section: "portal-entregables", related: ["pe-35", "pe-9"] },
  { id: "pe-23", section: "portal-entregables", related: ["pe-24", "pe-29"] },
  { id: "pe-24", section: "portal-entregables", related: ["pe-25", "pe-23"] },
  { id: "pe-25", section: "portal-entregables", related: ["pe-24"] },
  { id: "pe-26", section: "portal-entregables", related: ["pe-11", "pe-7"] },
  { id: "pe-27", section: "portal-entregables", related: ["pe-28", "pe-15"] },
  { id: "pe-28", section: "portal-entregables", related: ["pe-4", "pe-12"] },
  { id: "pe-29", section: "portal-entregables", related: ["pe-30", "pe-32"] },
  { id: "pe-30", section: "portal-entregables", related: ["pe-29", "pe-32"] },
  { id: "pe-31", section: "portal-entregables", related: ["pe-21", "pe-1"] },
  { id: "pe-32", section: "portal-entregables", related: ["pe-29", "pe-30"] },
  { id: "pe-33", section: "portal-entregables", related: ["pe-14", "pe-2"] },
  { id: "pe-34", section: "portal-entregables", related: ["pe-9", "pe-22"] },
  { id: "pe-35", section: "portal-entregables", related: ["pe-22", "pe-9"] },
];
