import type { HelpEntrySkeleton } from "../types";

export const PORTAL_HORARIO_ENTRIES: HelpEntrySkeleton[] = [
  { id: "ph-1", section: "portal-horario", related: ["ph-2", "ph-3"] },
  { id: "ph-2", section: "portal-horario", related: ["ph-1", "ph-28"] },
  { id: "ph-3", section: "portal-horario", related: ["ph-1", "ph-4"] },
  { id: "ph-4", section: "portal-horario", related: ["ph-3", "ph-22"] },
  { id: "ph-5", section: "portal-horario", related: ["ph-3", "ph-24"] },
  { id: "ph-6", section: "portal-horario", related: ["ph-7", "ph-12"] },
  { id: "ph-7", section: "portal-horario", related: ["ph-8", "ph-9"] },
  { id: "ph-8", section: "portal-horario", related: ["ph-7", "ph-13"] },
  { id: "ph-9", section: "portal-horario", related: ["ph-20", "ph-4"] },
  { id: "ph-10", section: "portal-horario", related: ["ph-11", "ph-5"] },
  { id: "ph-11", section: "portal-horario", related: ["ph-10", "ph-5"] },
  { id: "ph-12", section: "portal-horario", related: ["ph-6", "ph-15"] },
  { id: "ph-13", section: "portal-horario", related: ["ph-8", "ph-28"] },
  { id: "ph-14", section: "portal-horario", related: ["ph-15", "ph-6"] },
  { id: "ph-15", section: "portal-horario", related: ["ph-14", "ph-6"] },
  { id: "ph-16", section: "portal-horario", related: ["ph-7", "ph-17"] },
  { id: "ph-17", section: "portal-horario", related: ["ph-16", "ph-18"] },
  { id: "ph-18", section: "portal-horario", related: ["ph-16", "ph-25"] },
  { id: "ph-19", section: "portal-horario", related: ["ph-20", "ph-4"] },
  { id: "ph-20", section: "portal-horario", related: ["ph-19", "ph-23"] },
  { id: "ph-21", section: "portal-horario", related: ["ph-22", "ph-23"] },
  { id: "ph-22", section: "portal-horario", related: ["ph-21", "ph-23"] },
  { id: "ph-23", section: "portal-horario", related: ["ph-21", "ph-25"] },
  { id: "ph-24", section: "portal-horario", related: ["ph-25", "ph-6"] },
  { id: "ph-25", section: "portal-horario", related: ["ph-24", "ph-6"] },
  { id: "ph-26", section: "portal-horario", related: ["ph-27", "ph-29"] },
  { id: "ph-27", section: "portal-horario", related: ["ph-5", "ph-26"] },
  { id: "ph-28", section: "portal-horario", related: ["ph-29", "ph-2"] },
  { id: "ph-29", section: "portal-horario", related: ["ph-28", "ph-38"] },
  { id: "ph-30", section: "portal-horario", related: ["ph-26", "ph-27"] },
  { id: "ph-31", section: "portal-horario", related: ["ph-18", "ph-23"] },
  { id: "ph-32", section: "portal-horario", related: ["ph-33", "ph-36"] },
  { id: "ph-33", section: "portal-horario", related: ["ph-32", "ph-18"] },
  { id: "ph-34", section: "portal-horario", related: ["ph-35", "ph-36"] },
  { id: "ph-35", section: "portal-horario", related: ["ph-34", "ph-37"] },
  { id: "ph-36", section: "portal-horario", related: ["ph-34", "ph-37"] },
  { id: "ph-37", section: "portal-horario", related: ["ph-36", "ph-38"] },
  { id: "ph-38", section: "portal-horario", related: ["ph-29", "ph-37"] },
  { id: "ph-39", section: "portal-horario", related: ["ph-21", "ph-19"] },
  { id: "ph-40", section: "portal-horario", related: ["ph-2", "ph-28"] },
];
