import type { HelpEntrySkeleton } from "../types";

export const PORTAL_PERFIL_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pp-1", section: "portal-perfil", related: ["pp-2", "pp-3"] },
  { id: "pp-2", section: "portal-perfil", related: ["pp-1", "pp-3"] },
  { id: "pp-3", section: "portal-perfil", related: ["pp-4", "pp-5"] },
  { id: "pp-4", section: "portal-perfil", related: ["pp-3", "pp-5"] },
  { id: "pp-5", section: "portal-perfil", related: ["pp-3", "pp-33"] },
  { id: "pp-6", section: "portal-perfil", related: ["pp-3", "pp-34"] },
  { id: "pp-7", section: "portal-perfil", related: ["pp-8", "pp-36"] },
  { id: "pp-8", section: "portal-perfil", related: ["pp-7", "pp-9"] },
  { id: "pp-9", section: "portal-perfil", related: ["pp-8", "pp-10"] },
  { id: "pp-10", section: "portal-perfil", related: ["pp-11", "pp-25"] },
  { id: "pp-11", section: "portal-perfil", related: ["pp-10", "pp-25"] },
  { id: "pp-12", section: "portal-perfil", related: ["pp-13", "pp-14"] },
  { id: "pp-13", section: "portal-perfil", related: ["pp-12", "pp-14"] },
  { id: "pp-14", section: "portal-perfil", related: ["pp-12", "pp-13"] },
  { id: "pp-15", section: "portal-perfil", related: ["pp-16", "pp-17"] },
  { id: "pp-16", section: "portal-perfil", related: ["pp-15", "pp-17"] },
  { id: "pp-17", section: "portal-perfil", related: ["pp-15", "pp-18"] },
  { id: "pp-18", section: "portal-perfil", related: ["pp-17", "pp-19"] },
  { id: "pp-19", section: "portal-perfil", related: ["pp-15", "pp-20"] },
  { id: "pp-20", section: "portal-perfil", related: ["pp-21", "pp-30"] },
  { id: "pp-21", section: "portal-perfil", related: ["pp-20", "pp-30"] },
  { id: "pp-22", section: "portal-perfil", related: ["pp-23", "pp-31"] },
  { id: "pp-23", section: "portal-perfil", related: ["pp-22", "pp-38"] },
  { id: "pp-24", section: "portal-perfil", related: ["pp-25", "pp-26"] },
  { id: "pp-25", section: "portal-perfil", related: ["pp-24", "pp-26"] },
  { id: "pp-26", section: "portal-perfil", related: ["pp-25", "pp-27"] },
  { id: "pp-27", section: "portal-perfil", related: ["pp-28", "pp-40"] },
  { id: "pp-28", section: "portal-perfil", related: ["pp-27", "pp-29"] },
  { id: "pp-29", section: "portal-perfil", related: ["pp-28", "pp-30"] },
  { id: "pp-30", section: "portal-perfil", related: ["pp-25", "pp-26"] },
  { id: "pp-31", section: "portal-perfil", related: ["pp-12", "pp-32"] },
  { id: "pp-32", section: "portal-perfil", related: ["pp-31", "pp-33"] },
  { id: "pp-33", section: "portal-perfil", related: ["pp-5", "pp-34"] },
  { id: "pp-34", section: "portal-perfil", related: ["pp-4", "pp-33"] },
  { id: "pp-35", section: "portal-perfil", related: ["pp-22", "pp-36"] },
  { id: "pp-36", section: "portal-perfil", related: ["pp-7", "pp-37"] },
  { id: "pp-37", section: "portal-perfil", related: ["pp-10", "pp-36"] },
  { id: "pp-38", section: "portal-perfil", related: ["pp-39", "pp-40"] },
  { id: "pp-39", section: "portal-perfil", related: ["pp-38", "pp-40"] },
  { id: "pp-40", section: "portal-perfil", related: ["pp-27", "pp-28"] },
];
