import type { HelpEntrySkeleton } from "../types";

export const PORTAL_SEGUIMIENTO_ENTRIES: HelpEntrySkeleton[] = [
  { id: "ps-1", section: "portal-seguimiento", related: ["ps-2", "ps-3"] },
  { id: "ps-2", section: "portal-seguimiento", related: ["ps-1", "ps-22"] },
  { id: "ps-3", section: "portal-seguimiento", related: ["ps-1", "ps-4"] },
  { id: "ps-4", section: "portal-seguimiento", related: ["ps-5", "ps-6"] },
  { id: "ps-5", section: "portal-seguimiento", related: ["ps-4", "ps-6"] },
  { id: "ps-6", section: "portal-seguimiento", related: ["ps-4", "ps-5"] },
  { id: "ps-7", section: "portal-seguimiento", related: ["ps-8", "ps-9"] },
  { id: "ps-8", section: "portal-seguimiento", related: ["ps-7", "ps-9"] },
  { id: "ps-9", section: "portal-seguimiento", related: ["ps-7", "ps-8"] },
  { id: "ps-10", section: "portal-seguimiento", related: ["ps-7", "ps-18"] },
  { id: "ps-11", section: "portal-seguimiento", related: ["ps-12", "ps-13"] },
  { id: "ps-12", section: "portal-seguimiento", related: ["ps-11", "ps-13"] },
  { id: "ps-13", section: "portal-seguimiento", related: ["ps-11", "ps-14"] },
  { id: "ps-14", section: "portal-seguimiento", related: ["ps-13", "ps-26"] },
  { id: "ps-15", section: "portal-seguimiento", related: ["ps-2", "ps-16"] },
  { id: "ps-16", section: "portal-seguimiento", related: ["ps-17", "ps-25"] },
  { id: "ps-17", section: "portal-seguimiento", related: ["ps-16", "ps-25"] },
  { id: "ps-18", section: "portal-seguimiento", related: ["ps-19", "ps-10"] },
  { id: "ps-19", section: "portal-seguimiento", related: ["ps-18"] },
  { id: "ps-20", section: "portal-seguimiento", related: ["ps-21", "ps-28"] },
  { id: "ps-21", section: "portal-seguimiento", related: ["ps-20", "ps-28"] },
  { id: "ps-22", section: "portal-seguimiento", related: ["ps-23", "ps-30"] },
  { id: "ps-23", section: "portal-seguimiento", related: ["ps-22", "ps-24"] },
  { id: "ps-24", section: "portal-seguimiento", related: ["ps-23", "ps-27"] },
  { id: "ps-25", section: "portal-seguimiento", related: ["ps-16", "ps-17"] },
  { id: "ps-26", section: "portal-seguimiento", related: ["ps-14", "ps-44"] },
  { id: "ps-27", section: "portal-seguimiento", related: ["ps-24", "ps-29"] },
  { id: "ps-28", section: "portal-seguimiento", related: ["ps-20", "ps-29"] },
  { id: "ps-29", section: "portal-seguimiento", related: ["ps-22", "ps-32"] },
  { id: "ps-30", section: "portal-seguimiento", related: ["ps-20", "ps-21", "ps-22"] },
  { id: "ps-31", section: "portal-seguimiento", related: ["ps-33"] },
  { id: "ps-32", section: "portal-seguimiento", related: ["ps-27"] },
  { id: "ps-33", section: "portal-seguimiento", related: ["ps-34", "ps-40"] },
  { id: "ps-34", section: "portal-seguimiento", related: ["ps-33"] },
  { id: "ps-35", section: "portal-seguimiento", related: ["ps-36"] },
  { id: "ps-36", section: "portal-seguimiento", related: ["ps-35", "ps-47"] },
  { id: "ps-37", section: "portal-seguimiento", related: ["ps-38"] },
  { id: "ps-38", section: "portal-seguimiento", related: ["ps-37"] },
  { id: "ps-39", section: "portal-seguimiento", related: ["ps-40"] },
  { id: "ps-40", section: "portal-seguimiento", related: ["ps-39"] },
  { id: "ps-41", section: "portal-seguimiento", related: ["ps-42", "ps-43"] },
  { id: "ps-42", section: "portal-seguimiento", related: ["ps-41"] },
  { id: "ps-43", section: "portal-seguimiento", related: ["ps-41", "ps-44"] },
  { id: "ps-44", section: "portal-seguimiento", related: ["ps-26", "ps-60"] },
  { id: "ps-45", section: "portal-seguimiento", related: ["ps-29", "ps-46"] },
  { id: "ps-46", section: "portal-seguimiento", related: ["ps-29"] },
  { id: "ps-47", section: "portal-seguimiento", related: ["ps-35", "ps-46"] },
  { id: "ps-48", section: "portal-seguimiento", related: ["ps-31"] },
  { id: "ps-49", section: "portal-seguimiento", related: ["ps-4", "ps-5"] },
  { id: "ps-50", section: "portal-seguimiento", related: ["ps-18", "ps-26"] },
  { id: "ps-51", section: "portal-seguimiento", related: ["ps-11", "ps-12"] },
  { id: "ps-52", section: "portal-seguimiento", related: ["ps-24", "ps-29"] },
  { id: "ps-53", section: "portal-seguimiento", related: ["ps-33", "ps-60"] },
  { id: "ps-54", section: "portal-seguimiento", related: ["ps-43", "ps-55"] },
  { id: "ps-55", section: "portal-seguimiento", related: ["ps-31", "ps-54"] },
  { id: "ps-56", section: "portal-seguimiento", related: ["ps-27", "ps-49"] },
  { id: "ps-57", section: "portal-seguimiento", related: ["ps-7", "ps-9"] },
  { id: "ps-58", section: "portal-seguimiento", related: ["ps-3"] },
  { id: "ps-59", section: "portal-seguimiento", related: ["ps-1", "ps-3"] },
  { id: "ps-60", section: "portal-seguimiento", related: ["ps-43", "ps-44", "ps-53"] },
];
