import type { HelpEntrySkeleton } from "../types";

export const PORTAL_CITAS_ENTRIES: HelpEntrySkeleton[] = [
  { id: "pc-1", section: "portal-citas", related: ["pc-2", "pc-3"] },
  { id: "pc-2", section: "portal-citas", related: ["pc-1", "pc-20"] },
  { id: "pc-3", section: "portal-citas", related: ["pc-4", "pc-5", "pc-6", "pc-7", "pc-8"] },
  { id: "pc-4", section: "portal-citas", related: ["pc-3", "pc-11", "pc-13"] },
  { id: "pc-5", section: "portal-citas", related: ["pc-3", "pc-15", "pc-20"] },
  { id: "pc-6", section: "portal-citas", related: ["pc-3", "pc-13", "pc-14"] },
  { id: "pc-7", section: "portal-citas", related: ["pc-3", "pc-15", "pc-16"] },
  { id: "pc-8", section: "portal-citas", related: ["pc-3", "pc-36", "pc-37"] },
  { id: "pc-9", section: "portal-citas", related: ["pc-10", "pc-11", "pc-12"] },
  { id: "pc-10", section: "portal-citas", related: ["pc-9", "pc-11", "pc-24"] },
  { id: "pc-11", section: "portal-citas", related: ["pc-10", "pc-12", "pc-23"] },
  { id: "pc-12", section: "portal-citas", related: ["pc-9", "pc-11", "pc-13"] },
  { id: "pc-13", section: "portal-citas", related: ["pc-9", "pc-14", "pc-32"] },
  { id: "pc-14", section: "portal-citas", related: ["pc-13", "pc-32", "pc-50"] },
  { id: "pc-15", section: "portal-citas", related: ["pc-4", "pc-16", "pc-17"] },
  { id: "pc-16", section: "portal-citas", related: ["pc-15", "pc-17", "pc-7"] },
  { id: "pc-17", section: "portal-citas", related: ["pc-18", "pc-19", "pc-15"] },
  { id: "pc-18", section: "portal-citas", related: ["pc-17", "pc-19", "pc-12"] },
  { id: "pc-19", section: "portal-citas", related: ["pc-17", "pc-18", "pc-14"] },
  { id: "pc-20", section: "portal-citas", related: ["pc-5", "pc-21", "pc-22"] },
  { id: "pc-21", section: "portal-citas", related: ["pc-20", "pc-22"] },
  { id: "pc-22", section: "portal-citas", related: ["pc-20", "pc-23", "pc-46"] },
  { id: "pc-23", section: "portal-citas", related: ["pc-22", "pc-49"] },
  { id: "pc-24", section: "portal-citas", related: ["pc-2", "pc-20", "pc-22"] },
  { id: "pc-25", section: "portal-citas", related: ["pc-2", "pc-9"] },
  { id: "pc-26", section: "portal-citas", related: ["pc-8", "pc-38"] },
  { id: "pc-27", section: "portal-citas", related: ["pc-10", "pc-11"] },
  { id: "pc-28", section: "portal-citas", related: ["pc-10", "pc-11", "pc-27"] },
  { id: "pc-29", section: "portal-citas", related: ["pc-30", "pc-31", "pc-33"] },
  { id: "pc-30", section: "portal-citas", related: ["pc-29", "pc-31", "pc-33"] },
  { id: "pc-31", section: "portal-citas", related: ["pc-29", "pc-30"] },
  { id: "pc-32", section: "portal-citas", related: ["pc-14", "pc-50"] },
  { id: "pc-33", section: "portal-citas", related: ["pc-29", "pc-30", "pc-48"] },
  { id: "pc-34", section: "portal-citas", related: ["pc-9", "pc-41"] },
  { id: "pc-35", section: "portal-citas", related: ["pc-17", "pc-36", "pc-47"] },
  { id: "pc-36", section: "portal-citas", related: ["pc-7", "pc-37", "pc-47"] },
  { id: "pc-37", section: "portal-citas", related: ["pc-36", "pc-7"] },
  { id: "pc-38", section: "portal-citas", related: ["pc-8", "pc-39"] },
  { id: "pc-39", section: "portal-citas", related: ["pc-38", "pc-40"] },
  { id: "pc-40", section: "portal-citas", related: ["pc-39"] },
  { id: "pc-41", section: "portal-citas", related: ["pc-29", "pc-26"] },
  { id: "pc-42", section: "portal-citas", related: ["pc-4", "pc-15", "pc-44"] },
  { id: "pc-43", section: "portal-citas", related: ["pc-27", "pc-22"] },
  { id: "pc-44", section: "portal-citas", related: ["pc-42", "pc-9"] },
  { id: "pc-45", section: "portal-citas", related: ["pc-22", "pc-46"] },
  { id: "pc-46", section: "portal-citas", related: ["pc-45", "pc-36"] },
  { id: "pc-47", section: "portal-citas", related: ["pc-36", "pc-33", "pc-9"] },
  { id: "pc-48", section: "portal-citas", related: ["pc-20", "pc-1"] },
  { id: "pc-49", section: "portal-citas", related: ["pc-23", "pc-22"] },
  { id: "pc-50", section: "portal-citas", related: ["pc-32", "pc-33", "pc-29"] },
];
