import type { HelpEntrySkeleton } from "../types";

export const REPORTES_ENTRIES: HelpEntrySkeleton[] = [
  { id: "rep-1", section: "reportes", related: ["rep-2", "rep-3"] },
  { id: "rep-2", section: "reportes", related: ["rep-1", "rep-29"] },
  { id: "rep-3", section: "reportes", related: ["rep-1", "rep-29"] },
  { id: "rep-4", section: "reportes", related: ["rep-5", "rep-6"] },
  { id: "rep-5", section: "reportes", related: ["rep-4", "rep-6", "rep-26"] },
  { id: "rep-6", section: "reportes", related: ["rep-4", "rep-5", "rep-20"] },
  { id: "rep-7", section: "reportes", related: ["rep-8", "rep-9", "rep-10"] },
  { id: "rep-8", section: "reportes", related: ["rep-7", "rep-9"] },
  { id: "rep-9", section: "reportes", related: ["rep-7", "rep-10"] },
  { id: "rep-10", section: "reportes", related: ["rep-9", "rep-7"] },
  { id: "rep-11", section: "reportes", related: ["rep-12", "rep-13"] },
  { id: "rep-12", section: "reportes", related: ["rep-11", "rep-13"] },
  { id: "rep-13", section: "reportes", related: ["rep-11", "rep-12"] },
  { id: "rep-14", section: "reportes", related: ["rep-15", "rep-16"] },
  { id: "rep-15", section: "reportes", related: ["rep-14", "rep-16"] },
  { id: "rep-16", section: "reportes", related: ["rep-14", "rep-15"] },
  { id: "rep-17", section: "reportes", related: ["rep-18", "rep-29"] },
  { id: "rep-18", section: "reportes", related: ["rep-17", "rep-40"] },
  { id: "rep-19", section: "reportes", related: ["rep-20", "rep-39"] },
  { id: "rep-20", section: "reportes", related: ["rep-19", "rep-39"] },
  { id: "rep-21", section: "reportes", related: ["rep-22", "rep-23"] },
  { id: "rep-22", section: "reportes", related: ["rep-21", "rep-23"] },
  { id: "rep-23", section: "reportes", related: ["rep-21", "rep-22"] },
  { id: "rep-24", section: "reportes", related: ["rep-3", "rep-25"] },
  { id: "rep-25", section: "reportes", related: ["rep-26", "rep-29"] },
  { id: "rep-26", section: "reportes", related: ["rep-25", "rep-29"] },
  { id: "rep-27", section: "reportes", related: ["rep-28", "rep-29"] },
  { id: "rep-28", section: "reportes", related: ["rep-27", "rep-30"] },
  { id: "rep-29", section: "reportes", related: ["rep-17", "rep-3"] },
  { id: "rep-30", section: "reportes", related: ["rep-27", "rep-28"] },
  { id: "rep-31", section: "reportes", related: ["rep-32", "rep-33"] },
  { id: "rep-32", section: "reportes", related: ["rep-31", "rep-33"] },
  { id: "rep-33", section: "reportes", related: ["rep-31", "rep-34"] },
  { id: "rep-34", section: "reportes", related: ["rep-31", "rep-33"] },
  { id: "rep-35", section: "reportes", related: ["rep-27", "rep-26"] },
  { id: "rep-36", section: "reportes", related: ["rep-4", "rep-25"] },
  { id: "rep-37", section: "reportes", related: ["rep-32", "rep-38"] },
  { id: "rep-38", section: "reportes", related: ["rep-37", "rep-33"] },
  { id: "rep-39", section: "reportes", related: ["rep-26", "rep-27"] },
  { id: "rep-40", section: "reportes", related: ["rep-18", "rep-17"] },
];
